# -*- Mode: Makefile -*-
# vim:syntax=make:
export MODULE
MODULE = ddep
CORE = arm
TARGET = rcvt
include $(MMROOT)/video/makefiles/Make.nmf.config

first: ddep.conf
	@echo ddep.conf is created

include $(MMROOT)/video/makefiles/Make.nmf.rules

