/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
#include <vfm_common.idt>

void memoryRequirements(t_uint32 deblocking_param_struct[10],
						ts_ddep_buffer_descriptor paramBufferDesc,
						ts_ddep_buffer_descriptor linkListBufferDesc,
						ts_ddep_buffer_descriptor debugBufferDesc,
						t_uint16 error_map,
						t_uint16 *ptr,
						t_uint8 BufCountActual,



						t_bool disable,
						void *mpc_vfm_mem_ctxt);

void provideBufferForI(t_uint32 buffer_i_frame[2]);

