/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
void portSettings(t_uint32 width,t_uint32 height,
				  t_uint8 aspect_ratio,t_uint8 nHorizontal,
				  t_uint8 nVertical,t_uint8 color_primary);
