/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
void sendportSettings(t_uint32 width,t_uint32 height, t_uint32 concealment_flag,t_uint32 sorenson_flag,t_uint8 aspect_ratio,t_uint8 color_primary,t_uint32 error_reporting_enable);

void sendImmediateIFlag(t_uint8 immediate_i_flag);

