/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <t1xhv_common.idt>
#include <t1xhv_vdc_mpeg4.idt>

interface mpeg4dec.arm_nmf.api.update_algo { 

void updateAlgo(t_t1xhv_command command);

} 
