BUILD_MMDSP_PROC_audio/noise_reduction=bin
NO_STD_BUILD_audio/noise_reduction=1
BUILD_MMDSP_NMF_audio/noise_reduction=bin
BUILD_ARM_PROC_audio/noise_reduction=bin
BUILD_ARM_CODE_audio/noise_reduction=bin
BUILD_ARM_NMF_audio/noise_reduction=bin
BUILD_XP70_SIA_CODE_audio/noise_reduction=false
