/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <t1xhv_common.idt>
#include <t1xhv_vdc_jpeg.idt>

interface jpegdec.mpc.api.update_algo {	

 /** @addtogroup sdcJpegUpdateAlgoGroup updateAlgo
 *  @ingroup sdcJpegProvidedInterfaceGroup
 *  @{
 */
/*!
 Description : (Not yet implemented) Update the configuration of a specific NMF algo component.
 *   
 * \remarks	For the corresponding ITF server name(s), please refer to \ref sdcJpegConfigurationGroup
 */ 
void updateAlgo(t_t1xhv_command command);

/** @} */ // end of sdcJpegUpdateAlgoGroup

} // interface jpegdec.mpc.api.update_algo

