# vim:syntax=make:
# -*- Mode: Makefile -*-
MAKEFILE_CONFIG=mmdsp

include $(MM_MAKEFILES_DIR)/SharedCheck.mk

TESTLISTS= testlist.lst
DATABASE = misc_nmf
TEST_TAG =$(MMDSPPROCESSOR)

include $(MM_MAKEFILES_DIR)/AudioTest.mk
