BUILD_MMDSP_PROC_video/components/mpeg4dec=bin
NO_STD_BUILD_video/components/mpeg4dec=1
BUILD_MMDSP_NMF_video/components/mpeg4dec=bin
BUILD_ARM_PROC_video/components/mpeg4dec=bin
BUILD_ARM_CODE_video/components/mpeg4dec=src
BUILD_ARM_NMF_video/components/mpeg4dec=src
BUILD_XP70_SIA_CODE_video/components/mpeg4dec=false
