CC := gcc
CFLAGS   := -g -Wall -Wextra -std=c99 -pedantic-errors -pthread
INCDIRS  := -I./include -I../core/include
CPPFLAGS := $(INCDIRS)
LDFLAGS  :=
LDLIBS   :=

.PHONY: all clean test test_ng

all: $(OBJ)
	echo Nothing to do for anchor

test_mb:
	echo No white box test for anchor

test_fb:
	echo No white box test for anchor

test_cn:
	echo No white box test for anchor

clean:
	rm -f $(OBJ) $(TEST_OBJ)
