#!/bin/sh
cd /mnt/dth/DTH/iq_tunning/streaming_control/StillPicture/Launch/Width
echo 3280 | dthfilter -w u16 > value
cd /mnt/dth/DTH/iq_tunning/streaming_control/StillPicture/Launch/Height
echo 2466 | dthfilter -w u16 > value

cd /mnt/dth/DTH/iq_tunning/streaming_control/ViewFinder/Launch/Width
echo 864 | dthfilter -w u16 > value
cd /mnt/dth/DTH/iq_tunning/streaming_control/ViewFinder/Launch/Height
echo 480 | dthfilter -w u16 > value

cd /mnt/dth/DTH/iq_tunning/streaming_control/Video/Launch/Width
echo 176 | dthfilter -w u16 > value
cd /mnt/dth/DTH/iq_tunning/streaming_control/Video/Launch/Height
echo 144 | dthfilter -w u16 > value
