/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
 
interface trace.api.trace {
    void traceWrite16(t_uint32 channel, t_uint16 value);
    void traceWrite16T(t_uint32 channel, t_uint16 value);
    void traceWrite32(t_uint32 channel, t_uint32 value);
    void traceWrite32T(t_uint32 channel, t_uint32 value);
}
