BUILD_MMDSP_PROC_video/components/registers_def=bin
NO_STD_BUILD_video/components/registers_def=1
BUILD_MMDSP_NMF_video/components/registers_def=bin
BUILD_ARM_PROC_video/components/registers_def=bin
BUILD_ARM_CODE_video/components/registers_def=src
BUILD_ARM_NMF_video/components/registers_def=bin
BUILD_XP70_SIA_CODE_video/components/registers_def=false
