/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
 
/*!
 * \brief Interface exception.handler
 *
 * The exception.handler interface must be implement
 * by a component in order to provide a interrupt handler that will
 * be called by the execution engine when the corresponding interface
 * occure (must be registered though the component manager API).
 */
interface exception.handler
{
    void handler();
}
