/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#ifndef __ST_OST_GROUP_MAP__

#define power2(x) (1 << x)

#define FIXED_GROUP_TRACE_ERROR 130
#define FIXED_GROUP_TRACE_WARNING 131
#define FIXED_GROUP_TRACE_FLOW 138
#define FIXED_GROUP_TRACE_DEBUG 137
#define FIXED_GROUP_TRACE_API 132
#define FIXED_GROUP_TRACE_OMX_API 150
#define FIXED_GROUP_TRACE_OMX_BUFFER 151
#define FIXED_GROUP_TRACE_ALWAYS 152
#define FIXED_GROUP_TRACE_USER1 153
#define FIXED_GROUP_TRACE_USER2 154
#define FIXED_GROUP_TRACE_USER3 155
#define FIXED_GROUP_TRACE_USER4 156
#define FIXED_GROUP_TRACE_USER5 157
#define FIXED_GROUP_TRACE_USER6 158
#define FIXED_GROUP_TRACE_USER7 159
#define FIXED_GROUP_TRACE_USER8 160

#define TRACE_GROUP_BIT_MASK_0 FIXED_GROUP_TRACE_ERROR
#define TRACE_GROUP_BIT_MASK_1 FIXED_GROUP_TRACE_WARNING
#define TRACE_GROUP_BIT_MASK_2 FIXED_GROUP_TRACE_FLOW
#define TRACE_GROUP_BIT_MASK_3 FIXED_GROUP_TRACE_DEBUG
#define TRACE_GROUP_BIT_MASK_4 FIXED_GROUP_TRACE_API
#define TRACE_GROUP_BIT_MASK_5 FIXED_GROUP_TRACE_OMX_API
#define TRACE_GROUP_BIT_MASK_6 FIXED_GROUP_TRACE_OMX_BUFFER
#define TRACE_GROUP_BIT_MASK_7 FIXED_GROUP_TRACE_ALWAYS
#define TRACE_GROUP_BIT_MASK_8 FIXED_GROUP_TRACE_USER1
#define TRACE_GROUP_BIT_MASK_9 FIXED_GROUP_TRACE_USER2
#define TRACE_GROUP_BIT_MASK_10 FIXED_GROUP_TRACE_USER3
#define TRACE_GROUP_BIT_MASK_11 FIXED_GROUP_TRACE_USER4
#define TRACE_GROUP_BIT_MASK_12 FIXED_GROUP_TRACE_USER5
#define TRACE_GROUP_BIT_MASK_13 FIXED_GROUP_TRACE_USER6
#define TRACE_GROUP_BIT_MASK_14 FIXED_GROUP_TRACE_USER7
#define TRACE_GROUP_BIT_MASK_15 FIXED_GROUP_TRACE_USER8

#define TRACE_ERROR power2(0)
#define TRACE_WARNING power2(1)
#define TRACE_FLOW power2(2)
#define TRACE_DEBUG power2(3)
#define TRACE_API power2(4)
#define TRACE_OMX_API power2(5)
#define TRACE_OMX_BUFFER power2(6)
#define TRACE_ALWAYS power2(7)
#define TRACE_USER1 power2(8)
#define TRACE_USER2 power2(9)
#define TRACE_USER3 power2(10)
#define TRACE_USER4 power2(11)
#define TRACE_USER5 power2(12)
#define TRACE_USER6 power2(13)
#define TRACE_USER7 power2(14)
#define TRACE_USER8 power2(15)

#endif
