PRIVATE_FLASHTOOLBACKEND_TOOLS_PATH := $(abspath $(TOOLS_PATH))
PRIVATE_FLASHTOOLBACKEND_GIT_DIR := $(PRIVATE_FLASHTOOLBACKEND_TOOLS_PATH)/platform/flash_kit/flash_tool_backend

ifdef TARGET_OUT_INTERMEDIATES
  PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM:=$(abspath $(TARGET_OUT_INTERMEDIATES))/flash_kit/flash_tool_backend
  $(shell rm $(PRIVATE_FLASHTOOLBACKEND_GIT_DIR)/tool*.txt 2>/dev/null)
  $(shell mkdir -p $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM))
  $(shell cp -rp $(PRIVATE_FLASHTOOLBACKEND_GIT_DIR)/* $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM))
else
  PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM:=$(PRIVATE_FLASHTOOLBACKEND_GIT_DIR)
endif

PRIVATE_FLASHTOOLBACKEND_ANT_HOME := $(ANT_HOME)
PRIVATE_FLASHTOOLBACKEND_ANT4ECLIPSE_HOME := $(ANT4ECLIPSE_HOME)
PRIVATE_FLASHTOOLBACKEND_FLASH_KIT_TARGET_DIR := $(FLASHKIT_INSTALL_BASE)/flashkit

PRIVATE_FLASHKIT_INTERIM_TOOLS_DIR := $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM)/..
PRIVATE_FLASHKIT_TOOLS_VERSION := $(PRIVATE_FLASHTOOLBACKEND_FLASH_KIT_TARGET_DIR)/tools_version.txt

PRIVATE_FLASHTOOLBACKEND_FLAGS := \
 FLASH_KIT_TARGET_DIR=$(PRIVATE_FLASHTOOLBACKEND_FLASH_KIT_TARGET_DIR) \
 ANT_HOME=$(PRIVATE_FLASHTOOLBACKEND_ANT_HOME) \
 ANT4ECLIPSE_HOME=$(PRIVATE_FLASHTOOLBACKEND_ANT4ECLIPSE_HOME) \
 STE_PLATFORM=$(FLASHKIT_SET_HWCONFIG) \
 TARGET_OUT_INTERMEDIATES=$(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM) \
 FTB_GIT_DIR=$(PRIVATE_FLASHTOOLBACKEND_GIT_DIR)

st-ericsson-flashkit: build_flash_tool_backend $(PRIVATE_FLASHKIT_TOOLS_VERSION)

.phony: build_flash_tool_backend clean_flash_tool_backend distclean_flash_tool_backend

build_flash_tool_backend:
	@$(PRIVATE_FLASHTOOLBACKEND_FLAGS) $(MAKE) -C $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM) -f Makefile
	@$(PRIVATE_FLASHTOOLBACKEND_FLAGS) $(MAKE) -C $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM) -f Makefile install

clean_flash_tool_backend:
	@$(MAKE) -C $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM) -f Makefile clean

distclean_flash_tool_backend:
	@$(PRIVATE_FLASHTOOLBACKEND_FLAGS) $(MAKE) -C $(PRIVATE_FLASHTOOLBACKEND_OUT_INTERIM) -f Makefile distclean
	rm -f $(PRIVATE_FLASHKIT_TOOLS_VERSION)

clean: clean_flash_tool_backend

$(PRIVATE_FLASHKIT_TOOLS_VERSION): build_assemble_tool_cli build_flash_tool_cli build_flash_tool_backend build_sign_tool_cli
	@echo "Creating tools version info ..."
	@find $(PRIVATE_FLASHKIT_INTERIM_TOOLS_DIR) -maxdepth 2 -name "tool_version.txt" -and -not -regex ".*flash_script_engine.*" | xargs -I{} cat {} > $@
