BUILD_MMDSP_PROC_video/components/resource_manager=bin
NO_STD_BUILD_video/components/resource_manager=1
BUILD_MMDSP_NMF_video/components/resource_manager=bin
BUILD_ARM_PROC_video/components/resource_manager=bin
BUILD_ARM_CODE_video/components/resource_manager=bin
BUILD_ARM_NMF_video/components/resource_manager=bin
BUILD_XP70_SIA_CODE_video/components/resource_manager=false
