#
# Copyright (C) ST-Ericsson SA 2011. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

## Directories in which to decent in the given order
DIRECTORIES=lib exe

include $(MM_MAKEFILES_DIR)/SharedDispatch.mk
