BUILD_MMDSP_PROC_audio/gsmhr=bin
NO_STD_BUILD_audio/gsmhr=1
BUILD_MMDSP_NMF_audio/gsmhr=bin
BUILD_ARM_PROC_audio/gsmhr=bin
BUILD_ARM_CODE_audio/gsmhr=src
BUILD_ARM_NMF_audio/gsmhr=src
BUILD_XP70_SIA_CODE_audio/gsmhr=false
