# -*- Mode: Makefile -*-
# vim:syntax=make:

include $(MM_MAKEFILES_DIR)/VideoStdConfig.mk

all: install

install:
	$(GEN_LN) videotools $(INSTALL_TOOLS_DIR)/videotools


include $(MM_MAKEFILES_DIR)/VideoStdRules.mk

