#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#
# DejaGnu test script config file for interactive programs (TESTLEVEL=2)
#
# Written by Per.Sigmond@itr.no (Per Sigmond)
#

set UNIT_ROOT_DIR ..
set TOOL "./test/test-cli"
set MODULE_NAME "libstecom"
source "$UNIT_ROOT_DIR/dejagnu/lib/unix-tl2.exp"

