
include ../../config/config.mk

################################################################################
#                                    GNS                                       #
################################################################################

GNS_MOD := gns

GNS_DIR := srce

GNS_SRC := gns.c


GNS_INCL := -Iincl -I../cgps/incl -I../lsim/incl -I../halgps/incl

GNS_OBJ := obj

GNS_FLAGS := 

LIB := GNS

include ../../config/build.mk