/*
 * LPP_GNSS-OrbitModel.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP_PDU-Definitions"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LPP_GNSS_OrbitModel_H_
#define	_LPP_GNSS_OrbitModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NavModelKeplerianSet.h"
#include "LPP_NavModelNAV-KeplerianSet.h"
#include "LPP_NavModelCNAV-KeplerianSet.h"
#include "LPP_NavModel-GLONASS-ECEF.h"
#include "LPP_NavModel-SBAS-ECEF.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_OrbitModel_PR {
	LPP_GNSS_OrbitModel_PR_NOTHING,	/* No components present */
	LPP_GNSS_OrbitModel_PR_keplerianSet,
	LPP_GNSS_OrbitModel_PR_nav_KeplerianSet,
	LPP_GNSS_OrbitModel_PR_cnav_KeplerianSet,
	LPP_GNSS_OrbitModel_PR_glonass_ECEF,
	LPP_GNSS_OrbitModel_PR_sbas_ECEF,
	/* Extensions may appear below */
	
} LPP_GNSS_OrbitModel_PR;

/* LPP_GNSS-OrbitModel */
typedef struct LPP_GNSS_OrbitModel {
	LPP_GNSS_OrbitModel_PR present;
	union LPP_GNSS_OrbitModel_u {
		LPP_NavModelKeplerianSet_t	 keplerianSet;
		LPP_NavModelNAV_KeplerianSet_t	 nav_KeplerianSet;
		LPP_NavModelCNAV_KeplerianSet_t	 cnav_KeplerianSet;
		LPP_NavModel_GLONASS_ECEF_t	 glonass_ECEF;
		LPP_NavModel_SBAS_ECEF_t	 sbas_ECEF;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_OrbitModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_OrbitModel;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_OrbitModel_H_ */
