/*
 * LPP_GNSS-AlmanacElement.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP_PDU-Definitions"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LPP_GNSS_AlmanacElement_H_
#define	_LPP_GNSS_AlmanacElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_AlmanacKeplerianSet.h"
#include "LPP_AlmanacNAV-KeplerianSet.h"
#include "LPP_AlmanacReducedKeplerianSet.h"
#include "LPP_AlmanacMidiAlmanacSet.h"
#include "LPP_AlmanacGLONASS-AlmanacSet.h"
#include "LPP_AlmanacECEF-SBAS-AlmanacSet.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_AlmanacElement_PR {
	LPP_GNSS_AlmanacElement_PR_NOTHING,	/* No components present */
	LPP_GNSS_AlmanacElement_PR_keplerianAlmanacSet,
	LPP_GNSS_AlmanacElement_PR_keplerianNAV_Almanac,
	LPP_GNSS_AlmanacElement_PR_keplerianReducedAlmanac,
	LPP_GNSS_AlmanacElement_PR_keplerianMidiAlmanac,
	LPP_GNSS_AlmanacElement_PR_keplerianGLONASS,
	LPP_GNSS_AlmanacElement_PR_ecef_SBAS_Almanac,
	/* Extensions may appear below */
	
} LPP_GNSS_AlmanacElement_PR;

/* LPP_GNSS-AlmanacElement */
typedef struct LPP_GNSS_AlmanacElement {
	LPP_GNSS_AlmanacElement_PR present;
	union LPP_GNSS_AlmanacElement_u {
		LPP_AlmanacKeplerianSet_t	 keplerianAlmanacSet;
		LPP_AlmanacNAV_KeplerianSet_t	 keplerianNAV_Almanac;
		LPP_AlmanacReducedKeplerianSet_t	 keplerianReducedAlmanac;
		LPP_AlmanacMidiAlmanacSet_t	 keplerianMidiAlmanac;
		LPP_AlmanacGLONASS_AlmanacSet_t	 keplerianGLONASS;
		LPP_AlmanacECEF_SBAS_AlmanacSet_t	 ecef_SBAS_Almanac;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_AlmanacElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_AlmanacElement;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_AlmanacElement_H_ */
