/*
 * LPP_PRS-Info.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP_PDU-Definitions"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LPP_PRS_Info_H_
#define	_LPP_PRS_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_PRS_Info__prs_Bandwidth {
	LPP_PRS_Info__prs_Bandwidth_n6	= 0,
	LPP_PRS_Info__prs_Bandwidth_n15	= 1,
	LPP_PRS_Info__prs_Bandwidth_n25	= 2,
	LPP_PRS_Info__prs_Bandwidth_n50	= 3,
	LPP_PRS_Info__prs_Bandwidth_n75	= 4,
	LPP_PRS_Info__prs_Bandwidth_n100	= 5
	/*
	 * Enumeration is extensible
	 */
} e_LPP_PRS_Info__prs_Bandwidth;
typedef enum LPP_PRS_Info__numDL_Frames {
	LPP_PRS_Info__numDL_Frames_sf_1	= 0,
	LPP_PRS_Info__numDL_Frames_sf_2	= 1,
	LPP_PRS_Info__numDL_Frames_sf_4	= 2,
	LPP_PRS_Info__numDL_Frames_sf_6	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LPP_PRS_Info__numDL_Frames;
typedef enum LPP_PRS_Info__prs_MutingInfo_r9_PR {
	LPP_PRS_Info__prs_MutingInfo_r9_PR_NOTHING,	/* No components present */
	LPP_PRS_Info__prs_MutingInfo_r9_PR_po2_r9,
	LPP_PRS_Info__prs_MutingInfo_r9_PR_po4_r9,
	LPP_PRS_Info__prs_MutingInfo_r9_PR_po8_r9,
	LPP_PRS_Info__prs_MutingInfo_r9_PR_po16_r9,
	/* Extensions may appear below */
	
} LPP_PRS_Info__prs_MutingInfo_r9_PR;

/* LPP_PRS-Info */
typedef struct LPP_PRS_Info {
	ENUMERATED_t	 prs_Bandwidth;
	long	 prs_ConfigurationIndex;
	ENUMERATED_t	 numDL_Frames;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_PRS_Info__prs_MutingInfo_r9 {
		LPP_PRS_Info__prs_MutingInfo_r9_PR present;
		union LPP_PRS_Info__prs_MutingInfo_r9_u {
			BIT_STRING_t	 po2_r9;
			BIT_STRING_t	 po4_r9;
			BIT_STRING_t	 po8_r9;
			BIT_STRING_t	 po16_r9;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *prs_MutingInfo_r9;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_PRS_Info_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_prs_Bandwidth_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_numDL_Frames_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_PRS_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_PRS_Info_H_ */
