#include <trace.idt>

interface h264dec.mpc.api.trace_init { 

/* This file specifies methods included inside provided interface named iTrace
          i.e. :          - traceInit
*/

/** @addtogroup h264decTraceInitGroup startCabac
 *  @ingroup h264decProvidedInterfaceGroup
 *  @{ 
 */
/*!
 Description : Launch HED phase
 \param[in]  TraceInfo_t        Trace structure info
 \param[in]  id                 Component id 
 *
 *
 */ 

void traceInit(	
					TraceInfo_t trace_info, 
					t_uint16 id);

 /** @} */ // end of h264decTraceInitGroup

} // interface h264dec.mpc.api.trace_init
