###############################################################################
## Copyright (C) 2010, ST-Ericsson
## 
## File name       : Makefile
## Description     : For modem-supervisor.
## 
## Author          : Philippe Begnic <philippe.begnic@stericsson.com> 
## 
###############################################################################

build:
	$(CC) $(CFLAGS) -c modem-sup.c  -o $@

clean:
	rm *.o
