/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
 
/*!
 * \brief Ultra Low Power Sleep API
 *
 * Runtime API in order to control retention mode entering.
 */
interface ee.api.sleep
{
    /*!
     * \brief Allow EE to enter in ULP retention mode.
     */
    void allowSleep();

    /*!
     * \brief Prevent EE to enter in ULP retention mode.
     */
    void preventSleep();
}
