#include <vc1dec/arm_nmf/api/nmftype.idt>

interface vc1dec.arm_nmf.api.bitstream_handshake {

void nal_handshake(
		t_handshake	mode,	/**< enable/disable transmission of input buffer */
		t_bit_buffer 	*p_b	/**< input buffer available */
		);
}
