#include <vc1dec/arm_nmf/api/nmftype.idt>
#include <common/nmf/idt/frameinfo.idt>

interface vc1dec.arm_nmf.api.picture {

void picture(t_picture_output valid, t_uint8 *p_fb, t_uint32 nFlags, t_frameinfo info);

}
