#include <vc1dec/arm_nmf/api/nmftype.idt>

interface vc1dec.arm_nmf.api.picture_to_fill {

void output_buffer(
	void *ptr,         /**< buffer to be used as decoder output */
    t_uint32 size16 	
		);

}
