#include <vc1dec/arm_nmf/api/nmftype.idt>

interface vc1dec.arm_nmf.api.set_decoder_parameter {

void set_memory_ctxt(void *mem_ctxt);
void set_picsize(t_uint16 pic_width, t_uint16 pic_height);
void set_ImmediateRelease(t_uint16 bImmediateRelease);
}
