#include <arm_codec_type.idt>
#include <frameinfo.idt>

interface vc1dec.arm_nmf.api.set_config {

void set_config(t_uint32 domainDdrId, t_uint32 domainEsramId, t_frameinfo frame_info);
 
void flush(void);   /**< +ER 341788 CHANGE START FOR */

}
