#include <vc1dec/arm_nmf/api/nmftype.idt>

interface vc1dec.arm_nmf.api.set_sequence_params {

void set_sequence_params(
	  ts_decoder_configuration	 * decoder_conf,
  	ts_sequence_parameters       * seq_params
	);

}
