/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
 
#include <ee/api/panic.idt>

/*!
 * \brief Panic API
 */
interface ee.api.panic
{
    IMPORT_SHARED void Panic(t_panic_reason reason, void *THIS, t_uint32 info);
}
