
include ../../config/config.mk

################################################################################
#                                    LBSCFG                                       #
################################################################################

LBSCFG_MOD := lbscfg

LBSCFG_DIR := srce

LBSCFG_SRC := lbscfg_log.c lbscfg_platform.c lbscfg_user.c

LBSCFG_INCL := -Iincl -I../cgps/incl -I../lsim/incl -I../halgps/incl -I../libagpsosa/incl

LBSCFG_OBJ := obj

LBSCFG_FLAGS :=

LIB := LBSCFG

include ../../config/build.mk
