#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedNmfConfig.mk

INSTALL_NMF_COMP_SRC_MMDSP=     $(OST_INC_AUTOGEN)/libeffects_mpc_libmalloc_src_memTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libupdownmix_updownmixTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libmalloc_lowlevel_src_malloc_utilsTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libvolctrlapi_volctrl_apiTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libresamplingapi_resample_apiTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libsplapi_spl_apiTraces.h \
				$(OST_INC_AUTOGEN)/libeffects_mpc_libteqapi_teq_apiTraces.h

INSTALL_NMF_COMP_SRC_MMDSP_PREFIX:=libeffects/

include $(MM_MAKEFILES_DIR)/SharedNmfRules.mk
