CC := gcc
CFLAGS   := -g -Wall -Wextra -std=c99 -pedantic-errors -pthread
INCDIRS  := -I./include
CPPFLAGS := $(INCDIRS)
LDFLAGS  :=
LDLIBS   :=

.PHONY: all clean test test_fb test_mb test_cn

all: $(OBJ)
	echo Nothing to do for selector

test_mb:
	echo No test for selector

test_fb:
	echo No test for selector

test_cn:
	echo No test for selector

clean:
	rm -f $(OBJ) $(TEST_OBJ)
