#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedNmfConfig.mk

INSTALL_NMF_COMP_SRC_MMDSP=     $(OST_INC_AUTOGEN)/mixer_nmfil_wrapper_src_processingNodeTraces.h \
				$(OST_INC_AUTOGEN)/mixer_nmfil_wrapper_src_wrapperTraces.h

INSTALL_NMF_COMP_SRC_MMDSP_PREFIX:=mixer/

include $(MM_MAKEFILES_DIR)/SharedNmfRules.mk
