/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */
#include <vfm_common.idt>

void memoryRequirements(t_uint16 mChannelId,
						ts_ddep_buffer_descriptor paramBufferDesc,
						ts_ddep_buffer_descriptor linkListBufferDesc,
						ts_ddep_buffer_descriptor debugBufferDesc,
						ts_ddep_buffer_descriptor lineBufferDesc);
void huffMemory(ts_ddep_buffer_descriptor HuffMemoryDesc);



