
include ../../config/config.mk

################################################################################
#                                   AGPSCODEC                                  #
################################################################################

AGPSCODEC_MOD := agpscodec

AGPSCODEC_DIR := srce

AGPSCODEC_SRC := agpscodec.c

AGPSCODEC_INCL := -Iincl -I../libgps/$(GNSSCHIP_VER)/incl

AGPSCODEC_OBJ := obj

AGPSCODEC_FLAGS := 

LIB := AGPSCODEC

include ../../config/build.mk
