/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#define BaseAddress 0xF0000000

#include "PictorhwReg.h"

volatile MASTER_CCI_IP_ts *p_MASTER_CCI_IP = (MASTER_CCI_IP_ts *)(BaseAddress + 0x00000000);    //MASTER_CCI

volatile USER_IF_IP_ts *p_USER_IF_IP = (USER_IF_IP_ts *)(BaseAddress + 0x00000060);    //USER_IF

volatile GPIO_IP_ts *p_GPIO_IP = (GPIO_IP_ts *)(BaseAddress + 0x00000080);    //GPIO

volatile PERIPH_CTRL_IP_ts *p_PERIPH_CTRL_IP = (PERIPH_CTRL_IP_ts *)(BaseAddress + 0x000001E0);    //PERIPH_CTRL

volatile ITM_IP_ts *p_ITM_IP = (ITM_IP_ts *)(BaseAddress + 0x00000200);    //ITM

volatile ISP_SMIARX_IP_ts *p_ISP_SMIARX_IP = (ISP_SMIARX_IP_ts *)(BaseAddress + 0x500);    //ISP_SMIARX

volatile ISP_SD_IDP_GATE_IP_ts *p_ISP_SD_IDP_GATE_IP = (ISP_SD_IDP_GATE_IP_ts *)(BaseAddress + 0x600);    //ISP_SD_IDP_GATE

volatile ISP_BAYER_STORE_SD_CLK_IP_ts *p_ISP_BAYER_STORE_SD_CLK_IP = (ISP_BAYER_STORE_SD_CLK_IP_ts *)(BaseAddress + 0x620);    //ISP_BAYER_STORE_SD_CLK

volatile ISP_LBE_IP_ts *p_ISP_LBE_IP = (ISP_LBE_IP_ts *)(BaseAddress + 0x640);    //ISP_LBE

volatile ISP_BAYER_STORE_PIX_CLK_IP_ts *p_ISP_BAYER_STORE_PIX_CLK_IP = (ISP_BAYER_STORE_PIX_CLK_IP_ts *)(BaseAddress + 0x700);    //ISP_BAYER_STORE_PIX_CLK

volatile ISP_RE_BAYER_LOAD_IP_ts *p_ISP_RE_BAYER_LOAD_IP = (ISP_RE_BAYER_LOAD_IP_ts *)(BaseAddress + 0x720);    //ISP_RE_BAYER_LOAD

volatile ISP_RSO_IP_ts *p_ISP_RSO_IP = (ISP_RSO_IP_ts *)(BaseAddress + 0x740);    //ISP_RSO

volatile ISP_FLEXTF_LINEAR_IP_ts *p_ISP_FLEXTF_LINEAR_IP = (ISP_FLEXTF_LINEAR_IP_ts *)(BaseAddress + 0x780);    //ISP_FLEXTF_LINEAR

volatile ISP_GRIDIRON_IP_ts *p_ISP_GRIDIRON_IP = (ISP_GRIDIRON_IP_ts *)(BaseAddress + 0x7A0);    //ISP_GRIDIRON

volatile ISP_CHG_IP_ts *p_ISP_CHG_IP = (ISP_CHG_IP_ts *)(BaseAddress + 0x7E0);    //ISP_CHG

volatile ISP_SNAIL_SCORPIO_IP_ts *p_ISP_SNAIL_SCORPIO_IP = (ISP_SNAIL_SCORPIO_IP_ts *)(BaseAddress + 0x800);    //ISP_SNAIL_SCORPIO

volatile ISP_SCORPIO_IP_ts *p_ISP_SCORPIO_IP = (ISP_SCORPIO_IP_ts *)(BaseAddress + 0x820);    //ISP_SCORPIO

volatile ISP_SNAIL_DUSTER_IP_ts *p_ISP_SNAIL_DUSTER_IP = (ISP_SNAIL_DUSTER_IP_ts *)(BaseAddress + 0x840);    //ISP_SNAIL_DUSTER

volatile ISP_BAYER_STORE_POST_GAIN_IP_ts *p_ISP_BAYER_STORE_POST_GAIN_IP = (ISP_BAYER_STORE_POST_GAIN_IP_ts *)(BaseAddress + 0x880);    //ISP_BAYER_STORE_POST_GAIN

volatile ISP_ITPOINT_RE_IN_IP_ts *p_ISP_ITPOINT_RE_IN_IP = (ISP_ITPOINT_RE_IN_IP_ts *)(BaseAddress + 0x8A0);    //ISP_ITPOINT_RE_IN

volatile ISP_ITPOINT_POST_GAIN_IP_ts *p_ISP_ITPOINT_POST_GAIN_IP = (ISP_ITPOINT_POST_GAIN_IP_ts *)(BaseAddress + 0x8C0);    //ISP_ITPOINT_POST_GAIN

volatile ISP_ITPOINT_RE_OUT_STORE_IP_ts *p_ISP_ITPOINT_RE_OUT_STORE_IP = (ISP_ITPOINT_RE_OUT_STORE_IP_ts *)(BaseAddress + 0x8E0);    //ISP_ITPOINT_RE_OUT_STORE

volatile ISP_DUSTER_IP_ts *p_ISP_DUSTER_IP = (ISP_DUSTER_IP_ts *)(BaseAddress + 0x900);    //ISP_DUSTER

volatile ISP_SNAIL_BINNING_IP_ts *p_ISP_SNAIL_BINNING_IP = (ISP_SNAIL_BINNING_IP_ts *)(BaseAddress + 0xA00);    //ISP_SNAIL_BINNING

volatile ISP_BINNING_REPAIR_IP_ts *p_ISP_BINNING_REPAIR_IP = (ISP_BINNING_REPAIR_IP_ts *)(BaseAddress + 0xA20);    //ISP_BINNING_REPAIR

volatile ISP_CROP_BAYER_IP_ts *p_ISP_CROP_BAYER_IP = (ISP_CROP_BAYER_IP_ts *)(BaseAddress + 0xA40);    //ISP_CROP_BAYER

volatile ISP_BAYER_STORE_RE_OUT_IP_ts *p_ISP_BAYER_STORE_RE_OUT_IP = (ISP_BAYER_STORE_RE_OUT_IP_ts *)(BaseAddress + 0xA80);    //ISP_BAYER_STORE_RE_OUT

volatile ISP_SNAIL_BABYLON_IP_ts *p_ISP_SNAIL_BABYLON_IP = (ISP_SNAIL_BABYLON_IP_ts *)(BaseAddress + 0xAC0);    //ISP_SNAIL_BABYLON

volatile ISP_MOZART_IP_ts *p_ISP_MOZART_IP = (ISP_MOZART_IP_ts *)(BaseAddress + 0xB00);    //ISP_Mozart

volatile ISP_CE0_NORCOS_IP_ts *p_ISP_CE0_NORCOS_IP = (ISP_CE0_NORCOS_IP_ts *)(BaseAddress + 0x3A40);    //ISP_Norcos

volatile ISP_CE1_NORCOS_IP_ts *p_ISP_CE1_NORCOS_IP = (ISP_CE1_NORCOS_IP_ts *)(BaseAddress + 0x3C40 );    //ISP_Norcos+ 0x200

volatile ISP_BABYLON_IP_ts *p_ISP_BABYLON_IP = (ISP_BABYLON_IP_ts *)(BaseAddress + 0xAE0);    //ISP_BABYLON

volatile ISP_DMCE_BAYER_LOAD_IP_ts *p_ISP_DMCE_BAYER_LOAD_IP = (ISP_DMCE_BAYER_LOAD_IP_ts *)(BaseAddress + 0xB40);    //ISP_DMCE_BAYER_LOAD

volatile ISP_DMCE_RGB_LOAD_IP_ts *p_ISP_DMCE_RGB_LOAD_IP = (ISP_DMCE_RGB_LOAD_IP_ts *)(BaseAddress + 0xB60);    //ISP_DMCE_RGB_LOAD

volatile ISP_DMCE_RGB_STORE_IP_ts *p_ISP_DMCE_RGB_STORE_IP = (ISP_DMCE_RGB_STORE_IP_ts *)(BaseAddress + 0xB80);    //ISP_DMCE_RGB_STORE

volatile ISP_CHANNELMERGE_IP_ts *p_ISP_CHANNELMERGE_IP = (ISP_CHANNELMERGE_IP_ts *)(BaseAddress + 0xBA0);    //ISP_CHANNELMERGE

volatile ISP_DMCE_MUX_DEMOSAIC_IP_ts *p_ISP_DMCE_MUX_DEMOSAIC_IP = (ISP_DMCE_MUX_DEMOSAIC_IP_ts *)(BaseAddress + 0xBC0);    //ISP_DMCE_MUX_DEMOSAIC

volatile ISP_LINE_BURSTY_ELIM_IP_ts *p_ISP_LINE_BURSTY_ELIM_IP = (ISP_LINE_BURSTY_ELIM_IP_ts *)(BaseAddress + 0xBE0);    //ISP_LINE_BURSTY_ELIM

volatile ISP_CE0_IDP_GATE_IP_ts *p_ISP_CE0_IDP_GATE_IP = (ISP_CE0_IDP_GATE_IP_ts *)(BaseAddress + 0xC00);    //ISP_CE0_IDP_GATE

volatile ISP_CE0_CROP_IP_ts *p_ISP_CE0_CROP_IP = (ISP_CE0_CROP_IP_ts *)(BaseAddress + 0xC20);    //ISP_CE0_CROP

volatile ISP_CE0_RADIAL_ADSOC_PK_IP_ts *p_ISP_CE0_RADIAL_ADSOC_PK_IP = (ISP_CE0_RADIAL_ADSOC_PK_IP_ts *)(BaseAddress + 0xC60);    //ISP_CE0_RADIAL_ADSOC_PK

volatile ISP_CE0_RADIAL_ADSOC_RP_IP_ts *p_ISP_CE0_RADIAL_ADSOC_RP_IP = (ISP_CE0_RADIAL_ADSOC_RP_IP_ts *)(BaseAddress + 0xC78);    //ISP_CE0_RADIAL_ADSOC_RP

volatile ISP_CE0_MUX_GPS_IP_ts *p_ISP_CE0_MUX_GPS_IP = (ISP_CE0_MUX_GPS_IP_ts *)(BaseAddress + 0xCA0);    //ISP_CE0_MUX_GPS

volatile ISP_CE0_MUX_SHARP_IP_ts *p_ISP_CE0_MUX_SHARP_IP = (ISP_CE0_MUX_SHARP_IP_ts *)(BaseAddress + 0xCC0);    //ISP_CE0_MUX_SHARP

volatile ISP_CE0_MUX_UNSHARP_IP_ts *p_ISP_CE0_MUX_UNSHARP_IP = (ISP_CE0_MUX_UNSHARP_IP_ts *)(BaseAddress + 0xCE0);    //ISP_CE0_MUX_UNSHARP

volatile ISP_CE0_FLEXTF_SHARP_IP_ts *p_ISP_CE0_FLEXTF_SHARP_IP = (ISP_CE0_FLEXTF_SHARP_IP_ts *)(BaseAddress + 0xD00);    //ISP_CE0_FLEXTF_SHARP

volatile ISP_CE0_FLEXTF_UNSHARP_IP_ts *p_ISP_CE0_FLEXTF_UNSHARP_IP = (ISP_CE0_FLEXTF_UNSHARP_IP_ts *)(BaseAddress + 0xD20);    //ISP_CE0_FLEXTF_UNSHARP

volatile ISP_CE0_MUX_MATRIX_ADSOC_IP_ts *p_ISP_CE0_MUX_MATRIX_ADSOC_IP = (ISP_CE0_MUX_MATRIX_ADSOC_IP_ts *)(BaseAddress + 0xD40);    //ISP_CE0_MUX_MATRIX_ADSOC

volatile ISP_CE0_SNAIL0_ADSOC_IP_ts *p_ISP_CE0_SNAIL0_ADSOC_IP = (ISP_CE0_SNAIL0_ADSOC_IP_ts *)(BaseAddress + 0xD60);    //ISP_CE0_SNAIL0_ADSOC

volatile ISP_CE0_SNAIL1_ADSOC_IP_ts *p_ISP_CE0_SNAIL1_ADSOC_IP = (ISP_CE0_SNAIL1_ADSOC_IP_ts *)(BaseAddress + 0xD80);    //ISP_CE0_SNAIL1_ADSOC

volatile ISP_CE0_MATRIX_IP_ts *p_ISP_CE0_MATRIX_IP = (ISP_CE0_MATRIX_IP_ts *)(BaseAddress + 0xDA0);    //ISP_CE0_MATRIX

volatile ISP_CE0_PIXDELAY_0_IP_ts *p_ISP_CE0_PIXDELAY_0_IP = (ISP_CE0_PIXDELAY_0_IP_ts *)(BaseAddress + 0xDE0);    //ISP_CE0_PIXDELAY_0

volatile ISP_CE0_PIXDELAY_1_IP_ts *p_ISP_CE0_PIXDELAY_1_IP = (ISP_CE0_PIXDELAY_1_IP_ts *)(BaseAddress + 0xE00);    //ISP_CE0_PIXDELAY_1

volatile ISP_CE0_SPECIALFX_IP_ts *p_ISP_CE0_SPECIALFX_IP = (ISP_CE0_SPECIALFX_IP_ts *)(BaseAddress + 0xE20);    //ISP_CE0_SPECIALFX

volatile ISP_CE0_DITHER_IP_ts *p_ISP_CE0_DITHER_IP = (ISP_CE0_DITHER_IP_ts *)(BaseAddress + 0xE40);    //ISP_CE0_DITHER

volatile ISP_CE0_GPSSCALER_IP_ts *p_ISP_CE0_GPSSCALER_IP = (ISP_CE0_GPSSCALER_IP_ts *)(BaseAddress + 0xF00);    //ISP_CE0_GPSSCALER

volatile ISP_CE0_CODER_IP_ts *p_ISP_CE0_CODER_IP = (ISP_CE0_CODER_IP_ts *)(BaseAddress + 0x1000);    //ISP_CE0_CODER

volatile ISP_OPF0_IP_ts *p_ISP_OPF0_IP = (ISP_OPF0_IP_ts *)(BaseAddress + 0x1060);    //ISP_OPF0

volatile ISP_CE1_IDP_GATE_IP_ts *p_ISP_CE1_IDP_GATE_IP = (ISP_CE1_IDP_GATE_IP_ts *)(BaseAddress + 0x1100);    //ISP_CE1_IDP_GATE

volatile ISP_CE1_CROP_IP_ts *p_ISP_CE1_CROP_IP = (ISP_CE1_CROP_IP_ts *)(BaseAddress + 0x1120);    //ISP_CE1_CROP

volatile ISP_CE1_RADIAL_ADSOC_PK_IP_ts *p_ISP_CE1_RADIAL_ADSOC_PK_IP = (ISP_CE1_RADIAL_ADSOC_PK_IP_ts *)(BaseAddress + 0x1160);    //ISP_CE1_RADIAL_ADSOC_PK

volatile ISP_CE1_RADIAL_ADSOC_RP_IP_ts *p_ISP_CE1_RADIAL_ADSOC_RP_IP = (ISP_CE1_RADIAL_ADSOC_RP_IP_ts *)(BaseAddress + 0x1178);    //ISP_CE1_RADIAL_ADSOC_RP

volatile ISP_CE1_MUX_GPS_IP_ts *p_ISP_CE1_MUX_GPS_IP = (ISP_CE1_MUX_GPS_IP_ts *)(BaseAddress + 0x11A0);    //ISP_CE1_MUX_GPS

volatile ISP_CE1_MUX_SHARP_IP_ts *p_ISP_CE1_MUX_SHARP_IP = (ISP_CE1_MUX_SHARP_IP_ts *)(BaseAddress + 0x11C0);    //ISP_CE1_MUX_SHARP

volatile ISP_CE1_MUX_UNSHARP_IP_ts *p_ISP_CE1_MUX_UNSHARP_IP = (ISP_CE1_MUX_UNSHARP_IP_ts *)(BaseAddress + 0x11E0);    //ISP_CE1_MUX_UNSHARP

volatile ISP_CE1_FLEXTF_SHARP_IP_ts *p_ISP_CE1_FLEXTF_SHARP_IP = (ISP_CE1_FLEXTF_SHARP_IP_ts *)(BaseAddress + 0x1200);    //ISP_CE1_FLEXTF_SHARP

volatile ISP_CE1_FLEXTF_UNSHARP_IP_ts *p_ISP_CE1_FLEXTF_UNSHARP_IP = (ISP_CE1_FLEXTF_UNSHARP_IP_ts *)(BaseAddress + 0x1220);    //ISP_CE1_FLEXTF_UNSHARP

volatile ISP_CE1_MUX_MATRIX_ADSOC_IP_ts *p_ISP_CE1_MUX_MATRIX_ADSOC_IP = (ISP_CE1_MUX_MATRIX_ADSOC_IP_ts *)(BaseAddress + 0x1240);    //ISP_CE1_MUX_MATRIX_ADSOC

volatile ISP_CE1_SNAIL0_ADSOC_IP_ts *p_ISP_CE1_SNAIL0_ADSOC_IP = (ISP_CE1_SNAIL0_ADSOC_IP_ts *)(BaseAddress + 0x1260);    //ISP_CE1_SNAIL0_ADSOC

volatile ISP_CE1_SNAIL1_ADSOC_IP_ts *p_ISP_CE1_SNAIL1_ADSOC_IP = (ISP_CE1_SNAIL1_ADSOC_IP_ts *)(BaseAddress + 0x1280);    //ISP_CE1_SNAIL1_ADSOC

volatile ISP_CE1_MATRIX_IP_ts *p_ISP_CE1_MATRIX_IP = (ISP_CE1_MATRIX_IP_ts *)(BaseAddress + 0x12A0);    //ISP_CE1_MATRIX

volatile ISP_CE1_PIXDELAY_0_IP_ts *p_ISP_CE1_PIXDELAY_0_IP = (ISP_CE1_PIXDELAY_0_IP_ts *)(BaseAddress + 0x12E0);    //ISP_CE1_PIXDELAY_0

volatile ISP_CE1_PIXDELAY_1_IP_ts *p_ISP_CE1_PIXDELAY_1_IP = (ISP_CE1_PIXDELAY_1_IP_ts *)(BaseAddress + 0x1300);    //ISP_CE1_PIXDELAY_1

volatile ISP_CE1_SPECIALFX_IP_ts *p_ISP_CE1_SPECIALFX_IP = (ISP_CE1_SPECIALFX_IP_ts *)(BaseAddress + 0x1320);    //ISP_CE1_SPECIALFX

volatile ISP_CE1_DITHER_IP_ts *p_ISP_CE1_DITHER_IP = (ISP_CE1_DITHER_IP_ts *)(BaseAddress + 0x1340);    //ISP_CE1_DITHER

volatile ISP_CE1_GPSSCALER_IP_ts *p_ISP_CE1_GPSSCALER_IP = (ISP_CE1_GPSSCALER_IP_ts *)(BaseAddress + 0x1400);    //ISP_CE1_GPSSCALER

volatile ISP_CE1_CODER_IP_ts *p_ISP_CE1_CODER_IP = (ISP_CE1_CODER_IP_ts *)(BaseAddress + 0x1500);    //ISP_CE1_CODER

volatile ISP_OPF1_IP_ts *p_ISP_OPF1_IP = (ISP_OPF1_IP_ts *)(BaseAddress + 0x1560);    //ISP_OPF1

volatile ISP_STATS_ACCWZ_IP_ts *p_ISP_STATS_ACCWZ_IP = (ISP_STATS_ACCWZ_IP_ts *)(BaseAddress + 0x1600);    //ISP_STATS_ACCWZ

volatile ISP_STATS_ACC_8x6_IP_ts *p_ISP_STATS_ACC_8x6_IP = (ISP_STATS_ACC_8x6_IP_ts *)(BaseAddress + 0x1700);    //ISP_STATS_ACC_8x6

volatile ISP_STATS_MUX_MWWB_IP_ts *p_ISP_STATS_MUX_MWWB_IP = (ISP_STATS_MUX_MWWB_IP_ts *)(BaseAddress + 0x1800);    //ISP_STATS_MUX_MWWB

volatile ISP_STATS_MPSS_IP_ts *p_ISP_STATS_MPSS_IP = (ISP_STATS_MPSS_IP_ts *)(BaseAddress + 0x1820);    //ISP_STATS_MPSS

volatile ISP_STATS_SNAIL_MWWB_IP_ts *p_ISP_STATS_SNAIL_MWWB_IP = (ISP_STATS_SNAIL_MWWB_IP_ts *)(BaseAddress + 0x1840);    //ISP_STATS_SNAIL_MWWB

volatile ISP_STATS_MWWB_IP_ts *p_ISP_STATS_MWWB_IP = (ISP_STATS_MWWB_IP_ts *)(BaseAddress + 0x1860);    //ISP_STATS_MWWB

volatile ISP_STATS_MUX_HIST_IP_ts *p_ISP_STATS_MUX_HIST_IP = (ISP_STATS_MUX_HIST_IP_ts *)(BaseAddress + 0x18C0);    //ISP_STATS_MUX_HIST

volatile ISP_STATS_HIST_IP_ts *p_ISP_STATS_HIST_IP = (ISP_STATS_HIST_IP_ts *)(BaseAddress + 0x1900);    //ISP_STATS_HIST

volatile ISP_STATS_MUX_GLACE_IP_ts *p_ISP_STATS_MUX_GLACE_IP = (ISP_STATS_MUX_GLACE_IP_ts *)(BaseAddress + 0x1960);    //ISP_STATS_MUX_GLACE

volatile ISP_STATS_GLACE_IP_ts *p_ISP_STATS_GLACE_IP = (ISP_STATS_GLACE_IP_ts *)(BaseAddress + 0x1A00);    //ISP_STATS_GLACE

volatile ISP_STATS_MPSS_GLACE_IP_ts *p_ISP_STATS_MPSS_GLACE_IP = (ISP_STATS_MPSS_GLACE_IP_ts *)(BaseAddress + 0x1AC0);    //ISP_STATS_MPSS_GLACE

volatile ISP_STATS_AF_IP_ts *p_ISP_STATS_AF_IP = (ISP_STATS_AF_IP_ts *)(BaseAddress + 0x1B00);    //ISP_STATS_AF

volatile ISP_STATS_SKINTONE_IP_ts *p_ISP_STATS_SKINTONE_IP = (ISP_STATS_SKINTONE_IP_ts *)(BaseAddress + 0x1D00);    //ISP_STATS_SKINTONE

volatile ISP_ITPOINT_DMCE_IN_IP_ts *p_ISP_ITPOINT_DMCE_IN_IP = (ISP_ITPOINT_DMCE_IN_IP_ts *)(BaseAddress + 0x1E40);    //ISP_ITPOINT_DMCE_IN

volatile ISP_ITPOINT_DMCE_OUT_IP_ts *p_ISP_ITPOINT_DMCE_OUT_IP = (ISP_ITPOINT_DMCE_OUT_IP_ts *)(BaseAddress + 0x1E60);    //ISP_ITPOINT_DMCE_OUT

volatile ISP_ITPOINT_RGB_STORE_IP_ts *p_ISP_ITPOINT_RGB_STORE_IP = (ISP_ITPOINT_RGB_STORE_IP_ts *)(BaseAddress + 0x1E80);    //ISP_ITPOINT_RGB_STORE

volatile ISP_SMIARX3D_IP_ts *p_ISP_SMIARX3D_IP = (ISP_SMIARX3D_IP_ts *)(BaseAddress + 0x3800);    //ISP_SMIARX3D

volatile ISP_CE0_RGB2YUV_MATRIX_IP_ts *p_ISP_CE0_RGB2YUV_MATRIX_IP = (ISP_CE0_RGB2YUV_MATRIX_IP_ts *)(BaseAddress + 0x3A00);    //ISP_CE0_RGB2YUV_MATRIX

volatile ISP_CE0_YUV2RGB_MATRIX_IP_ts *p_ISP_CE0_YUV2RGB_MATRIX_IP = (ISP_CE0_YUV2RGB_MATRIX_IP_ts *)(BaseAddress + 0x3AC0);    //ISP_CE0_YUV2RGB_MATRIX

volatile ISP_CE0_MUX_0_UNPEAKING_IP_ts *p_ISP_CE0_MUX_0_UNPEAKING_IP = (ISP_CE0_MUX_0_UNPEAKING_IP_ts *)(BaseAddress + 0x3B00);    //ISP_CE0_MUX_0_UNPEAKING

volatile ISP_CE0_MUX_1_UNPEAKING_IP_ts *p_ISP_CE0_MUX_1_UNPEAKING_IP = (ISP_CE0_MUX_1_UNPEAKING_IP_ts *)(BaseAddress + 0x3B20);    //ISP_CE0_MUX_1_UNPEAKING

volatile ISP_CE0_MUX_0_PEAKING_IP_ts *p_ISP_CE0_MUX_0_PEAKING_IP = (ISP_CE0_MUX_0_PEAKING_IP_ts *)(BaseAddress + 0x3B40);    //ISP_CE0_MUX_0_PEAKING

volatile ISP_CE0_MUX_1_PEAKING_IP_ts *p_ISP_CE0_MUX_1_PEAKING_IP = (ISP_CE0_MUX_1_PEAKING_IP_ts *)(BaseAddress + 0x3B60);    //ISP_CE0_MUX_1_PEAKING

volatile ISP_CE1_RGB2YUV_MATRIX_IP_ts *p_ISP_CE1_RGB2YUV_MATRIX_IP = (ISP_CE1_RGB2YUV_MATRIX_IP_ts *)(BaseAddress + 0x3C00);    //ISP_CE1_RGB2YUV_MATRIX

volatile ISP_CE1_YUV2RGB_MATRIX_IP_ts *p_ISP_CE1_YUV2RGB_MATRIX_IP = (ISP_CE1_YUV2RGB_MATRIX_IP_ts *)(BaseAddress + 0x3CC0);    //ISP_CE1_YUV2RGB_MATRIX

volatile ISP_CE1_MUX_0_UNPEAKING_IP_ts *p_ISP_CE1_MUX_0_UNPEAKING_IP = (ISP_CE1_MUX_0_UNPEAKING_IP_ts *)(BaseAddress + 0x3D00);    //ISP_CE1_MUX_0_UNPEAKING

volatile ISP_CE1_MUX_1_UNPEAKING_IP_ts *p_ISP_CE1_MUX_1_UNPEAKING_IP = (ISP_CE1_MUX_1_UNPEAKING_IP_ts *)(BaseAddress + 0x3D20);    //ISP_CE1_MUX_1_UNPEAKING

volatile ISP_CE1_MUX_0_PEAKING_IP_ts *p_ISP_CE1_MUX_0_PEAKING_IP = (ISP_CE1_MUX_0_PEAKING_IP_ts *)(BaseAddress + 0x3D40);    //ISP_CE1_MUX_0_PEAKING

volatile ISP_CE1_MUX_1_PEAKING_IP_ts *p_ISP_CE1_MUX_1_PEAKING_IP = (ISP_CE1_MUX_1_PEAKING_IP_ts *)(BaseAddress + 0x3D60);    //ISP_CE1_MUX_1_PEAKING

volatile GRIDIRON_MEM_IP_ts *p_GRIDIRON_MEM_IP = (GRIDIRON_MEM_IP_ts *)(BaseAddress + 0x00004000);    //GRIDIRON_MEM

volatile GLACE_MEM_IP_ts *p_GLACE_MEM_IP = (GLACE_MEM_IP_ts *)(BaseAddress + 0x00024400);    //GLACE_MEM

volatile HIST_MEM_IP_ts *p_HIST_MEM_IP = (HIST_MEM_IP_ts *)(BaseAddress + 0x0002C800);    //HIST_MEM

volatile LINEAR_MEM_IP_ts *p_LINEAR_MEM_IP = (LINEAR_MEM_IP_ts *)(BaseAddress + 0x0002DC00);    //LINEAR_MEM

volatile CE0_SHARP_MEM_IP_ts *p_CE0_SHARP_MEM_IP = (CE0_SHARP_MEM_IP_ts *)(BaseAddress + 0x0002F000);    //CE0_SHARP_MEM

volatile CE0_UNSHARP_MEM_IP_ts *p_CE0_UNSHARP_MEM_IP = (CE0_UNSHARP_MEM_IP_ts *)(BaseAddress + 0x0002FC00);    //CE0_UNSHARP_MEM

volatile CE1_SHARP_MEM_IP_ts *p_CE1_SHARP_MEM_IP = (CE1_SHARP_MEM_IP_ts *)(BaseAddress + 0x00030800);    //CE1_SHARP_MEM

volatile CE1_UNSHARP_MEM_IP_ts *p_CE1_UNSHARP_MEM_IP = (CE1_UNSHARP_MEM_IP_ts *)(BaseAddress + 0x00031400);    //CE1_UNSHARP_MEM

volatile DUSTER_MEM_IP_ts *p_DUSTER_MEM_IP = (DUSTER_MEM_IP_ts *)(BaseAddress + 0x00032000);    //DUSTER_MEM

volatile XP70_L2_MEM_IP_ts *p_XP70_L2_MEM_IP = (XP70_L2_MEM_IP_ts *)(BaseAddress + 0x00040000);    //XP70_L2_MEM

volatile XP70_TCDM_MEM_IP_ts *p_XP70_TCDM_MEM_IP = (XP70_TCDM_MEM_IP_ts *)(BaseAddress + 0x00060000);    //XP70_TCDM_MEM

