# Copyright (c) ST-Ericsson AB 2009-2010
#
# Author: Manish Sharma <manish.sharma@stericsson.com>
#

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libmalsms
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_SRC_FILES := pre_built/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)
include $(BUILD_PREBUILT)
