#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedConfig.mk

INSTALL_NMF_COMP_SRC_MMDSP = osttrace.itf
INSTALL_NMF_COMP_SRC_MMDSP_PREFIX = osttrace/api/

todo: nmfsrc

include $(MM_MAKEFILES_DIR)/SharedRules.mk
