/*                               -*- Mode: C -*-
 * Copyright (C) 2010, ST-Ericsson
 *
 * File name       : tuicc.h
 * Description     : test executable header file.
 *
 * Author          : Annwesh Mukherjee <annwesh.xa.mukherjee@stericsson.com>
 *
 */

#ifndef TUICC_H
#define TUICC_H

typedef enum {
    TUICC_CT_STE_SIM_CAUSE_HANGUP,
    TUICC_CT_STE_SIM_CAUSE_NOOP,
    TUICC_CT_STE_SIM_CAUSE_CONNECT,
    TUICC_CT_STE_SIM_CAUSE_DISCONNECT,
    TUICC_CT_STE_SIM_CAUSE_SHUTDOWN,
    TUICC_CT_STE_SIM_CAUSE_PING,
    TUICC_CT_STE_SIM_SET_SIM_DEBUG_LEVEL,
    TUICC_CT_STE_SIM_SET_MODEM_DEBUG_LEVEL,
    TUICC_CT_STE_UICC_CAUSE_NOOP,
    TUICC_CT_STE_UICC_CAUSE_REGISTER,
    TUICC_CT_STE_UICC_CAUSE_DEREGISTER,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_VERIFY,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_NEEDED,
    TUICC_CT_STE_UICC_CAUSE_REQ_READ_SIM_FILE_RECORD,
    TUICC_CT_STE_UICC_CAUSE_REQ_UPDATE_SIM_FILE_RECORD,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_CHANGE,
    TUICC_CT_STE_UICC_CAUSE_REQ_READ_SIM_FILE_BINARY,
    TUICC_CT_STE_UICC_CAUSE_REQ_UPDATE_SIM_FILE_BINARY,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_GET_FORMAT,
    TUICC_CT_STE_UICC_CAUSE_REQ_GET_FILE_INFORMATION,
    TUICC_CT_STE_UICC_CAUSE_REQ_GET_FILE_INFORMATION_FAIL,
    TUICC_CT_STE_UICC_CAUSE_REQ_GET_SIM_STATE,
    TUICC_CT_STE_UICC_CAUSE_SIM_STATE_CHANGED,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_DISABLE,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_ENABLE,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_INFO,
    TUICC_CT_STE_UICC_CAUSE_REQ_PIN_UNBLOCK,
    TUICC_CT_STE_UICC_CAUSE_REQ_READ_SPECIFIC_CHAR_FILE,
    TUICC_CT_STE_UICC_CAUSE_REQ_APP_INFO,
    TUICC_CT_STE_UICC_CAUSE_NOT_READY,
    TUICC_CT_STE_SIM_CAUSE_STARTUP,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_IMSI,
    TUICC_CT_STE_UICC_CAUSE_REQ_UPDATE_SERVICE_TABLE,
    TUICC_CT_STE_UICC_CAUSE_REQ_GET_SERVICE_TABLE,
    TUICC_CT_STE_UICC_CAUSE_SIM_STATUS,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_ICON,
    TUICC_CT_STE_UICC_CAUSE_REQ_SUBSCRIBER_NUMBER,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_PLMN,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_PLMN_SEL,
    TUICC_CT_STE_UICC_CAUSE_REQ_APP_STATUS,
    TUICC_CT_STE_UICC_CAUSE_REQ_CARD_STATUS,
    TUICC_CT_STE_UICC_CAUSE_REQ_SMSC_GET_ACTIVE,
    TUICC_CT_STE_UICC_CAUSE_REQ_SMSC_SET_ACTIVE,
    TUICC_CT_STE_UICC_CAUSE_REQ_SMSC_GET_RECORD_MAX,
    TUICC_CT_STE_UICC_CAUSE_REQ_SMSC_RESTORE_FROM_RECORD,
    TUICC_CT_STE_UICC_CAUSE_REQ_SMSC_SAVE_TO_RECORD,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_CHANNEL_SEND,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_CHANNEL_OPEN,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_CHANNEL_CLOSE,
    TUICC_CT_STE_UICC_CAUSE_REQ_GET_SERVICE_AVAILABILITY,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_FDN,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_ECC,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_FILE_READ_GENERIC,
    TUICC_CT_STE_UICC_CAUSE_REQ_RESET,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_POWER_ON,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_POWER_OFF,
    TUICC_CT_STE_UICC_CAUSE_REQ_SIM_READ_PREFERRED_RAT_SETTING,
    TUICC_CT_STE_UICC_CAUSE_REQ_SET_APP_TYPE_SIM,
    TUICC_CT_NOT_USED
} tuicc_ct_ste_uicc_cause_t;

#endif
