/*
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#ifndef _TUNING_IQSET_H_
#define _TUNING_IQSET_H_

/** minor version of the parser.
This value should be incremented each time new IQSET are added both in the #e_iqset_id and in the xml files*/
#define IQSET_ENTRIES_VERSION 0x2

/** list of all supported IQSETs */
typedef enum
{
    IQSET_UNKNOWN = -1,

    IQSET_OPMODE_SETUP,
    IQSET_PICTURE_SETTINGS_MAPPING,
    IQSET_NOISE_MODEL_SETUP,

    IQSET_WHITEBALANCE_OFF,
    IQSET_WHITEBALANCE_AUTO,
    IQSET_WHITEBALANCE_DAYLIGHT,
    IQSET_WHITEBALANCE_TUNGSTEN,
    IQSET_WHITEBALANCE_SHADE,
    IQSET_WHITEBALANCE_FLASH,
    IQSET_WHITEBALANCE_CLOUDY,
    IQSET_WHITEBALANCE_HORIZON,
    IQSET_WHITEBALANCE_FLUORESCENT,
    IQSET_WHITEBALANCE_INCANDESCENT,

    IQSET_EXPOSURECONTROL_OFF,
    IQSET_EXPOSURECONTROL_AUTO,
    IQSET_EXPOSURECONTROL_NIGHT,
    IQSET_EXPOSURECONTROL_BACKLIGHT,
    IQSET_EXPOSURECONTROL_SPOTLIGHT,
    IQSET_EXPOSURECONTROL_SPORTS,
    IQSET_EXPOSURECONTROL_SNOW,
    IQSET_EXPOSURECONTROL_BEACH,
    IQSET_EXPOSURECONTROL_LARGEAPERTURE,
    IQSET_EXPOSURECONTROL_SMALLAPERTURE,
    IQSET_EXPOSURECONTROL_CENTER,
    IQSET_EXPOSURECONTROL_VERYLONG,

    IQSET_IMAGEFILTER_NONE,
    IQSET_IMAGEFILTER_NOISE,
    IQSET_IMAGEFILTER_EMBOSS,
    IQSET_IMAGEFILTER_NEGATIVE,
    IQSET_IMAGEFILTER_SKETCH,
    IQSET_IMAGEFILTER_OILPAINT,
    IQSET_IMAGEFILTER_HATCH,
    IQSET_IMAGEFILTER_GPEN,
    IQSET_IMAGEFILTER_ANTIALIAS,
    IQSET_IMAGEFILTER_DERING,
    IQSET_IMAGEFILTER_SOLARIZE,

    IQSET_SYMBIAN_SCENEAUTO,
    IQSET_SYMBIAN_SCENEPORTRAIT,
    IQSET_SYMBIAN_SCENELANDSCAPE,
    IQSET_SYMBIAN_SCENENIGHT,
    IQSET_SYMBIAN_SCENENIGHTPORTRAIT,
    IQSET_SYMBIAN_SCENESPORT,
    IQSET_SYMBIAN_SCENEMACRO,
    IQSET_STE_SCENEDOCUMENT,
    IQSET_STE_SCENEBEACH,
    IQSET_STE_SCENESNOW,
    IQSET_STE_SCENEPARTY,
    IQSET_STE_SCENEAQUA,
    IQSET_STE_SCENECANDLELIGHT,
    IQSET_STE_SCENEBACKLIGHT,
    IQSET_STE_SCENESUNSET,

    IQSET_FLICKERREJECTION_OFF,
    IQSET_FLICKERREJECTION_50,
    IQSET_FLICKERREJECTION_60,

    IQSET_EXPOSUREVALUE_COMPENSATION,
    IQSET_AECMETERING_AVERAGE,
    IQSET_AECMETERING_SPOT,
    IQSET_AECMETERING_MATRIX,
    IQSET_AECMETERING_CENTERWEIGHTED,
    IQSET_AECMETERING_BEACH_SNOW,
    IQSET_AECMETERING_PORTRAIT,
    IQSET_AECMETERING_LANDSCAPE,
    IQSET_SHUTTERSPEED_TIME,
    IQSET_ISO_AUTO,
    IQSET_ISO_100,
    IQSET_ISO_200,
    IQSET_ISO_400,
    IQSET_ISO_800,
    IQSET_ISO_1600,
    IQSET_ISO_3200,

    IQSET_IMAGEFILTER_SEPIA,
    IQSET_IMAGEFILTER_GRAYSCALE,
    IQSET_IMAGEFILTER_NATURAL,
    IQSET_IMAGEFILTER_VIVID,
    IQSET_IMAGEFILTER_WATERCOLOR,
    IQSET_IMAGEFILTER_PASTEL,
    IQSET_IMAGEFILTER_GRAYSCALENEGATIVE,
    IQSET_IMAGEFILTER_FILM,
    IQSET_IMAGEFILTER_SNOW,
    IQSET_IMAGEFILTER_BEACH,
    IQSET_IMAGEFILTER_POSTERIZE,

    IQSET_FOCUS_ON,
    IQSET_FOCUS_AUTO,
    IQSET_FOCUSRANGE_AUTO,
    IQSET_FOCUSRANGE_NORMAL,
    IQSET_FOCUSRANGE_SUPERMACRO,
    IQSET_FOCUSRANGE_MACRO,
    IQSET_FOCUSRANGE_HYPERFOCAL,
    IQSET_FOCUSRANGE_INFINITY,
    IQSET_FOCUSREGION_AUTO,
    IQSET_FOCUSREGION_MANUAL,
    IQSET_FOCUSREGION_CENTER,
    IQSET_YUVPRIMARIES_FULL,
    IQSET_YUVPRIMARIES_BT601,
    IQSET_YUVPRIMARIES_BT709,

    IQSET_SOFTWARE_CHROMA_NOISE_REDUCTION,
    IQSET_SHAKE_DETECTION,
    IQSET_FLASH,
    IQSET_ANALOG_GAIN_MODEL,
    IQSET_SOFTWARE_SCENE_DETECTOR,
    IQSET_EXPOSURE_TIME_INIT_MODEL,

    IQSET_COUNT // Always keep as last
} e_iqset_id;

class CTuningIQSet
{
    public:
        static e_iqset_id  FindIQSetIdFromName(const char* aName);
        static const char* FindIQSetNameFromId(const e_iqset_id);
        inline static bool IsValidIQSetId(const e_iqset_id aIqSetId) {return aIqSetId>=0 && aIqSetId<IQSET_COUNT;}
};

#endif /*_TUNING_IQSET_H_*/
