#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedNmfConfig.mk

INSTALL_NMF_COMP_SRC_MMDSP=     $(OST_INC_AUTOGEN)/afm_nmf_mpc_bindings_pcmadapter_src_pcmadapterTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_decoders_streamed_wrapper_src_wrapperTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_bindings_shmpcm_shmin_src_shminTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_misc_controller_src_controllerTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_bindings_shmpcm_shmout_src_shmoutTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_pcmprocessings_wrapper_src_wrapperTraces.h \
				$(OST_INC_AUTOGEN)/afm_nmf_mpc_bindings_shm_shmin_src_shminTraces.h \
                                $(OST_INC_AUTOGEN)/afm_nmf_mpc_misc_pcmdump_src_pcmdumpTraces.h

INSTALL_NMF_COMP_SRC_MMDSP_PREFIX:=afm/

include $(MM_MAKEFILES_DIR)/SharedNmfRules.mk
