/*
 * SUPL_ULP_ThirdPartyID.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#ifndef    _SUPL_ULP_ThirdPartyID_H_
#define    _SUPL_ULP_ThirdPartyID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ThirdPartyID_PR {
    ThirdPartyID_PR_NOTHING,    /* No components present */
    ThirdPartyID_PR_logicalName,
    ThirdPartyID_PR_msisdn,
    ThirdPartyID_PR_emailaddr,
    ThirdPartyID_PR_sip_uri,
    ThirdPartyID_PR_ims_public_identity,
    ThirdPartyID_PR_min,
    ThirdPartyID_PR_mdn,
    ThirdPartyID_PR_uri,
    /* Extensions may appear below */
    
} ThirdPartyID_PR;

/* SUPL_ULP_ThirdPartyID */
typedef struct ThirdPartyID {
    ThirdPartyID_PR present;
    union ThirdPartyID_u {
        IA5String_t     logicalName;
        OCTET_STRING_t     msisdn;
        IA5String_t     emailaddr;
        VisibleString_t     sip_uri;
        VisibleString_t     ims_public_identity;
        BIT_STRING_t     min;
        OCTET_STRING_t     mdn;
        VisibleString_t     uri;
        /*
         * This type is extensible,
         * possible extensions are below.
         */
    } choice;
    
    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} ThirdPartyID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThirdPartyID;

#ifdef __cplusplus
}
#endif

#endif    /* _SUPL_ULP_ThirdPartyID_H_ */
