/*
 * SUPL_ULP_PosPayLoad.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-POS"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#ifndef    _SUPL_ULP_PosPayLoad_H_
#define    _SUPL_ULP_PosPayLoad_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "SUPL_ULP_Ver2-PosPayLoad-extension.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosPayLoad_PR {
    PosPayLoad_PR_NOTHING,    /* No components present */
    PosPayLoad_PR_tia801payload,
    PosPayLoad_PR_rrcPayload,
    PosPayLoad_PR_rrlpPayload,
    /* Extensions may appear below */
    PosPayLoad_PR_ver2_PosPayLoad_extension
} PosPayLoad_PR;

/* SUPL_ULP_PosPayLoad */
typedef struct PosPayLoad {
    PosPayLoad_PR present;
    union PosPayLoad_u {
        OCTET_STRING_t     tia801payload;
        OCTET_STRING_t     rrcPayload;
        OCTET_STRING_t     rrlpPayload;
        /*
         * This type is extensible,
         * possible extensions are below.
         */
        Ver2_PosPayLoad_extension_t     ver2_PosPayLoad_extension;
    } choice;
    
    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} PosPayLoad_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosPayLoad;

#ifdef __cplusplus
}
#endif

#endif    /* _SUPL_ULP_PosPayLoad_H_ */
