BUILD_MMDSP_PROC_audio/transducer_equalizer=bin
NO_STD_BUILD_audio/transducer_equalizer=1
BUILD_MMDSP_NMF_audio/transducer_equalizer=bin
BUILD_ARM_PROC_audio/transducer_equalizer=bin
BUILD_ARM_CODE_audio/transducer_equalizer=bin
BUILD_ARM_NMF_audio/transducer_equalizer=bin
BUILD_XP70_SIA_CODE_audio/transducer_equalizer=false
