BUILD_MMDSP_PROC_video/components/common=bin
NO_STD_BUILD_video/components/common=1
BUILD_MMDSP_NMF_video/components/common=bin
BUILD_ARM_PROC_video/components/common=bin
BUILD_ARM_CODE_video/components/common=src
BUILD_ARM_NMF_video/components/common=src
BUILD_XP70_SIA_CODE_video/components/common=false
