# -*- Mode: Makefile -*-
# vim:syntax=make:

DIRECTORIES += omx_toolbox
DIRECTORIES += img_ens
DIRECTORIES += img_enswrapper 
DIRECTORIES += wom 

include $(MM_MAKEFILES_DIR)/SharedDispatch.mk

#all lib solib clean install_source install exe: 
#	@echo Launching submak with options: $*
#	make -C img_ens $*
#	make -C img_enswrapper  $*
#	make -C wom  $*


	#test part
#	make -C img_enswrapper/test/img_test $*
#	make -C img_enswrapper/test/nonregr $*

