/*
 * RRLP_RRLP-Component.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP_Messages"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RRLP_RRLP_Component_H_
#define	_RRLP_RRLP_Component_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRLP_MsrPosition-Req.h"
#include "RRLP_MsrPosition-Rsp.h"
#include "RRLP_AssistanceData.h"
#include <NULL.h>
#include "RRLP_ProtocolError.h"
#include "RRLP_PosCapability-Req.h"
#include "RRLP_PosCapability-Rsp.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRLP_RRLP_Component_PR {
	RRLP_RRLP_Component_PR_NOTHING,	/* No components present */
	RRLP_RRLP_Component_PR_msrPositionReq,
	RRLP_RRLP_Component_PR_msrPositionRsp,
	RRLP_RRLP_Component_PR_assistanceData,
	RRLP_RRLP_Component_PR_assistanceDataAck,
	RRLP_RRLP_Component_PR_protocolError,
	/* Extensions may appear below */
	RRLP_RRLP_Component_PR_posCapabilityReq,
	RRLP_RRLP_Component_PR_posCapabilityRsp
} RRLP_RRLP_Component_PR;

/* RRLP_RRLP_Component */
typedef struct RRLP_RRLP_Component {
	RRLP_RRLP_Component_PR present;
	union RRLP_RRLP_Component_u {
		RRLP_MsrPosition_Req_t	 msrPositionReq;
		RRLP_MsrPosition_Rsp_t	 msrPositionRsp;
		RRLP_AssistanceData_t	 assistanceData;
		NULL_t	 assistanceDataAck;
		RRLP_ProtocolError_t	 protocolError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		RRLP_PosCapability_Req_t	 posCapabilityReq;
		RRLP_PosCapability_Rsp_t	 posCapabilityRsp;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRLP_RRLP_Component_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRLP_RRLP_Component;

#ifdef __cplusplus
}
#endif

#endif	/* _RRLP_RRLP_Component_H_ */

