/*
 * RRLP_GANSSGenericAssistDataElement.h
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP_Components"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RRLP_GANSSGenericAssistDataElement_H_
#define	_RRLP_GANSSGenericAssistDataElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RRLP_SeqOfGANSSTimeModel;
struct RRLP_GANSSDiffCorrections;
struct RRLP_GANSSNavModel;
struct RRLP_GANSSRealTimeIntegrity;
struct RRLP_GANSSDataBitAssist;
struct RRLP_GANSSRefMeasurementAssist;
struct RRLP_GANSSAlmanacModel;
struct RRLP_GANSSUTCModel;
struct RRLP_GANSSEphemerisExtension;
struct RRLP_GANSSEphemerisExtensionCheck;
struct RRLP_GANSSAddUTCModel;
struct RRLP_GANSSAuxiliaryInformation;
struct RRLP_GANSSDiffCorrectionsValidityPeriod;
struct RRLP_SeqOfGANSSTimeModel_R10_Ext;
struct RRLP_GANSSRefMeasurementAssist_R10_Ext;
struct RRLP_GANSSAlmanacModel_R10_Ext;

/* RRLP_GANSSGenericAssistDataElement */
typedef struct RRLP_GANSSGenericAssistDataElement {
	long	*ganssID	/* OPTIONAL */;
	struct RRLP_SeqOfGANSSTimeModel	*ganssTimeModel	/* OPTIONAL */;
	struct RRLP_GANSSDiffCorrections	*ganssDiffCorrections	/* OPTIONAL */;
	struct RRLP_GANSSNavModel	*ganssNavigationModel	/* OPTIONAL */;
	struct RRLP_GANSSRealTimeIntegrity	*ganssRealTimeIntegrity	/* OPTIONAL */;
	struct RRLP_GANSSDataBitAssist	*ganssDataBitAssist	/* OPTIONAL */;
	struct RRLP_GANSSRefMeasurementAssist	*ganssRefMeasurementAssist	/* OPTIONAL */;
	struct RRLP_GANSSAlmanacModel	*ganssAlmanacModel	/* OPTIONAL */;
	struct RRLP_GANSSUTCModel	*ganssUTCModel	/* OPTIONAL */;
	struct RRLP_GANSSEphemerisExtension	*ganssEphemerisExtension	/* OPTIONAL */;
	struct RRLP_GANSSEphemerisExtensionCheck	*ganssEphemerisExtCheck	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*sbasID	/* OPTIONAL */;
	struct RRLP_GANSSAddUTCModel	*ganssAddUTCModel	/* OPTIONAL */;
	struct RRLP_GANSSAuxiliaryInformation	*ganssAuxiliaryInfo	/* OPTIONAL */;
	struct RRLP_GANSSDiffCorrectionsValidityPeriod	*ganssDiffCorrectionsValidityPeriod	/* OPTIONAL */;
	struct RRLP_SeqOfGANSSTimeModel_R10_Ext	*ganssTimeModel_R10_Ext	/* OPTIONAL */;
	struct RRLP_GANSSRefMeasurementAssist_R10_Ext	*ganssRefMeasurementAssist_R10_Ext	/* OPTIONAL */;
	struct RRLP_GANSSAlmanacModel_R10_Ext	*ganssAlmanacModel_R10_Ext	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRLP_GANSSGenericAssistDataElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRLP_GANSSGenericAssistDataElement;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRLP_SeqOfGANSSTimeModel.h"
#include "RRLP_GANSSDiffCorrections.h"
#include "RRLP_GANSSNavModel.h"
#include "RRLP_GANSSRealTimeIntegrity.h"
#include "RRLP_GANSSDataBitAssist.h"
#include "RRLP_GANSSRefMeasurementAssist.h"
#include "RRLP_GANSSAlmanacModel.h"
#include "RRLP_GANSSUTCModel.h"
#include "RRLP_GANSSEphemerisExtension.h"
#include "RRLP_GANSSEphemerisExtensionCheck.h"
#include "RRLP_GANSSAddUTCModel.h"
#include "RRLP_GANSSAuxiliaryInformation.h"
#include "RRLP_GANSSDiffCorrectionsValidityPeriod.h"
#include "RRLP_SeqOfGANSSTimeModel-R10-Ext.h"
#include "RRLP_GANSSRefMeasurementAssist-R10-Ext.h"
#include "RRLP_GANSSAlmanacModel-R10-Ext.h"

#endif	/* _RRLP_GANSSGenericAssistDataElement_H_ */
