# -*- Mode: Makefile -*-
# vim:syntax=make:

include $(MM_MAKEFILES_DIR)/AudioNmfArch.mk

CPPFLAGS+=-I$(COMPONENT_TOP_DIR)/include -DNVERBOSE -I$(COMPONENT_TOP_DIR)/inc -I$(COMPONENT_TOP_DIR)/mpc/include

LDFLAGS+=./build/tmp/test/obj/rtos/synchronous/synchronous/scheduler.o
