#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedConfig.mk

INSTALL_HEADERDIR:=.

INSTALL_HEADER_PREFIX_DIR:=omxil/

todo: header

test:
	@echo No test to launch !

cleantest:
	@echo No test to clean !

include $(MM_MAKEFILES_DIR)/SharedRules.mk
