#include <trace.idt>

interface vc1dec.mpc.api.mpc_trace_init { 

/* This file specifies methods included inside provided interface named iTrace
          i.e. :          - traceInit
*/

/** @addtogroup vc1decTraceInitGroup startCabac
 *  @ingroup vc1decProvidedInterfaceGroup
 *  @{ 
 */
/*!
 Description : Launch HED phase
 \param[in]  TraceInfo_t        Trace structure info
 \param[in]  id                 Component id 
 *
 *
 */ 

void traceInit(	
					TraceInfo_t trace_info, 
					t_uint16 id);

 /** @} */ // end of vc1decTraceInitGroup

} // interface vc1dec.mpc.api.mpc_trace_init
