
#ifndef _SIA_H_
#define _SIA_H_

/****************************************************************************************
*                     Copyright STMicroelectronics
*              All rights reserved, COMPANY CONFIDENTIAL
*     Unauthorized reproduction and communication strictly prohibited
*----------------------------------------------------------------------------------------
*                   System Platforms Group - IP&Design/SPG
*----------------------------------------------------------------------------------------
*  This C header file was automatically generated by 'spirit2regtest' utility from the
*  SPIRIT description of the component.
*
*  Purpose : It declares C preprocessor definitions for component, register and 
*            register fields parameters
*
*  Generated by spirit2regtest v1.7.6
*

*  WARNING This file has been modify by /vobs/NOMADIK_SIA/VERIFICATION/SETUP/UTILS/byte2double.pl to adapte :
*     header address byte to address double-byte
*     for xbus/mmdsp target
*  (SIA Team )

*  PLEASE DO NOT MODIFY THIS FILE
****************************************************************************************/


/*
* Component section
* Purpose : defines macros for component
*           specific informations
*/

#define SIA_VENDOR                                          ("st.com")
#define SIA_LIBRARY                                         ("orphan_component")
#define SIA_NAME                                            ("SIA")
#define SIA_VERSION                                         ("0.0")

/*
* Address Block : SIA
*/

#define SIA_SIA_BASE_ADDR                                   (0xa000U)

/*
* Register section
* Purpose : defines macros for register and
*           its associated fields specific
*           informations
*/

/*
* Register : SIA_RESET
*/

#define SIA_SIA_RESET_SIZE                                  (16)
#define SIA_SIA_RESET_OFFSET                                (SIA_SIA_BASE_ADDR + 0x00)
#define SIA_SIA_RESET_RESET_VALUE                           (0x00)
#define SIA_SIA_RESET_BITFIELD_MASK                         (0x001F)
#define SIA_SIA_RESET_RWMASK                                (0x001F)
#define SIA_SIA_RESET_ROMASK                                (0x0000)
#define SIA_SIA_RESET_WOMASK                                (0x0000)
#define SIA_SIA_RESET_UNUSED_MASK                           (0xFFE0)
#define SIA_SIA_RESET_SIA_CORE_OFFSET                       (0x0000)
#define SIA_SIA_RESET_SIA_CORE_WIDTH                        (1)
#define SIA_SIA_RESET_SIA_CORE_MASK                         (0x0001)
#define SIA_SIA_RESET_SIA_CORE_B_0x0                        (0x0000)
#define SIA_SIA_RESET_SIA_CORE_B_0x1                        (0x0001)
#define SIA_SIA_RESET_IPP_OFFSET                            (0x0001)
#define SIA_SIA_RESET_IPP_WIDTH                             (1)
#define SIA_SIA_RESET_IPP_MASK                              (0x0002)
#define SIA_SIA_RESET_IPP_B_0x0                             (0x0000)
#define SIA_SIA_RESET_IPP_B_0x1                             (0x0001)
#define SIA_SIA_RESET_VCF_OFFSET                            (0x0002)
#define SIA_SIA_RESET_VCF_WIDTH                             (1)
#define SIA_SIA_RESET_VCF_MASK                              (0x0004)
#define SIA_SIA_RESET_VCF_B_0x0                             (0x0000)
#define SIA_SIA_RESET_VCF_B_0x1                             (0x0001)
#define SIA_SIA_RESET_PROJ_OFFSET                           (0x0003)
#define SIA_SIA_RESET_PROJ_WIDTH                            (1)
#define SIA_SIA_RESET_PROJ_MASK                             (0x0008)
#define SIA_SIA_RESET_PROJ_B_0x0                            (0x0000)
#define SIA_SIA_RESET_PROJ_B_0x1                            (0x0001)
#define SIA_SIA_RESET_ROT_OFFSET                            (0x0004)
#define SIA_SIA_RESET_ROT_WIDTH                             (1)
#define SIA_SIA_RESET_ROT_MASK                              (0x0010)
#define SIA_SIA_RESET_ROT_B_0x0                             (0x0000)
#define SIA_SIA_RESET_ROT_B_0x1                             (0x0001)

/*
* Register : SIA_CLK_ENABLE
*/

#define SIA_SIA_CLK_ENABLE_SIZE                             (16)
#define SIA_SIA_CLK_ENABLE_OFFSET                           (SIA_SIA_BASE_ADDR + 0x08)
#define SIA_SIA_CLK_ENABLE_RESET_VALUE                      (0x00)
#define SIA_SIA_CLK_ENABLE_BITFIELD_MASK                    (0x001F)
#define SIA_SIA_CLK_ENABLE_RWMASK                           (0x001F)
#define SIA_SIA_CLK_ENABLE_ROMASK                           (0x0000)
#define SIA_SIA_CLK_ENABLE_WOMASK                           (0x0000)
#define SIA_SIA_CLK_ENABLE_UNUSED_MASK                      (0xFFE0)
#define SIA_SIA_CLK_ENABLE_DMA_OFFSET                       (0x0000)
#define SIA_SIA_CLK_ENABLE_DMA_WIDTH                        (1)
#define SIA_SIA_CLK_ENABLE_DMA_MASK                         (0x0001)
#define SIA_SIA_CLK_ENABLE_DMA_B_0x0                        (0x0000)
#define SIA_SIA_CLK_ENABLE_DMA_B_0x1                        (0x0001)
#define SIA_SIA_CLK_ENABLE_STBP_OFFSET                      (0x0001)
#define SIA_SIA_CLK_ENABLE_STBP_WIDTH                       (1)
#define SIA_SIA_CLK_ENABLE_STBP_MASK                        (0x0002)
#define SIA_SIA_CLK_ENABLE_STBP_B_0x0                       (0x0000)
#define SIA_SIA_CLK_ENABLE_STBP_B_0x1                       (0x0001)
#define SIA_SIA_CLK_ENABLE_IPP_OFFSET                       (0x0002)
#define SIA_SIA_CLK_ENABLE_IPP_WIDTH                        (1)
#define SIA_SIA_CLK_ENABLE_IPP_MASK                         (0x0004)
#define SIA_SIA_CLK_ENABLE_IPP_B_0x0                        (0x0000)
#define SIA_SIA_CLK_ENABLE_IPP_B_0x1                        (0x0001)
#define SIA_SIA_CLK_ENABLE_VCF_OFFSET                       (0x0003)
#define SIA_SIA_CLK_ENABLE_VCF_WIDTH                        (1)
#define SIA_SIA_CLK_ENABLE_VCF_MASK                         (0x0008)
#define SIA_SIA_CLK_ENABLE_VCF_B_0x0                        (0x0000)
#define SIA_SIA_CLK_ENABLE_VCF_B_0x1                        (0x0001)
#define SIA_SIA_CLK_ENABLE_PROJ_OFFSET                      (0x0004)
#define SIA_SIA_CLK_ENABLE_PROJ_WIDTH                       (1)
#define SIA_SIA_CLK_ENABLE_PROJ_MASK                        (0x0010)
#define SIA_SIA_CLK_ENABLE_PROJ_B_0x0                       (0x0000)
#define SIA_SIA_CLK_ENABLE_PROJ_B_0x1                       (0x0001)

/*
* Register : SIA_IDN_HRV
*/

#define SIA_SIA_IDN_HRV_SIZE                                (16)
#define SIA_SIA_IDN_HRV_OFFSET                              (SIA_SIA_BASE_ADDR + 0x10)
#define SIA_SIA_IDN_HRV_RESET_VALUE                         (0x00)
#define SIA_SIA_IDN_HRV_BITFIELD_MASK                       (0x0FFF)
#define SIA_SIA_IDN_HRV_RWMASK                              (0x0000)
#define SIA_SIA_IDN_HRV_ROMASK                              (0x0FFF)
#define SIA_SIA_IDN_HRV_WOMASK                              (0x0000)
#define SIA_SIA_IDN_HRV_UNUSED_MASK                         (0xF000)
#define SIA_SIA_IDN_HRV_R0_OFFSET                           (0x0000)
#define SIA_SIA_IDN_HRV_R0_WIDTH                            (4)
#define SIA_SIA_IDN_HRV_R0_MASK                             (0x000F)
#define SIA_SIA_IDN_HRV_R1_OFFSET                           (0x0004)
#define SIA_SIA_IDN_HRV_R1_WIDTH                            (4)
#define SIA_SIA_IDN_HRV_R1_MASK                             (0x00F0)
#define SIA_SIA_IDN_HRV_R2_OFFSET                           (0x0008)
#define SIA_SIA_IDN_HRV_R2_WIDTH                            (4)
#define SIA_SIA_IDN_HRV_R2_MASK                             (0x0F00)
#define SIA_SIA_IDN_HRV_R2_B_0x1                            (0x0001)
#define SIA_SIA_IDN_HRV_R2_B_0x2                            (0x0002)
#define SIA_SIA_IDN_HRV_R2_B_0x3                            (0x0003)
#define SIA_SIA_IDN_HRV_R2_B_0x4                            (0x0004)

/*
* Register : SIA_VCF_ENABLE
*/

#define SIA_SIA_VCF_ENABLE_SIZE                             (16)
#define SIA_SIA_VCF_ENABLE_OFFSET                           (SIA_SIA_BASE_ADDR + 0x18)
#define SIA_SIA_VCF_ENABLE_RESET_VALUE                      (0x00)
#define SIA_SIA_VCF_ENABLE_BITFIELD_MASK                    (0x0001)
#define SIA_SIA_VCF_ENABLE_RWMASK                           (0x0001)
#define SIA_SIA_VCF_ENABLE_ROMASK                           (0x0000)
#define SIA_SIA_VCF_ENABLE_WOMASK                           (0x0000)
#define SIA_SIA_VCF_ENABLE_UNUSED_MASK                      (0xFFFE)
#define SIA_SIA_VCF_ENABLE_EN_OFFSET                        (0x0000)
#define SIA_SIA_VCF_ENABLE_EN_WIDTH                         (1)
#define SIA_SIA_VCF_ENABLE_EN_MASK                          (0x0001)
#define SIA_SIA_VCF_ENABLE_EN_B_0x0                         (0x0000)
#define SIA_SIA_VCF_ENABLE_EN_B_0x1                         (0x0001)

/*
* Register : SIA_ROTATION
*/

#define SIA_SIA_ROTATION_SIZE                               (16)
#define SIA_SIA_ROTATION_OFFSET                             (SIA_SIA_BASE_ADDR + 0x19)
#define SIA_SIA_ROTATION_RESET_VALUE                        (0x00)
#define SIA_SIA_ROTATION_BITFIELD_MASK                      (0x0003)
#define SIA_SIA_ROTATION_RWMASK                             (0x0003)
#define SIA_SIA_ROTATION_ROMASK                             (0x0000)
#define SIA_SIA_ROTATION_WOMASK                             (0x0000)
#define SIA_SIA_ROTATION_UNUSED_MASK                        (0xFFFC)
#define SIA_SIA_ROTATION_ROTATION_OFFSET                    (0x0000)
#define SIA_SIA_ROTATION_ROTATION_WIDTH                     (2)
#define SIA_SIA_ROTATION_ROTATION_MASK                      (0x0003)
#define SIA_SIA_ROTATION_ROTATION_B_0x0                     (0x0000)
#define SIA_SIA_ROTATION_ROTATION_B_0x1                     (0x0001)
#define SIA_SIA_ROTATION_ROTATION_B_0x3                     (0x0003)

/*
* Register : ISP_MCU_SYS_ADDR_0_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_0_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x20)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_0_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE0
*/

#define SIA_ISP_MCU_SYS_SIZE0_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE0_OFFSET                        (SIA_SIA_BASE_ADDR + 0x21)
#define SIA_ISP_MCU_SYS_SIZE0_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE0_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE0_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE0_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE0_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE0_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE0_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_1_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_1_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x22)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_1_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE1
*/

#define SIA_ISP_MCU_SYS_SIZE1_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE1_OFFSET                        (SIA_SIA_BASE_ADDR + 0x23)
#define SIA_ISP_MCU_SYS_SIZE1_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE1_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE1_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE1_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE1_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE1_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE1_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_2_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_2_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x24)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_2_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE2
*/

#define SIA_ISP_MCU_SYS_SIZE2_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE2_OFFSET                        (SIA_SIA_BASE_ADDR + 0x25)
#define SIA_ISP_MCU_SYS_SIZE2_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE2_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE2_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE2_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE2_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE2_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE2_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_3_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_3_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x26)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_3_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE3
*/

#define SIA_ISP_MCU_SYS_SIZE3_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE3_OFFSET                        (SIA_SIA_BASE_ADDR + 0x27)
#define SIA_ISP_MCU_SYS_SIZE3_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE3_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE3_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE3_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE3_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE3_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE3_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_4_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_4_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x28)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_4_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE4
*/

#define SIA_ISP_MCU_SYS_SIZE4_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE4_OFFSET                        (SIA_SIA_BASE_ADDR + 0x29)
#define SIA_ISP_MCU_SYS_SIZE4_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE4_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE4_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE4_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE4_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE4_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE4_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_5_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_5_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x2a)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_5_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE5
*/

#define SIA_ISP_MCU_SYS_SIZE5_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE5_OFFSET                        (SIA_SIA_BASE_ADDR + 0x2b)
#define SIA_ISP_MCU_SYS_SIZE5_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE5_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE5_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE5_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE5_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE5_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE5_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_6_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_6_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x2c)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_6_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE6
*/

#define SIA_ISP_MCU_SYS_SIZE6_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE6_OFFSET                        (SIA_SIA_BASE_ADDR + 0x2d)
#define SIA_ISP_MCU_SYS_SIZE6_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE6_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE6_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE6_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE6_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE6_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE6_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_SYS_ADDR_7_HI
*/

#define SIA_ISP_MCU_SYS_ADDR_7_HI_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_OFFSET                    (SIA_SIA_BASE_ADDR + 0x2e)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_RESET_VALUE               (0x4F00)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_BITFIELD_MASK             (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_RWMASK                    (0xFFFF)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_UNUSED_MASK               (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_REGION_BA_HI_OFFSET       (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_REGION_BA_HI_WIDTH        (16)
#define SIA_ISP_MCU_SYS_ADDR_7_HI_REGION_BA_HI_MASK         (0xFFFF)

/*
* Register : ISP_MCU_SYS_SIZE7
*/

#define SIA_ISP_MCU_SYS_SIZE7_SIZE                          (16)
#define SIA_ISP_MCU_SYS_SIZE7_OFFSET                        (SIA_SIA_BASE_ADDR + 0x2f)
#define SIA_ISP_MCU_SYS_SIZE7_RESET_VALUE                   (0x00)
#define SIA_ISP_MCU_SYS_SIZE7_BITFIELD_MASK                 (0x0007)
#define SIA_ISP_MCU_SYS_SIZE7_RWMASK                        (0x0007)
#define SIA_ISP_MCU_SYS_SIZE7_ROMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE7_WOMASK                        (0x0000)
#define SIA_ISP_MCU_SYS_SIZE7_UNUSED_MASK                   (0xFFF8)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_OFFSET              (0x0000)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_WIDTH               (3)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_MASK                (0x0007)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x0               (0x0000)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x1               (0x0001)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x2               (0x0002)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x3               (0x0003)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x4               (0x0004)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x5               (0x0005)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x6               (0x0006)
#define SIA_ISP_MCU_SYS_SIZE7_REGION_SZ_B_0x7               (0x0007)

/*
* Register : ISP_MCU_IO_ADDR_0_HI
*/

#define SIA_ISP_MCU_IO_ADDR_0_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_0_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x30)
#define SIA_ISP_MCU_IO_ADDR_0_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_0_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_0_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_0_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_0_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_1_HI
*/

#define SIA_ISP_MCU_IO_ADDR_1_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_1_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x31)
#define SIA_ISP_MCU_IO_ADDR_1_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_1_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_1_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_1_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_1_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_2_HI
*/

#define SIA_ISP_MCU_IO_ADDR_2_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_2_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x32)
#define SIA_ISP_MCU_IO_ADDR_2_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_2_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_2_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_2_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_2_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_3_HI
*/

#define SIA_ISP_MCU_IO_ADDR_3_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_3_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x33)
#define SIA_ISP_MCU_IO_ADDR_3_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_3_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_3_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_3_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_3_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_4_HI
*/

#define SIA_ISP_MCU_IO_ADDR_4_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_4_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x34)
#define SIA_ISP_MCU_IO_ADDR_4_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_4_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_4_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_4_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_4_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_5_HI
*/

#define SIA_ISP_MCU_IO_ADDR_5_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_5_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x35)
#define SIA_ISP_MCU_IO_ADDR_5_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_5_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_5_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_5_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_5_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_6_HI
*/

#define SIA_ISP_MCU_IO_ADDR_6_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_6_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x36)
#define SIA_ISP_MCU_IO_ADDR_6_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_6_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_6_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_6_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_6_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MCU_IO_ADDR_7_HI
*/

#define SIA_ISP_MCU_IO_ADDR_7_HI_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_7_HI_OFFSET                     (SIA_SIA_BASE_ADDR + 0x37)
#define SIA_ISP_MCU_IO_ADDR_7_HI_RESET_VALUE                (0x4F00)
#define SIA_ISP_MCU_IO_ADDR_7_HI_BITFIELD_MASK              (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_7_HI_RWMASK                     (0xFFFF)
#define SIA_ISP_MCU_IO_ADDR_7_HI_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_HI_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_HI_UNUSED_MASK                (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_HI_REGION_BA_HI_OFFSET        (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_HI_REGION_BA_HI_WIDTH         (16)
#define SIA_ISP_MCU_IO_ADDR_7_HI_REGION_BA_HI_MASK          (0xFFFF)

/*
* Register : ISP_MEM_PAGE
*/

#define SIA_ISP_MEM_PAGE_SIZE                               (16)
#define SIA_ISP_MEM_PAGE_OFFSET                             (SIA_SIA_BASE_ADDR + 0x38)
#define SIA_ISP_MEM_PAGE_RESET_VALUE                        (0x00)
#define SIA_ISP_MEM_PAGE_BITFIELD_MASK                      (0x003F)
#define SIA_ISP_MEM_PAGE_RWMASK                             (0x003F)
#define SIA_ISP_MEM_PAGE_ROMASK                             (0x0000)
#define SIA_ISP_MEM_PAGE_WOMASK                             (0x0000)
#define SIA_ISP_MEM_PAGE_UNUSED_MASK                        (0xFFC0)
#define SIA_ISP_MEM_PAGE_INDEX_OFFSET                       (0x0000)
#define SIA_ISP_MEM_PAGE_INDEX_WIDTH                        (6)
#define SIA_ISP_MEM_PAGE_INDEX_MASK                         (0x003F)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x0                        (0x0000)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x1                        (0x0001)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x2                        (0x0002)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x3                        (0x0003)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x4                        (0x0004)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x5                        (0x0005)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x6                        (0x0006)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x7                        (0x0007)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x8                        (0x0008)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x9                        (0x0009)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xA                        (0x000A)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xB                        (0x000B)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xC                        (0x000C)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xD                        (0x000D)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xE                        (0x000E)
#define SIA_ISP_MEM_PAGE_INDEX_B_0xF                        (0x000F)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x10                       (0x0010)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x11                       (0x0011)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x12                       (0x0012)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x13                       (0x0013)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x14                       (0x0014)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x15                       (0x0015)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x16                       (0x0016)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x17                       (0x0017)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x18                       (0x0018)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x19                       (0x0019)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x20                       (0x0020)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x21                       (0x0021)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x22                       (0x0022)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x23                       (0x0023)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x24                       (0x0024)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x25                       (0x0025)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x26                       (0x0026)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x27                       (0x0027)
#define SIA_ISP_MEM_PAGE_INDEX_B_0x30                       (0x0030)

/*
* Register : SIA_XBUS_BYTE_ENABLE
*/

#define SIA_SIA_XBUS_BYTE_ENABLE_SIZE                       (16)
#define SIA_SIA_XBUS_BYTE_ENABLE_OFFSET                     (SIA_SIA_BASE_ADDR + 0x39)
#define SIA_SIA_XBUS_BYTE_ENABLE_RESET_VALUE                (0x303)
#define SIA_SIA_XBUS_BYTE_ENABLE_BITFIELD_MASK              (0x0303)
#define SIA_SIA_XBUS_BYTE_ENABLE_RWMASK                     (0x0303)
#define SIA_SIA_XBUS_BYTE_ENABLE_ROMASK                     (0x0000)
#define SIA_SIA_XBUS_BYTE_ENABLE_WOMASK                     (0x0000)
#define SIA_SIA_XBUS_BYTE_ENABLE_UNUSED_MASK                (0xFCFC)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_OFFSET                 (0x0000)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_WIDTH                  (2)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_MASK                   (0x0003)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_B_0x0                  (0x0000)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_B_0x1                  (0x0001)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_B_0x2                  (0x0002)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE0_B_0x3                  (0x0003)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_OFFSET                 (0x0008)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_WIDTH                  (2)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_MASK                   (0x0300)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_B_0x0                  (0x0000)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_B_0x1                  (0x0001)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_B_0x2                  (0x0002)
#define SIA_SIA_XBUS_BYTE_ENABLE_BE1_B_0x3                  (0x0003)

/*
* Register : SIA_PIPE03_SELECT
*/

#define SIA_SIA_PIPE03_SELECT_SIZE                          (16)
#define SIA_SIA_PIPE03_SELECT_OFFSET                        (SIA_SIA_BASE_ADDR + 0x40)
#define SIA_SIA_PIPE03_SELECT_RESET_VALUE                   (0x00)
#define SIA_SIA_PIPE03_SELECT_BITFIELD_MASK                 (0x0001)
#define SIA_SIA_PIPE03_SELECT_RWMASK                        (0x0001)
#define SIA_SIA_PIPE03_SELECT_ROMASK                        (0x0000)
#define SIA_SIA_PIPE03_SELECT_WOMASK                        (0x0000)
#define SIA_SIA_PIPE03_SELECT_UNUSED_MASK                   (0xFFFE)
#define SIA_SIA_PIPE03_SELECT_AP_OFFSET                     (0x0000)
#define SIA_SIA_PIPE03_SELECT_AP_WIDTH                      (1)
#define SIA_SIA_PIPE03_SELECT_AP_MASK                       (0x0001)
#define SIA_SIA_PIPE03_SELECT_AP_B_0x0                      (0x0000)
#define SIA_SIA_PIPE03_SELECT_AP_B_0x1                      (0x0001)

/*
* Register : LICN_ITS
*/

#define SIA_LICN_ITS_SIZE                                   (16)
#define SIA_LICN_ITS_OFFSET                                 (SIA_SIA_BASE_ADDR + 0x48)
#define SIA_LICN_ITS_RESET_VALUE                            (0x00)
#define SIA_LICN_ITS_BITFIELD_MASK                          (0x0001)
#define SIA_LICN_ITS_RWMASK                                 (0x0000)
#define SIA_LICN_ITS_ROMASK                                 (0x0001)
#define SIA_LICN_ITS_WOMASK                                 (0x0000)
#define SIA_LICN_ITS_UNUSED_MASK                            (0xFFFE)
#define SIA_LICN_ITS_BUSERR_OFFSET                          (0x0000)
#define SIA_LICN_ITS_BUSERR_WIDTH                           (1)
#define SIA_LICN_ITS_BUSERR_MASK                            (0x0001)
#define SIA_LICN_ITS_BUSERR_B_0x0                           (0x0000)
#define SIA_LICN_ITS_BUSERR_B_0x1                           (0x0001)

/*
* Register : LICN_ITS_BCLR
*/

#define SIA_LICN_ITS_BCLR_SIZE                              (16)
#define SIA_LICN_ITS_BCLR_OFFSET                            (SIA_SIA_BASE_ADDR + 0x49)
#define SIA_LICN_ITS_BCLR_RESET_VALUE                       (0x00)
#define SIA_LICN_ITS_BCLR_BITFIELD_MASK                     (0x0001)
#define SIA_LICN_ITS_BCLR_RWMASK                            (0x0000)
#define SIA_LICN_ITS_BCLR_ROMASK                            (0x0000)
#define SIA_LICN_ITS_BCLR_WOMASK                            (0x0001)
#define SIA_LICN_ITS_BCLR_UNUSED_MASK                       (0xFFFE)
#define SIA_LICN_ITS_BCLR_BUSERR_OFFSET                     (0x0000)
#define SIA_LICN_ITS_BCLR_BUSERR_WIDTH                      (1)
#define SIA_LICN_ITS_BCLR_BUSERR_MASK                       (0x0001)
#define SIA_LICN_ITS_BCLR_BUSERR_B_0x0                      (0x0000)
#define SIA_LICN_ITS_BCLR_BUSERR_B_0x1                      (0x0001)

/*
* Register : LICN_ITS_BSET
*/

#define SIA_LICN_ITS_BSET_SIZE                              (16)
#define SIA_LICN_ITS_BSET_OFFSET                            (SIA_SIA_BASE_ADDR + 0x4a)
#define SIA_LICN_ITS_BSET_RESET_VALUE                       (0x00)
#define SIA_LICN_ITS_BSET_BITFIELD_MASK                     (0x0001)
#define SIA_LICN_ITS_BSET_RWMASK                            (0x0000)
#define SIA_LICN_ITS_BSET_ROMASK                            (0x0000)
#define SIA_LICN_ITS_BSET_WOMASK                            (0x0001)
#define SIA_LICN_ITS_BSET_UNUSED_MASK                       (0xFFFE)
#define SIA_LICN_ITS_BSET_BUSERR_OFFSET                     (0x0000)
#define SIA_LICN_ITS_BSET_BUSERR_WIDTH                      (1)
#define SIA_LICN_ITS_BSET_BUSERR_MASK                       (0x0001)
#define SIA_LICN_ITS_BSET_BUSERR_B_0x0                      (0x0000)
#define SIA_LICN_ITS_BSET_BUSERR_B_0x1                      (0x0001)

/*
* Register : LICN_ITM
*/

#define SIA_LICN_ITM_SIZE                                   (16)
#define SIA_LICN_ITM_OFFSET                                 (SIA_SIA_BASE_ADDR + 0x4b)
#define SIA_LICN_ITM_RESET_VALUE                            (0x00)
#define SIA_LICN_ITM_BITFIELD_MASK                          (0x0001)
#define SIA_LICN_ITM_RWMASK                                 (0x0000)
#define SIA_LICN_ITM_ROMASK                                 (0x0001)
#define SIA_LICN_ITM_WOMASK                                 (0x0000)
#define SIA_LICN_ITM_UNUSED_MASK                            (0xFFFE)
#define SIA_LICN_ITM_BUSERR_OFFSET                          (0x0000)
#define SIA_LICN_ITM_BUSERR_WIDTH                           (1)
#define SIA_LICN_ITM_BUSERR_MASK                            (0x0001)
#define SIA_LICN_ITM_BUSERR_B_0x0                           (0x0000)
#define SIA_LICN_ITM_BUSERR_B_0x1                           (0x0001)

/*
* Register : LICN_ITM_BCLR
*/

#define SIA_LICN_ITM_BCLR_SIZE                              (16)
#define SIA_LICN_ITM_BCLR_OFFSET                            (SIA_SIA_BASE_ADDR + 0x4c)
#define SIA_LICN_ITM_BCLR_RESET_VALUE                       (0x00)
#define SIA_LICN_ITM_BCLR_BITFIELD_MASK                     (0x0001)
#define SIA_LICN_ITM_BCLR_RWMASK                            (0x0000)
#define SIA_LICN_ITM_BCLR_ROMASK                            (0x0000)
#define SIA_LICN_ITM_BCLR_WOMASK                            (0x0001)
#define SIA_LICN_ITM_BCLR_UNUSED_MASK                       (0xFFFE)
#define SIA_LICN_ITM_BCLR_BUSERR_OFFSET                     (0x0000)
#define SIA_LICN_ITM_BCLR_BUSERR_WIDTH                      (1)
#define SIA_LICN_ITM_BCLR_BUSERR_MASK                       (0x0001)
#define SIA_LICN_ITM_BCLR_BUSERR_B_0x0                      (0x0000)
#define SIA_LICN_ITM_BCLR_BUSERR_B_0x1                      (0x0001)

/*
* Register : LICN_ITM_BSET
*/

#define SIA_LICN_ITM_BSET_SIZE                              (16)
#define SIA_LICN_ITM_BSET_OFFSET                            (SIA_SIA_BASE_ADDR + 0x4d)
#define SIA_LICN_ITM_BSET_RESET_VALUE                       (0x00)
#define SIA_LICN_ITM_BSET_BITFIELD_MASK                     (0x0001)
#define SIA_LICN_ITM_BSET_RWMASK                            (0x0000)
#define SIA_LICN_ITM_BSET_ROMASK                            (0x0000)
#define SIA_LICN_ITM_BSET_WOMASK                            (0x0001)
#define SIA_LICN_ITM_BSET_UNUSED_MASK                       (0xFFFE)
#define SIA_LICN_ITM_BSET_BUSERR_OFFSET                     (0x0000)
#define SIA_LICN_ITM_BSET_BUSERR_WIDTH                      (1)
#define SIA_LICN_ITM_BSET_BUSERR_MASK                       (0x0001)
#define SIA_LICN_ITM_BSET_BUSERR_B_0x0                      (0x0000)
#define SIA_LICN_ITM_BSET_BUSERR_B_0x1                      (0x0001)

/*
* Register : ISP_MCU_SYS_ADDR_0_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_0_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x50)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_0_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_1_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_1_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x51)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_1_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_2_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_2_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x52)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_2_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_3_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_3_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x53)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_3_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_4_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_4_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x54)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_4_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_5_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_5_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x55)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_5_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_6_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_6_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x56)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_6_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_SYS_ADDR_7_LO
*/

#define SIA_ISP_MCU_SYS_ADDR_7_LO_SIZE                      (16)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_OFFSET                    (SIA_SIA_BASE_ADDR + 0x57)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_RESET_VALUE               (0x00)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_BITFIELD_MASK             (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_RWMASK                    (0xF000)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_ROMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_WOMASK                    (0x0000)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_UNUSED_MASK               (0x0FFF)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_REGION_BA_LO_OFFSET       (0x000c)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_REGION_BA_LO_WIDTH        (4)
#define SIA_ISP_MCU_SYS_ADDR_7_LO_REGION_BA_LO_MASK         (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_0_LO
*/

#define SIA_ISP_MCU_IO_ADDR_0_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_0_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x60)
#define SIA_ISP_MCU_IO_ADDR_0_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_0_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_0_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_0_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_0_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_0_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_0_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_0_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_1_LO
*/

#define SIA_ISP_MCU_IO_ADDR_1_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_1_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x61)
#define SIA_ISP_MCU_IO_ADDR_1_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_1_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_1_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_1_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_1_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_1_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_1_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_1_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_2_LO
*/

#define SIA_ISP_MCU_IO_ADDR_2_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_2_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x62)
#define SIA_ISP_MCU_IO_ADDR_2_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_2_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_2_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_2_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_2_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_2_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_2_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_2_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_3_LO
*/

#define SIA_ISP_MCU_IO_ADDR_3_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_3_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x63)
#define SIA_ISP_MCU_IO_ADDR_3_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_3_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_3_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_3_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_3_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_3_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_3_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_3_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_4_LO
*/

#define SIA_ISP_MCU_IO_ADDR_4_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_4_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x64)
#define SIA_ISP_MCU_IO_ADDR_4_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_4_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_4_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_4_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_4_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_4_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_4_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_4_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_5_LO
*/

#define SIA_ISP_MCU_IO_ADDR_5_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_5_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x65)
#define SIA_ISP_MCU_IO_ADDR_5_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_5_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_5_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_5_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_5_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_5_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_5_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_5_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_6_LO
*/

#define SIA_ISP_MCU_IO_ADDR_6_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_6_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x66)
#define SIA_ISP_MCU_IO_ADDR_6_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_6_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_6_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_6_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_6_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_6_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_6_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_6_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_ADDR_7_LO
*/

#define SIA_ISP_MCU_IO_ADDR_7_LO_SIZE                       (16)
#define SIA_ISP_MCU_IO_ADDR_7_LO_OFFSET                     (SIA_SIA_BASE_ADDR + 0x67)
#define SIA_ISP_MCU_IO_ADDR_7_LO_RESET_VALUE                (0x00)
#define SIA_ISP_MCU_IO_ADDR_7_LO_BITFIELD_MASK              (0xF000)
#define SIA_ISP_MCU_IO_ADDR_7_LO_RWMASK                     (0xF000)
#define SIA_ISP_MCU_IO_ADDR_7_LO_ROMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_LO_WOMASK                     (0x0000)
#define SIA_ISP_MCU_IO_ADDR_7_LO_UNUSED_MASK                (0x0FFF)
#define SIA_ISP_MCU_IO_ADDR_7_LO_REGION_BA_LO_OFFSET        (0x000c)
#define SIA_ISP_MCU_IO_ADDR_7_LO_REGION_BA_LO_WIDTH         (4)
#define SIA_ISP_MCU_IO_ADDR_7_LO_REGION_BA_LO_MASK          (0xF000)

/*
* Register : ISP_MCU_IO_SIZE0
*/

#define SIA_ISP_MCU_IO_SIZE0_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE0_OFFSET                         (SIA_SIA_BASE_ADDR + 0x70)
#define SIA_ISP_MCU_IO_SIZE0_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE0_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE0_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE0_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE0_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE0_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE0_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE1
*/

#define SIA_ISP_MCU_IO_SIZE1_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE1_OFFSET                         (SIA_SIA_BASE_ADDR + 0x71)
#define SIA_ISP_MCU_IO_SIZE1_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE1_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE1_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE1_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE1_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE1_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE1_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE2
*/

#define SIA_ISP_MCU_IO_SIZE2_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE2_OFFSET                         (SIA_SIA_BASE_ADDR + 0x72)
#define SIA_ISP_MCU_IO_SIZE2_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE2_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE2_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE2_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE2_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE2_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE2_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE3
*/

#define SIA_ISP_MCU_IO_SIZE3_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE3_OFFSET                         (SIA_SIA_BASE_ADDR + 0x73)
#define SIA_ISP_MCU_IO_SIZE3_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE3_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE3_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE3_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE3_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE3_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE3_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE4
*/

#define SIA_ISP_MCU_IO_SIZE4_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE4_OFFSET                         (SIA_SIA_BASE_ADDR + 0x74)
#define SIA_ISP_MCU_IO_SIZE4_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE4_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE4_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE4_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE4_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE4_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE4_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE5
*/

#define SIA_ISP_MCU_IO_SIZE5_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE5_OFFSET                         (SIA_SIA_BASE_ADDR + 0x75)
#define SIA_ISP_MCU_IO_SIZE5_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE5_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE5_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE5_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE5_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE5_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE5_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE6
*/

#define SIA_ISP_MCU_IO_SIZE6_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE6_OFFSET                         (SIA_SIA_BASE_ADDR + 0x76)
#define SIA_ISP_MCU_IO_SIZE6_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE6_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE6_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE6_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE6_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE6_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE6_REGION_SZ_B_0x7                (0x0007)

/*
* Register : ISP_MCU_IO_SIZE7
*/

#define SIA_ISP_MCU_IO_SIZE7_SIZE                           (16)
#define SIA_ISP_MCU_IO_SIZE7_OFFSET                         (SIA_SIA_BASE_ADDR + 0x77)
#define SIA_ISP_MCU_IO_SIZE7_RESET_VALUE                    (0x00)
#define SIA_ISP_MCU_IO_SIZE7_BITFIELD_MASK                  (0x0007)
#define SIA_ISP_MCU_IO_SIZE7_RWMASK                         (0x0007)
#define SIA_ISP_MCU_IO_SIZE7_ROMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE7_WOMASK                         (0x0000)
#define SIA_ISP_MCU_IO_SIZE7_UNUSED_MASK                    (0xFFF8)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_OFFSET               (0x0000)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_WIDTH                (3)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_MASK                 (0x0007)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x0                (0x0000)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x1                (0x0001)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x2                (0x0002)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x3                (0x0003)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x4                (0x0004)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x5                (0x0005)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x6                (0x0006)
#define SIA_ISP_MCU_IO_SIZE7_REGION_SZ_B_0x7                (0x0007)

#endif /* _SIA_H_ */
