#include <t1xhv_vec_h264.idt>
#include <t1xhv_common.idt>

/** @addtogroup vecH264endAlgoGroup endAlgo
 *  @ingroup vecH264RequiredInterfaceGroup
 *  @{ 
 */
/*!
 Description : Report the end of a NMF ALGO component.
 \param[in]  status		      Status of the process done.
 \param[in]  errors         Error description (if any).
 \param[in]  durationInTicks  Duration (in SVA's timer ticks unit, i.e. 90kHz) of the algo process that have been done 
                            (i.e. between a CMD_START of the algo and its completion).
 *
 * \remarks	For the corresponding ITF server name(s), please refer to \ref vecH264ConfigurationGroup
 * 
 */

void endAlgo(t_t1xhv_status status, t_uint32 errors, t_uint32 durationInTicks);

/** @} */ // end of vecH264endAlgoGroup

