// Common interface between splitter and decoder 
#include <h264enc/arm_nmf/api/nmftype.idt>
#include <frameinfo.idt>

void get_headers(t_frameinfo* p_params, void* buffer1, t_uint16* size1, void* buffer2, t_uint16* size2, t_uint16 no_headers_stream);

