// Common interface between splitter and decoder 
#include <h264enc/arm_nmf/api/nmftype.idt>

void notify_output_buffer(void *p_b, t_uint32 offset, t_uint32 size, t_valid_output valid, t_uint32 nTimeStampH, t_uint32 nTimeStampL, t_uint32 nFlags);
