#include <h264enc/arm_nmf/api/nmftype.idt>
#include <frameinfo.idt>

interface h264enc.arm_nmf.api.set_config {

void set_config(t_uint32 domainDdrId, t_uint32 domainEsramId, t_frameinfo frame_info);
void set_VideoStabParam(t_uint32 OSWidth,t_uint32 OSHeight);
void set_param(void *ptr);
}
