

/** @addtogroup vecH264UpdateAlgoGroup updateAlgo
 *  @ingroup vecH264ProvidedInterfaceGroup
 *  @{
 */
/*!
 Description : (Not yet implemented) Update the configuration of a specific NMF algo component.
 *   
 * \remarks	For the corresponding ITF server name(s), please refer to \ref vecH264ConfigurationGroup
 */ 
void updateAlgo(void);

/** @} */ // end of vecH264UpdateAlgoGroup
