# vim:syntax=make:
# -*- Mode: Makefile -*-
#
include make.ost_conf

include $(MM_MAKEFILES_DIR)/SharedCheck.mk

all clean realclean install uninstall:
	$(MAKE) -C host $@ 
#	$(MAKE) -C debug $@











