BUILD_MMDSP_PROC_audio/comfortnoise=bin
NO_STD_BUILD_audio/comfortnoise=1
BUILD_MMDSP_NMF_audio/comfortnoise=bin
BUILD_ARM_PROC_audio/comfortnoise=bin
BUILD_ARM_CODE_audio/comfortnoise=bin
BUILD_ARM_NMF_audio/comfortnoise=bin
BUILD_XP70_SIA_CODE_audio/comfortnoise=false
