# vim:syntax=make:
# -*- Mode: Makefile -*-

#WARNING COMPONENT_PATH is MANDATORY for Make.config and Make.rules
#-------------------------------
# Default Config
#-------------------------------
include $(MMROOT)/shared/makefiles/Make.config

#----------------------------
INSTALL_HEADER    = MMIO_Camera.h pictor.h

todo: install 
	@echo "Nothing to be built. $(INSTALL_HEADER) exported through install directive"

#-------------------------------
# Generic Rules
#-------------------------------
include $(MMROOT)/shared/makefiles/Make.rules








