/*                               -*- Mode: C -*-
 * Copyright (C) 2010, ST-Ericsson
 *
 * File name       : uicc_internal.h
 * Description     : uicc internal info
 *
 * Author          : Mats Bergstrom <mats.m.bergstrom@stericsson.com>
 *
 */


#ifndef __uicc_internal_h__
#define __uicc_internal_h__ (1)


#define STE_UICC_RANGE_MASK                      (0xff00)
#define STE_UICC_RANGE_REQ                       (0x2000)
#define STE_UICC_RANGE_RSP                       (0x2100)
#define STE_UICC_RANGE_IND                       (0x2200)

#define STE_UICC_RANGE_REQ_SAP                   (0x2D00)
#define STE_UICC_RANGE_RSP_SAP                   (0x2E00)
#define STE_UICC_RANGE_IND_SAP                   (0x2F00)

typedef enum {
    STE_UICC_REQ_REGISTER = (STE_UICC_RANGE_REQ | 0x0001),
    STE_UICC_REQ_PIN_VERIFY,
    STE_UICC_REQ_READ_SIM_FILE_RECORD,
    STE_UICC_REQ_UPDATE_SIM_FILE_RECORD,
    STE_UICC_REQ_PIN_NEEDED,
    STE_UICC_REQ_PIN_CHANGE,
    STE_UICC_REQ_READ_SIM_FILE_BINARY,
    STE_UICC_REQ_UPDATE_SIM_FILE_BINARY,
    STE_UICC_REQ_SIM_FILE_GET_FORMAT,
    STE_UICC_REQ_GET_FILE_INFORMATION,
    STE_UICC_RSP_NOT_READY,
    STE_UICC_REQ_GET_SIM_STATE,
    STE_UICC_REQ_PIN_DISABLE,
    STE_UICC_REQ_PIN_ENABLE,
    STE_UICC_REQ_PIN_INFO,
    STE_UICC_REQ_PIN_UNBLOCK,
    STE_UICC_REQ_APP_INFO,
    STE_UICC_REQ_READ_SMSC,
    STE_UICC_REQ_UPDATE_SMSC,
    STE_UICC_REQ_SIM_FILE_READ_GENERIC,
    STE_UICC_REQ_UPDATE_SERVICE_TABLE,
    STE_UICC_REQ_GET_SERVICE_TABLE,
    STE_UICC_REQ_SIM_ICON_READ,
    STE_UICC_REQ_READ_SUBSCRIBER_NUMBER,
    STE_UICC_REQ_READ_PLMN,
    STE_UICC_REQ_UPDATE_PLMN,
    STE_UICC_REQ_CARD_STATUS,
    STE_UICC_REQ_APP_STATUS,
    STE_UICC_REQ_APPL_APDU_SEND,
    STE_UICC_REQ_SMSC_GET_RECORD_MAX,
    STE_UICC_REQ_SMSC_SAVE_TO_RECORD,
    STE_UICC_REQ_SMSC_RESTORE_FROM_RECORD,
    STE_UICC_REQ_SIM_CHANNEL_SEND,
    STE_UICC_REQ_SIM_CHANNEL_OPEN,
    STE_UICC_REQ_SIM_CHANNEL_CLOSE,
    STE_UICC_REQ_GET_SERVICE_AVAILABILITY,
    STE_UICC_REQ_READ_FDN,
    STE_UICC_REQ_READ_ECC,
    STE_UICC_REQ_RESET,
    STE_UICC_REQ_SIM_POWER_ON,
    STE_UICC_REQ_SIM_POWER_OFF,
    STE_UICC_REQ_SIM_READ_PREFERRED_RAT_SETTING
#ifndef HAVE_ANDROID_OS
    ,STE_UICC_REQ_SIM_SET_APP_TYPE_TO_SIM
#endif
} ste_uicc_req_sim_t;

typedef enum {
    STE_UICC_RSP_REGISTER = (STE_UICC_RANGE_RSP | 0x0001),
    STE_UICC_RSP_PIN_VERIFY,
    STE_UICC_RSP_READ_SIM_FILE_RECORD,
    STE_UICC_RSP_UPDATE_SIM_FILE_RECORD,
    STE_UICC_RSP_PIN_CHANGE,
    STE_UICC_RSP_READ_SIM_FILE_BINARY,
    STE_UICC_RSP_UPDATE_SIM_FILE_BINARY,
    STE_UICC_RSP_SIM_FILE_GET_FORMAT,
    STE_UICC_RSP_GET_FILE_INFORMATION,
    STE_UICC_RSP_GET_SIM_STATE,
    STE_UICC_RSP_PIN_DISABLE,
    STE_UICC_RSP_PIN_ENABLE,
    STE_UICC_RSP_PIN_INFO,
    STE_UICC_RSP_PIN_UNBLOCK,
    STE_UICC_RSP_APP_INFO,
    STE_UICC_RSP_READ_SMSC,
    STE_UICC_RSP_UPDATE_SMSC,
    STE_UICC_RSP_SIM_FILE_READ_GENERIC,
    STE_UICC_RSP_UPDATE_SERVICE_TABLE,
    STE_UICC_RSP_GET_SERVICE_TABLE,
    STE_UICC_RSP_SIM_ICON_READ,
    STE_UICC_RSP_READ_SUBSCRIBER_NUMBER,
    STE_UICC_RSP_READ_PLMN,
    STE_UICC_RSP_UPDATE_PLMN,
    STE_UICC_RSP_CARD_STATUS,
    STE_UICC_RSP_APP_STATUS,
    STE_UICC_RSP_APPL_APDU_SEND,
    STE_UICC_RSP_SMSC_GET_RECORD_MAX,
    STE_UICC_RSP_SMSC_SAVE_TO_RECORD,
    STE_UICC_RSP_SMSC_RESTORE_FROM_RECORD,
    STE_UICC_RSP_SIM_CHANNEL_SEND,
    STE_UICC_RSP_SIM_CHANNEL_OPEN,
    STE_UICC_RSP_SIM_CHANNEL_CLOSE,
    STE_UICC_RSP_GET_SERVICE_AVAILABILITY,
    STE_UICC_RSP_READ_FDN,
    STE_UICC_RSP_READ_ECC,
    STE_UICC_RSP_RESET,
    STE_UICC_RSP_SIM_POWER_ON,
    STE_UICC_RSP_SIM_POWER_OFF,
    STE_UICC_RSP_SIM_READ_PREFERRED_RAT_SETTING
} ste_uicc_rsp_sim_t;

typedef enum {
    STE_UICC_SIM_STATE_CHANGED = (STE_UICC_RANGE_IND | 0x0001),
    STE_UICC_SIM_STATUS,
} ste_uicc_sim_ind_t;

/* SAP session req/rsp values */
typedef enum {
    STE_UICC_REQ_SAP_SESSION_START = (STE_UICC_RANGE_REQ_SAP | 0x0001),
    STE_UICC_REQ_SAP_SESSION_EXIT,
    STE_UICC_REQ_SAP_SESSION_PWROFF,
    STE_UICC_REQ_SAP_SESSION_PWRON,
    STE_UICC_REQ_SAP_SESSION_RESET,
    STE_UICC_REQ_SAP_SESSION_APDU_DATA,
    STE_UICC_REQ_SAP_SESSION_ATR_GET,
    STE_UICC_REQ_SAP_SESSION_STATUS_GET,
} ste_uicc_sap_req_t;
typedef enum {
    STE_UICC_RSP_SAP_SESSION_START = (STE_UICC_RANGE_RSP_SAP | 0x0001),
    STE_UICC_RSP_SAP_SESSION_EXIT,
    STE_UICC_RSP_SAP_SESSION_PWROFF,
    STE_UICC_RSP_SAP_SESSION_PWRON,
    STE_UICC_RSP_SAP_SESSION_RESET,
    STE_UICC_RSP_SAP_SESSION_APDU_DATA,
    STE_UICC_RSP_SAP_SESSION_ATR_GET,
    STE_UICC_RSP_SAP_SESSION_STATUS_GET
} ste_uicc_rsp_sap_t;

/* SAP indications to clients */
typedef enum {
    STE_UICC_SAP_SESSION_RESET_IND = (STE_UICC_RANGE_IND_SAP | 0x0001),
    STE_UICC_SAP_SESSION_STATUS_IND,
    STE_UICC_SAP_SESSION_SAP_READY_IND
} ste_uicc_sap_session_t;

/* SAP's definitions end */
#endif
