/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <asyncflash_types.idt>

interface asyncflash.api.request
{
    void getSupportedFlashModes(void* pReqStruct);
    void getFlashModeDetails(void* pReqStruct);
    void enableFlashMode(void* pReqStruct);
    void configureFlashMode(void* pReqStruct);
    void strobe(void* pReqStruct);
    void getStatus(void* pReqStruct);
    void getXenonLifeCounter(void* pReqStruct);
    void getSupportedSelfTests(void* pReqStruct);
    void getFaultRegisters(void* pReqStruct);
    void doSelfTest(void* pReqStruct);
    void getNVM(void* pReqStruct);
}
