/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <asyncflash_types.idt>

interface asyncflash.api.response
{
    void asyncFlashSelfTestResult(t_sint32 res);
    void asyncFlashReturnCode(t_sint32 ret);
}
