#-------------------------------
# Default Config
#-------------------------------
include $(MM_MAKEFILES_DIR)/SharedConfig.mk


INSTALL_HEADER= TraceObject.h

todo: install

include $(MM_MAKEFILES_DIR)/SharedRules.mk

test cleantest:
	@echo No Test...
