/*
 * Copyright (C) ST-Ericsson SA 2012. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef __DSIL_REGS_H__
#define __DSIL_REGS_H__

#define DSI_VAL2REG(__reg, __fld, __val) \
	(((__val) << __reg##_##__fld##_SHIFT) & __reg##_##__fld##_MASK)
#define DSI_REG2VAL(__reg, __fld, __val) \
	(((__val) & __reg##_##__fld##_MASK) >> __reg##_##__fld##_SHIFT)

#define DSI_MCTL_MAIN_DATA_CTL 0x00000004
#define DSI_MCTL_MAIN_DATA_CTL_LINK_EN_SHIFT 0
#define DSI_MCTL_MAIN_DATA_CTL_LINK_EN_MASK 0x00000001
#define DSI_MCTL_MAIN_DATA_CTL_REG_TE_EN_SHIFT 7
#define DSI_MCTL_MAIN_DATA_CTL_REG_TE_EN_MASK 0x00000080
#define DSI_MCTL_MAIN_DATA_CTL_REG_TE_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_DATA_CTL, REG_TE_EN, __x)
#define DSI_MCTL_MAIN_DATA_CTL_READ_EN_SHIFT 8
#define DSI_MCTL_MAIN_DATA_CTL_READ_EN_MASK 0x00000100
#define DSI_MCTL_MAIN_DATA_CTL_READ_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_DATA_CTL, READ_EN, __x)
#define DSI_MCTL_MAIN_DATA_CTL_BTA_EN_SHIFT 9
#define DSI_MCTL_MAIN_DATA_CTL_BTA_EN_MASK 0x00000200
#define DSI_MCTL_MAIN_DATA_CTL_BTA_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_DATA_CTL, BTA_EN, __x)
#define DSI_MCTL_MAIN_DATA_CTL_DLX_REMAP_EN_SHIFT 14
#define DSI_MCTL_MAIN_DATA_CTL_DLX_REMAP_EN_MASK 0x00004000
#define DSI_MCTL_MAIN_DATA_CTL_DLX_REMAP_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_DATA_CTL, DLX_REMAP_EN, __x)
#define DSI_MCTL_MAIN_PHY_CTL 0x00000008
#define DSI_MCTL_MAIN_PHY_CTL_LANE2_EN_SHIFT 0
#define DSI_MCTL_MAIN_PHY_CTL_LANE2_EN_MASK 0x00000001
#define DSI_MCTL_MAIN_PHY_CTL_LANE2_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_PHY_CTL, LANE2_EN, __x)
#define DSI_MCTL_MAIN_PHY_CTL_CLK_CONTINUOUS_SHIFT 2
#define DSI_MCTL_MAIN_PHY_CTL_CLK_CONTINUOUS_MASK 0x00000004
#define DSI_MCTL_MAIN_PHY_CTL_CLK_CONTINUOUS(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_PHY_CTL, CLK_CONTINUOUS, __x)
#define DSI_MCTL_MAIN_PHY_CTL_WAIT_BURST_TIME_SHIFT 6
#define DSI_MCTL_MAIN_PHY_CTL_WAIT_BURST_TIME_MASK 0x000003C0
#define DSI_MCTL_MAIN_PHY_CTL_WAIT_BURST_TIME(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_PHY_CTL, WAIT_BURST_TIME, __x)
#define DSI_MCTL_DPHY_TIMEOUT 0x00000014
#define DSI_MCTL_DPHY_TIMEOUT_CLK_DIV_SHIFT 0
#define DSI_MCTL_DPHY_TIMEOUT_CLK_DIV_MASK 0x0000000F
#define DSI_MCTL_DPHY_TIMEOUT_CLK_DIV(__x) \
	DSI_VAL2REG(DSI_MCTL_DPHY_TIMEOUT, CLK_DIV, __x)
#define DSI_MCTL_DPHY_TIMEOUT_HSTX_TO_VAL_SHIFT 4
#define DSI_MCTL_DPHY_TIMEOUT_HSTX_TO_VAL_MASK 0x0003FFF0
#define DSI_MCTL_DPHY_TIMEOUT_HSTX_TO_VAL(__x) \
	DSI_VAL2REG(DSI_MCTL_DPHY_TIMEOUT, HSTX_TO_VAL, __x)
#define DSI_MCTL_DPHY_TIMEOUT_LPRX_TO_VAL_SHIFT 18
#define DSI_MCTL_DPHY_TIMEOUT_LPRX_TO_VAL_MASK 0xFFFC0000
#define DSI_MCTL_DPHY_TIMEOUT_LPRX_TO_VAL(__x) \
	DSI_VAL2REG(DSI_MCTL_DPHY_TIMEOUT, LPRX_TO_VAL, __x)
#define DSI_MCTL_ULPOUT_TIME 0x00000018
#define DSI_MCTL_ULPOUT_TIME_CKLANE_ULPOUT_TIME_SHIFT 0
#define DSI_MCTL_ULPOUT_TIME_CKLANE_ULPOUT_TIME_MASK 0x000001FF
#define DSI_MCTL_ULPOUT_TIME_CKLANE_ULPOUT_TIME(__x) \
	DSI_VAL2REG(DSI_MCTL_ULPOUT_TIME, CKLANE_ULPOUT_TIME, __x)
#define DSI_MCTL_ULPOUT_TIME_DATA_ULPOUT_TIME_SHIFT 9
#define DSI_MCTL_ULPOUT_TIME_DATA_ULPOUT_TIME_MASK 0x0003FE00
#define DSI_MCTL_ULPOUT_TIME_DATA_ULPOUT_TIME(__x) \
	DSI_VAL2REG(DSI_MCTL_ULPOUT_TIME, DATA_ULPOUT_TIME, __x)
#define DSI_MCTL_DPHY_STATIC 0x0000001C
#define DSI_MCTL_DPHY_STATIC_UI_X4_SHIFT 6
#define DSI_MCTL_DPHY_STATIC_UI_X4_MASK 0x00000FC0
#define DSI_MCTL_DPHY_STATIC_UI_X4(__x) \
	DSI_VAL2REG(DSI_MCTL_DPHY_STATIC, UI_X4, __x)
#define DSI_MCTL_MAIN_EN 0x00000020
#define DSI_MCTL_MAIN_EN_PLL_START_SHIFT 0
#define DSI_MCTL_MAIN_EN_PLL_START_MASK 0x00000001
#define DSI_MCTL_MAIN_EN_PLL_START(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, PLL_START, __x)
#define DSI_MCTL_MAIN_EN_CKLANE_EN_SHIFT 3
#define DSI_MCTL_MAIN_EN_CKLANE_EN_MASK 0x00000008
#define DSI_MCTL_MAIN_EN_CKLANE_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, CKLANE_EN, __x)
#define DSI_MCTL_MAIN_EN_DAT1_EN_SHIFT 4
#define DSI_MCTL_MAIN_EN_DAT1_EN_MASK 0x00000010
#define DSI_MCTL_MAIN_EN_DAT1_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, DAT1_EN, __x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS 0x00000064
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_WRITE 0
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_SHIFT 0
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_MASK 0x00000007
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_DCS_SHORT_WRITE_0 5
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_DCS_SHORT_WRITE_1 21
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_DCS_LONG_WRITE 57
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LONGNOTSHORT_SHIFT 3
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LONGNOTSHORT_MASK 0x00000008
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LONGNOTSHORT(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_LONGNOTSHORT, __x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_ID_SHIFT 14
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_ID_MASK 0x0000C000
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_ID(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_ID, __x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_SIZE_SHIFT 16
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_SIZE_MASK 0x001F0000
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_SIZE(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_SIZE, __x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LP_EN_SHIFT 21
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LP_EN_MASK 0x00200000
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_LP_EN(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_LP_EN, __x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_ENUM(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_NAT, \
	DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_##__x)
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_SHIFT 8
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_MASK 0x00003F00
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_ENUM(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_MAIN_SETTINGS, CMD_HEAD, \
	DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_##__x)
#define DSI_DIRECT_CMD_WRDAT0 0x00000070
#define DSI_DIRECT_CMD_WRDAT0_WRDAT0_SHIFT 0
#define DSI_DIRECT_CMD_WRDAT0_WRDAT0_MASK 0x000000FF
#define DSI_DIRECT_CMD_WRDAT0_WRDAT0(__x) \
	DSI_VAL2REG(DSI_DIRECT_CMD_WRDAT0, WRDAT0, __x)
#define DSI_DIRECT_CMD_WRDAT1 0x00000074
#define DSI_DIRECT_CMD_WRDAT2 0x00000078
#define DSI_DIRECT_CMD_WRDAT3 0x0000007C
#define DSI_DIRECT_CMD_STS_CLR 0x00000118
#define DSI_DIRECT_CMD_SEND 0x00000060
#define DSI_CMD_MODE_STS_CLR 0x00000114
#define DSI_DPHY_LANES_TRIM 0x00000150
#define DSI_DPHY_LANES_TRIM_DPHY_SPECS_90_81B_0_90 1
#define DSI_DPHY_LANES_TRIM_DPHY_SPECS_90_81B_SHIFT 12
#define DSI_DPHY_LANES_TRIM_DPHY_SPECS_90_81B_MASK 0x00001000
#define DSI_DPHY_LANES_TRIM_DPHY_SPECS_90_81B_ENUM(__x) \
	DSI_VAL2REG(DSI_DPHY_LANES_TRIM, DPHY_SPECS_90_81B, \
	DSI_DPHY_LANES_TRIM_DPHY_SPECS_90_81B_##__x)
#define DSI_CMD_MODE_CTL 0x00000050
#define DSI_CMD_MODE_CTL_ARB_MODE_MASK 0x00000040
#define DSI_CMD_MODE_CTL_ARB_MODE_SHIFT 6
#define DSI_CMD_MODE_CTL_ARB_PRI_MASK 0x00000080
#define DSI_CMD_MODE_CTL_ARB_PRI_SHIFT 7
#define DSI_MCTL_MAIN_EN_DAT2_EN_SHIFT 5
#define DSI_MCTL_MAIN_EN_DAT2_EN_MASK 0x00000020
#define DSI_MCTL_MAIN_EN_DAT2_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, DAT2_EN, __x)
#define DSI_MCTL_MAIN_EN_IF1_EN_SHIFT 9
#define DSI_MCTL_MAIN_EN_IF1_EN_MASK 0x00000200
#define DSI_MCTL_MAIN_EN_IF1_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, IF1_EN, __x)
#define DSI_MCTL_MAIN_EN_IF2_EN_SHIFT 10
#define DSI_MCTL_MAIN_EN_IF2_EN_MASK 0x00000400
#define DSI_MCTL_MAIN_EN_IF2_EN(__x) \
	DSI_VAL2REG(DSI_MCTL_MAIN_EN, IF2_EN, __x)
#define DSI_MCTL_MAIN_STS 0x00000024
#define DSI_MCTL_MAIN_STS_CLKLANE_READY_MASK 0x00000002
#define DSI_MCTL_MAIN_STS_CLKLANE_READY_SHIFT 1
#define DSI_MCTL_MAIN_STS_DAT1_READY_SHIFT 2
#define DSI_MCTL_MAIN_STS_DAT1_READY_MASK 0x00000004
#define DSI_MCTL_MAIN_STS_DAT2_READY_SHIFT 3
#define DSI_MCTL_MAIN_STS_DAT2_READY_MASK 0x00000008
#define DSI_CMD_MODE_CTL_IF1_ID_SHIFT 0
#define DSI_CMD_MODE_CTL_IF1_ID_MASK 0x00000003
#define DSI_CMD_MODE_CTL_IF2_ID_SHIFT 2
#define DSI_CMD_MODE_CTL_IF2_ID_MASK 0x0000000C
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_NAT_READ 1
#define DSI_DIRECT_CMD_MAIN_SETTINGS_CMD_HEAD_DCS_READ 6
#define DSI_DIRECT_CMD_RD_STS_CLR 0x0000011C
#define DSI_DIRECT_CMD_STS 0x00000068
#define DSI_DIRECT_CMD_STS_READ_COMPLETED_WITH_ERR_SHIFT 10
#define DSI_DIRECT_CMD_STS_READ_COMPLETED_WITH_ERR_MASK 0x00000400
#define DSI_DIRECT_CMD_STS_READ_COMPLETED_SHIFT 3
#define DSI_DIRECT_CMD_STS_READ_COMPLETED_MASK 0x00000008
#define DSI_DIRECT_CMD_STS_WRITE_COMPLETED_SHIFT 1
#define DSI_DIRECT_CMD_STS_WRITE_COMPLETED_MASK 0x00000002
#define DSI_DIRECT_CMD_STS_FLAG 0x00000138
#define DSI_DIRECT_CMD_STS_ACKNOWLEDGE_WITH_ERR_RECEIVED_SHIFT 5
#define DSI_DIRECT_CMD_STS_ACKNOWLEDGE_WITH_ERR_RECEIVED_MASK 0x00000020
#define DSI_DIRECT_CMD_STS_ACK_VAL_SHIFT 16
#define DSI_DIRECT_CMD_STS_ACK_VAL_MASK 0xFFFF0000
#define DSI_DIRECT_CMD_RD_PROPERTY 0x00000084
#define DSI_DIRECT_CMD_RD_PROPERTY_RD_SIZE_SHIFT 0
#define DSI_DIRECT_CMD_RD_PROPERTY_RD_SIZE_MASK 0x0000FFFF
#define DSI_DIRECT_CMD_RDDAT 0x00000080
#define DSI_MCTL_MAIN_DATA_CTL_HOST_EOT_GEN_SHIFT 12
#define DSI_MCTL_MAIN_DATA_CTL_HOST_EOT_GEN_MASK 0x00001000

#endif /* __DSIL_REGS_H__ */
