/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

//#define LOCAL_OST_TRACE_EVENT

#ifdef LOCAL_OST_TRACE_EVENT

void MeasureEventInit(void);
void MeasureEventStart0(t_uint32 aTraceName,char	* aEventName);
void MeasureEventStop(t_uint32 aTraceName,char *aEventName);
void MeasureDelta(t_uint32 aTraceName,char *aEventName,t_uint32 duaration);
void MeasureEventDisplayStatus(void);
#else

//filtered 

#define  MeasureEventInit()
#define MeasureEventStart0(A,B)
#define MeasureEventStop(A,B)
#define MeasureEventDisplayStatus()
#define MeasureDelta(A,B,C);


#endif

enum  { TRACE_EVENT_BUFFER_START=0, TRACE_EVENT_HW_START,TRACE_EVENT_FINDNEXTNAL_START,TRACE_EVENT_HAMACPHYSICALL_START,TRACE_EVENT_NONVCL_START,TRACE_EVENT_ALLOC_START,TRACE_EVENT_PARSER_START,TRACE_EVENT_CACHECLEAN_START,TRACE_EVENT_PROCESSALLSLICES_START,TRACE_EVENT_1_START,TRACE_EVENT_2_START,TRACE_EVENT_3_START,TRACE_EVENT_FILLPARAMIN_START,TRACE_EVENT_COMPUTE_START,TRACE_DELTA_SVA,TRACE_EVENT_CALIBRATION_START} ;
#define TRACE_EVENT_CALIBRATION_STOP	TRACE_EVENT_CALIBRATION_START
#define TRACE_EVENT_BUFFER_STOP			TRACE_EVENT_BUFFER_START
#define TRACE_EVENT_FINDNEXTNAL_STOP 	TRACE_EVENT_FINDNEXTNAL_START
#define TRACE_EVENT_HW_STOP				TRACE_EVENT_HW_START
#define TRACE_EVENT_HAMACPHYSICALL_STOP	TRACE_EVENT_HAMACPHYSICALL_START
#define  TRACE_EVENT_NONVCL_STOP		TRACE_EVENT_NONVCL_START
#define  TRACE_EVENT_ALLOC_STOP			 TRACE_EVENT_ALLOC_START
#define  TRACE_EVENT_PARSER_STOP		TRACE_EVENT_PARSER_START
#define	TRACE_EVENT_CACHECLEAN_STOP		TRACE_EVENT_CACHECLEAN_START
#define TRACE_EVENT_PROCESSALLSLICES_STOP	TRACE_EVENT_PROCESSALLSLICES_START
#define	TRACE_EVENT_1_STOP					TRACE_EVENT_1_START
#define	TRACE_EVENT_2_STOP					TRACE_EVENT_2_START
#define	TRACE_EVENT_3_STOP					TRACE_EVENT_3_START
#define	TRACE_EVENT_FILLPARAMIN_STOP	TRACE_EVENT_FILLPARAMIN_START
#define	TRACE_EVENT_COMPUTE_STOP	TRACE_EVENT_COMPUTE_START
