BUILD_MMDSP_PROC_imaging/sw3A=bin
NO_STD_BUILD_imaging/sw3A=1
BUILD_MMDSP_NMF_imaging/sw3A=bin
BUILD_ARM_PROC_imaging/sw3A=bin
BUILD_ARM_CODE_imaging/sw3A=bin
BUILD_ARM_NMF_imaging/sw3A=bin
BUILD_XP70_SIA_CODE_imaging/sw3A=false
