BUILD_MMDSP_PROC_imaging/ext_sia_hw_components_8500=bin
NO_STD_BUILD_imaging/ext_sia_hw_components_8500=1
BUILD_MMDSP_NMF_imaging/ext_sia_hw_components_8500=bin
BUILD_ARM_PROC_imaging/ext_sia_hw_components_8500=bin
BUILD_ARM_CODE_imaging/ext_sia_hw_components_8500=bin
BUILD_ARM_NMF_imaging/ext_sia_hw_components_8500=bin
BUILD_XP70_SIA_CODE_imaging/ext_sia_hw_components_8500=false
