BUILD_MMDSP_PROC_audio/aacenc=bin
NO_STD_BUILD_audio/aacenc=1
BUILD_MMDSP_NMF_audio/aacenc=bin
BUILD_ARM_PROC_audio/aacenc=bin
BUILD_ARM_CODE_audio/aacenc=src
BUILD_ARM_NMF_audio/aacenc=src
BUILD_XP70_SIA_CODE_audio/aacenc=false
