/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

/*****************************************************************************/
/**
 * This is a Nomadik Multiprocessing Framework generated file, please do not modify it.
 */

/* Generated ispctl_types.idt defined type */
#if !defined(_ispctl_type_idt)
#define _ispctl_type_idt


#define ISPCTL_SIZE_TAB_PE 64

#define ISP_SIZE_OF_ITM_REGISTERS 128

#define XP70_NO_ACK_INT 0x0UL

#define XP70_HOST_COMMS_READY 0x1UL

#define XP70_HOST_COMMS_OPERATION_COMPLETE 0x2UL

#define XP70_BOOT_COMPLETE 0x4UL

#define XP70_SLEEPING 0x8UL

#define XP70_WORKEN_UP 0x10UL

#define XP70_ISP_STREAMING 0x20UL

#define XP70_ISP_STOP_STREAMING 0x40UL

#define XP70_SENSOR_STOP_STREAMING 0x80UL

#define XP70_SENSOR_START_STREAMING 0x100UL

#define XP70_ISP_LOAD_READY 0x200UL

#define XP70_ZOOM_CONFIG_REQUEST_DENIED 0x400UL

#define XP70_ZOOM_CONFIG_REPROGRAM_REQUIRED 0x800UL

#define XP70_ZOOM_STEP_COMPLETE 0x1000UL

#define XP70_ZOOM_SET_OUT_OF_RANGE 0x2000UL

#define XP70_STREAMING_ERROR 0x4000UL

#define XP70_ISP_RESET_COMPLETE 0x8000UL

#define XP70_MASTER_I2C_ACCESS_FAILURE 0x10000UL

#define XP70_GLACE_STATS_READY 0x20000UL

#define XP70_HISTOGRAM_STATS_READY 0x40000UL

#define XP70_EXPOSURE_AND_WB_PARAMETERS_UPDATED 0x80000UL

#define XP70_AUTOFOCUS_STATS_READY 0x100000UL

#define XP70_FLADRIVER_LENS_STOP 0x200000UL

#define XP70_ZOOM_OUTPUT_IMAGE_RESOLUTION_READY 0x400000UL

#define XP70_COLOUR_MATRIX_PIPE0_UPDATE_COMPLETE 0x800000UL

#define XP70_COLOUR_MATRIX_PIPE1_UPDATE_COMPLETE 0x1000000UL

#define XP70_SDL_UPDATE_READY 0x2000000UL

#define XP70_NVM_EXPORT_DONE 0x4000000UL

#define XP70_CDCC_AVAILABLE 0x8000000UL

#define XP70_POWER_NOTIFICATION 0x10000000UL

#define XP70_SMS_NOTIFICATION 0x20000000UL

#define XP70_SENSOR_OUTPUT_MODE_EXPORT_NOTIFICATION 0x40000000UL

#define XP70_VALID_BMS_FRAME_NOTIFICATION 0x80000000UL

#define XP70_HOST_TO_SENSOR_ACCESS_COMPLETE 0x1UL

#define XP70_SENSOR_COMMIT_NOTIFICATION 0x2UL

#define XP70_ISP_COMMIT_NOTIFICATION 0x4UL

#define XP70_HR_GAMMA_UPDATE_COMPLETE 0x8UL

#define XP70_LR_GAMMA_UPDATE_COMPLETE 0x10UL

#define XP70_FLASH_LIT_FRAME 0x1UL

#define CSI2_NULL 0x10

#define CSI2_BLKD 0x11

#define CSI2_EMBD_8BIT 0x12

#define CSI2_RAW6 0x28

#define CSI2_RAW7 0x29

#define CSI2_RAW8 0x2A

#define CSI2_RAW10 0x2B

#define CSI2_RAW12 0x2C

#define CSI2_RAW14 0x2D

enum e_ispctlInfo {
  ISP_INF_NONE=0x0,
  ISP_READ_DONE=0x1,
  ISP_WRITE_DONE=0x2,
  ISP_INIT_DONE=0x3,
  ISP_READLIST_DONE=0x4,
  ISP_WRITELIST_DONE=0x5,
  ISP_POLLING_PE_VALUE_DONE=0x6,
  ISP_HOST_COMMS_READY=0x7,
  ISP_BOOT_COMPLETE=0x8,
  ISP_SLEEPING=0x9,
  ISP_WOKEN_UP=0xA,
  ISP_STREAMING=0xB,
  ISP_STOP_STREAMING=0xC,
  ISP_SENSOR_START_STREAMING=0xD,
  ISP_SENSOR_STOP_STREAMING=0xE,
  ISP_HOST_TO_SENSOR_ACCESS_COMPLETE=0xF,
  ISP_LOAD_READY=0x10,
  ISP_ZOOM_CONFIG_REQUEST_DENIED=0x11,
  ISP_ZOOM_CONFIG_REPROGRAM_REQUIRED=0x12,
  ISP_ZOOM_STEP_COMPLETE=0x13,
  ISP_ZOOM_SET_OUT_OF_RANGE=0x14,
  ISP_RESET_COMPLETE=0x15,
  ISP_GLACE_STATS_READY=0x16,
  ISP_HISTOGRAM_STATS_READY=0x17,
  ISP_EXPOSURE_AND_WB_PARAMETERS_UPDATED=0x18,
  ISP_AUTOFOCUS_STATS_READY=0x19,
  ISP_FLADRIVER_LENS_STOP=0x20,
  ISP_ZOOM_OUTPUT_IMAGE_RESOLUTION_READY=0x21,
  ISP_COLOUR_MATRIX_PIPE0_UPDATE_COMPLETE=0x22,
  ISP_COLOUR_MATRIX_PIPE1_UPDATE_COMPLETE=0x23,
  ISP_SDL_UPDATE_READY=0x24,
  ISP_NVM_EXPORT_DONE=0x25,
  ISP_CDCC_AVAILABLE=0x26,
  ISP_POWER_NOTIFICATION=0x27,
  ISP_SMS_NOTIFICATION=0x28,
  ISP_SENSOR_OUTPUT_MODE_EXPORT_NOTIFICATION=0x29,
  ISP_VALID_BMS_FRAME_NOTIFICATION=0x30,
  ISP_SENSOR_COMMIT_NOTIFICATION=0x31,
  ISP_ISP_COMMIT_NOTIFICATION=0x32,
  ISP_LR_GAMMA_UPDATE_COMPLETE=0x33,
  ISP_HR_GAMMA_UPDATE_COMPLETE=0x34,
  ISP_DEBUG_MODE_ON=0x777,
  ISP_DEBUG_MODE_OFF=0x0FF,
  UNKNOWN_INFO=0x1000};

enum e_ispctlError {
  ISP_NO_ERROR=0x0,
  ISP_POLLING_TIMEOUT_ERROR=0x1,
  ISP_CHECK_VALUE_ERROR=0x2,
  ISP_FORBIDDEN_STATE_TRANSITION_ERROR=0x4,
  ISP_READ_ONLY_ERROR=0x8,
  ISP_READ_ONLY_IN_LIST_ERROR=0x10,
  ISP_WRITELIST_NOT_DONE_OUT_OF_BOUNDARY_ERROR=0x20,
  ISP_READLIST_NOT_DONE_OUT_OF_BOUNDARY_ERROR=0x40,
  ISP_SENSOR_TYPE_NOT_DEFINED_ERROR=0x80,
  ISP_STREAMING_ERROR=0x1000,
  ISP_DOES_NOT_RESPOND_ERROR=0x4000,
  ISP_MASTER_I2C_ACCESS_FAILURE=0x200,
  ISP_ALREADY_IN_PROCESSING_ERROR=0x100,
  ISP_BOOTING_ERROR=0xA,
  ISP_READING_ERROR=0xB,
  ISP_WRITING_ERROR=0xC,
  ISP_POLLING_ERROR=0xD};

enum e_ispctlDebug {
  ISPDBG_REGVALUE=0x1,
  ISPDBG_POLLING_TIMEOUT_HANDLER_CALLED=0x19,
  ISPDBG_PANIC_HANDLER_CALLED=0x20,
  ISPDBG_ITM0_HANDLER_CALLED=0x21,
  ISPDBG_ITM1_HANDLER_CALLED=0x22,
  ISPDBG_ITM2_HANDLER_CALLED=0x23,
  ISPDBG_SUBSCRIBE_METHOD=0x24,
  ISPDBG_UNSUBSCRIBE_METHOD=0x25,
  ISPDBG_WRITELIST_METHOD=0x26,
  ISPDBG_WRITE_METHOD=0x27,
  ISPDBG_READLIST_METHOD=0x28,
  ISPDBG_READ_METHOD=0x29,
  ISPDBG_WAITEXPECTEDPEVALUE_METHOD=0x2A,
  ISPDBG_INITISP_METHOD=0x2B};

struct s_PageElement {
  t_uint16 pe_addr;
  t_uint32 pe_data;
};

typedef enum t_xyuv_t_eSignal {
  INIT_STATE_SIG=1,
  ISP_REG_WRITTEN_SIG,
  ISP_REG_READ_SIG,
  ISP_HOST_COMM_READY_SIG} t_eSignal;

typedef enum t_xyuv_t_eStateId {
  ISP_RESET_STATE_ID=0x0,
  ISP_BOOTING_STATE_ID=0x1,
  ISP_POLLING_STATE_ID=0x8,
  ISP_WRITING_STATE_ID=0x10,
  ISP_READING_STATE_ID=0x20} t_eStateId;

typedef struct s_PageElement ts_PageElement;

#endif
