BUILD_MMDSP_PROC_audio/audiolibs=bin
NO_STD_BUILD_audio/audiolibs=1
BUILD_MMDSP_NMF_audio/audiolibs=bin
BUILD_ARM_PROC_audio/audiolibs=bin
BUILD_ARM_CODE_audio/audiolibs=src
BUILD_ARM_NMF_audio/audiolibs=src
BUILD_XP70_SIA_CODE_audio/audiolibs=false
