#!/bin/bash

out_error()
{
	echo ""
	echo -e "\033[1;31mOption not or not yet available\033[0m"
	exit
}

export SCRIPTPATH="./scripts"
export CONFIGPATH=$SCRIPTPATH/ux500/u5500

# Check if all eviroment variables is set before running script
if [ "$T32SYS" == '' ] || [ "$T32TMP" == '' ] || [ "$(which t32marm)" == '' ]; then
	echo
	echo "You need to set the following enviroment variables:"
	echo -e "\033[1m\$T32SYS:\033[0m To point to the install directory for Trace32"
	echo -e "\033[1m\$T32TMP:\033[0m To a directory where you have write access"
	echo -e "\033[1m\$PATH:\033[0m    Add the path to t32marm"
	echo
	echo "More info can be found in the README file"
	echo
	exit
fi

# Check if License file is specified using $T32LICENSE, replace in all config files.
if [ "$T32LICENSE" != "" ]; then
	for f in $CONFIGPATH/config*.t32; do
		if ! grep -q LICENSE=$T32LICENSE $f; then
			#delete old LICENSE Line
			perl -i -nle 'print if !/^LICENSE\b/' $f
			#add LICENSE line
			echo LICENSE=$T32LICENSE >> $f
		fi
	done
fi

# What to debug?
if [[ $1 -ge 1 ]] && [ $1 -le 3 ]; then
	choice=$1
else
	echo "Please select platform:"
	echo -e "\033[1m#   Chip          Core              Comment\033[0m"
	echo -e "\033[1m1\033[0m:  U5500_V2      APP"
	echo -e "\033[1m2\033[0m:  U5500_V2      APP+ACC"
	echo -e "\033[1m3\033[0m:  U5500_V2      APP+ACC+CEVA"

	# read user input
	read choice
fi

# Not yet supported for U5500
#if [[ $2 -ge 1 ]] && [ $2 -le 2 ]; then
#	simu=$2
#else
#	echo "Please select mode:"
#	echo -e "\033[1m#   Mode\033[0m"
#	echo -e "\033[1m1\033[0m:  ICD"
#	echo -e "\033[1m2\033[0m:  Simulator"

	# read user input
#	read simu
#fi


#if [[ $simu = 1 ]] ; then
#	SIM=""
#elif [[ $simu = 2 ]] ; then
#	SIM="_sim"
#else
#	SIM=""
#fi
SIM=""

# Start t32marm and call config and init script.
if [[ $choice = 1 ]] ; then
	echo "Debugging: [U5500-V2_APP]"
	t32marm -c $CONFIGPATH/config_app$SIM.t32,$SCRIPTPATH/init.cmm [U5500_APP] &
elif [[ $choice = 2 ]] ; then
	echo "Debugging: [U5500-V2_APP+ACC]"
	t32marm -c $CONFIGPATH/config_app$SIM.t32,$SCRIPTPATH/init.cmm [U5500_APP] &
	sleep 5s
	t32marm -c $CONFIGPATH/config_acc$SIM.t32,$SCRIPTPATH/init.cmm [U5500_ACC] &
elif [[ $choice = 3 ]] ; then
	echo "Debugging: [U5500-V2_APP+ACC+CEVA]"
	t32marm -c $CONFIGPATH/config_app$SIM.t32,$SCRIPTPATH/init.cmm [U5500_APP] &	
	sleep 5s
	t32marm -c $CONFIGPATH/config_acc$SIM.t32,$SCRIPTPATH/init.cmm [U5500_ACC] &
	sleep 1s
	t32marm -c $CONFIGPATH/config_ceva$SIM.t32,$SCRIPTPATH/init.cmm [U5500_CEVA] &
else
	echo "Debugging: Default platform [U5500-V2_APP]"
	t32marm -c $CONFIGPATH/config_app$SIM.t32,$SCRIPTPATH/init.cmm [U5500_APP] &
fi

