//#include <t1xhv_common.idt>
//#include <t1xhv_vdc_h264.idt>

interface h264dec.arm_nmf.api.algo {

void configureAlgo(	t_uint32	cb,
					t_uint32 addr_in_frame_buffer,
					t_uint32 addr_out_frame_buffer,
					t_uint32 addr_internal_buffer,
					t_uint32 addr_in_bitstream_buffer,
					t_uint32 addr_out_bitstream_buffer,
					t_uint32 addr_in_parameters,
					t_uint32 addr_out_parameters,
					t_uint32 addr_in_frame_parameters,
					t_uint32 addr_out_frame_parameters);

}
