#include <arm_codec_type.idt>
#include <frameinfo.idt>
#include <VFM_Memory.idt>

interface h264dec.arm_nmf.api.get_config {

void get_config(t_frameinfo frame_info);
void get_memory(VFM_MemoryStatus memory_status);

}
