// Common interface between splitter and decoder 
#include <arm_codec_type.idt>

interface h264dec.arm_nmf.api.nal_handshake {

void nal_handshake(t_handshake mode,t_bit_buffer *p_b);
void fatal_decoding_error(t_uint16 error_code);
}
