 // Common interface between splitter and decoder 
#include <arm_codec_type.idt>
#include <frameinfo.idt>

interface h264dec.arm_nmf.api.picture {

void picture(t_picture_output valid, t_uint16 *p_fb, t_uint32 nFlags, t_frameinfo info);

}
