/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler */

#ifndef _Included_com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler
#define _Included_com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler
 * Method:    initJNILayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler_initJNILayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler
 * Method:    getAvailablePorts
 * Signature: ()[Lcom/stericsson/sdk/equipment/io/uart/internal/SerialPort;
 */
JNIEXPORT jobjectArray JNICALL Java_com_stericsson_sdk_equipment_io_uart_internal_SerialPortHandler_getAvailablePorts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}

#endif
#endif
