/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 *
 * \brief   interface function declaration 
 * \author  ST-Ericsson
 */

#include <t1xhv_common.idt>
#include <t1xhv_vec_mpeg4.idt>

interface mpeg4enc.arm_nmf.api.algo { 


void configureAlgo(	t_uint32 addr_in_frame_buffer,
					t_uint32 addr_out_frame_buffer,
					t_uint32 addr_internal_buffer,
					t_uint32 addr_in_header_buffer,
					t_uint32 addr_in_bitstream_buffer,
					t_uint32 addr_out_bitstream_buffer,
					t_uint32 addr_in_parameters,
					t_uint32 addr_out_parameters,
					t_uint32 addr_in_frame_parameters,
					t_uint32 addr_out_frame_parameters);

void controlAlgo(t_t1xhv_command command, t_uint16 channelNumber, t_uint16 param);

void setDebug(t_t1xhv_debug_mode mode, t_uint32 param1, t_uint32 param2);
} // interface mpeg4dec_sw.mpc.api.algo

