/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 *
 * \brief   Contains the source for the development of OMX mpeg4enc video component
 * \author  ST-Ericsson
 */
interface mpeg4enc.arm_nmf.api.setCropForStab {
void setCropForStab(t_uint32 crop_left_offset, t_uint32 crop_top_offset, t_uint32 overscan_width, t_uint32 overscan_height);
}