/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <t1xhv_common.idt>
#include <t1xhv_vec_mpeg4.idt>
#include <vfm_common.idt>

interface mpeg4enc.arm_nmf.api.setParam {
void setParameter(t_t1xhv_algo_id algoId, ts_ddep_buffer_descriptor ddep_vec_mpeg4_param_desc);
}
