#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedNmfConfig.mk

INSTALL_NMF_COMP_SRC_MMDSP= \
	$(OST_INC_AUTOGEN)/ens_interface_nmf_mpc_fsm_component_src_ComponentTraces.h \
	$(OST_INC_AUTOGEN)/ens_interface_nmf_mpc_fsm_component_src_PortTraces.h \
	$(OST_INC_AUTOGEN)/ENS_INTERFACE_nmf_mpc.xml

INSTALL_NMF_COMP_SRC_MMDSP_PREFIX:=ens_interface/

include $(MM_MAKEFILES_DIR)/SharedNmfRules.mk
