/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <fileio_types.idt>

interface fileio.api.error
{
    const char* errorCode2String(t_fileio_error err);
}
