/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <fileio_types.idt>

interface fileio.api.request
{
    void test();
    void size(const char* aFileName, t_uint32* aSizePtr);
    void read(const char* aFileName, void* aDestBuffer, t_uint32 aNumBytes);
    void write(const char* aFileName, const void* aSrcBuffer, t_uint32 aNumBytes);
}
