# -*- Mode: Makefile -*-
# vim:syntax=make:
NO_ARM11=1
NO_MMDSP=1
##NO_CA9=1
#include $(MM_MAKEFILES_DIR)/AudioDispatch.mk
include $(MM_MAKEFILES_DIR)/SharedCheck.mk

DIRECTORIES= include  libaac_core libaac_sbr standalone  libaacdec_algo_wrapper

include $(MM_MAKEFILES_DIR)/SharedDispatch.mk


