BUILD_MMDSP_PROC_imaging/tuningloader_api=bin
NO_STD_BUILD_imaging/tuningloader_api=1
BUILD_MMDSP_NMF_imaging/tuningloader_api=bin
BUILD_ARM_PROC_imaging/tuningloader_api=bin
BUILD_ARM_CODE_imaging/tuningloader_api=bin
BUILD_ARM_NMF_imaging/tuningloader_api=bin
BUILD_XP70_SIA_CODE_imaging/tuningloader_api=false
