/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 *
 * \brief   Contains the source for the development of OMX mpeg4enc video component
 * \author  ST-Ericsson
 *
 */

#include <vfm_common.idt>
#include <t1xhv_common.idt>
#include <t1xhv_vec_mpeg4.idt>

interface mpeg4enc.mpc.api.ddep {
void setConfig(t_uint16 channelId);
void setParameter(t_uint16 channelId, t_t1xhv_algo_id algoId, ts_ddep_buffer_descriptor ddep_vec_mpeg_param_desc);
void setNeeds(t_uint16 channelId,ts_ddep_buffer_descriptor bbm_desc, ts_ddep_buffer_descriptor debugBuffer_desc);
void setCropForStab(t_uint32 crop_left_offset, t_uint32 crop_top_offset, t_uint32 overscan_width, t_uint32 overscan_height);
void disableFWCodeexection(t_bool value);
}

