#include <t1xhv_common.idt>
#include <t1xhv_vdc_h264.idt>

interface h264dec.mpc.ddep.api.end_codec { 

/** @addtogroup h264decDdepEndCodecGroup endCodec
 *  @ingroup h264decDdepRequiredInterfaceGroup
 *  @{ 
 */
/*!
 Description : Report the end of a NMF ALGO component.
 \param[in]  status		    Status of the process done.
 \param[in]  info           Information on process completion.
                            \n It'll characterize the good job completion (STATUS_JOB_COMPLETE) : VDC_ERT_NONE.
                            \n or it'll indicate possible error sources if status is STATUS_JOB_ABORTED.

 \param[in]  durationInTicks  Duration (in SVA's timer ticks unit, i.e. 90kHz) of the algo process that have been done 
                            (i.e. between a CMD_START of the algo and its completion).
 *
 * \remarks	For the corresponding ITF server name(s), please refer to \ref h264decConfigurationGroup
 * 
 */

//void endCodec(t_t1xhv_status status, t_t1xhv_decoder_info info, t_uint32 durationInTicks);
//void endCodec(t_t1xhv_status status, t_uint32 info, t_uint32 durationInTicks);
void endCodec(t_uint32 status, t_uint32 info, t_uint32 durationInTicks);

/** @} */ // end of h264decDdepEndCodecGroup

}
