#include <t1xhv_common.idt>
#include <t1xhv_vdc_h264.idt>

interface h264dec.mpc.ddep.api.log_event { 

void eventEndAlgo();
void eventEndCabac(t_t1xhv_status status, t_t1xhv_decoder_info info, t_uint32 durationInTicks);
void eventInformResourceStatus();
void eventInformResourceStatusCabac();
}
