/*****************************************************************************/
/**
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
*/
/*****************************************************************************/
#ifndef _IMGCONFIG_H
#define _IMGCONFIG_H

#ifdef __SYMBIAN32__
#include "ImgSymbianConfig.h"
#else
#include "ImgSelectedConfig.h"
#endif

#define IMG_CONFIG_FALSE 0
#define IMG_CONFIG_TRUE  1

#if (IMG_CONFIG == 100)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     1
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_TRUE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE 	IMG_CONFIG_FALSE	
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM		    2
    #define IMG_CONFIG_SENSORNVM_READ		0
    #define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 101)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     1
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_TRUE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
	#define IMG_CONFIG_SW_PLATFORM		    2
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 102)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     1
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_TRUE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE	
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
	#define IMG_CONFIG_SW_PLATFORM			2
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 103)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     1
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_TRUE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
	#define IMG_CONFIG_SW_PLATFORM			2
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 200)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM    		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 201)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM			1
    #define IMG_CONFIG_SENSORNVM_READ		2
    #define IMG_CONFIG_NVM_PATH 	1
	
#endif

#if (IMG_CONFIG == 300)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM   		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
#endif

#if (IMG_CONFIG == 301)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_TRUE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_TRUE
    #define IMG_CONFIG_SW_PLATFORM 			1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
	
#endif

#if (IMG_CONFIG == 302)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_TRUE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_TRUE
    #define IMG_CONFIG_SW_PLATFORM     		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
#endif
#if (IMG_CONFIG == 303)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_TRUE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_TRUE
    #define IMG_CONFIG_SW_PLATFORM     		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
#endif
#if (IMG_CONFIG == 304)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_TRUE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_TRUE
    #define IMG_CONFIG_SW_PLATFORM     		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
#endif
#if (IMG_CONFIG == 305)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_TRUE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_TRUE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_TRUE
    #define IMG_CONFIG_SW_PLATFORM     		1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	0
#endif
#if (IMG_CONFIG == 400)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM			3
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 401)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM			3
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#if (IMG_CONFIG == 501)
    #define IMG_CONFIG_FLASH                1
    #define IMG_CONFIG_CUSTOMER_FEATURE     2
    #define IMG_CONFIG_EXIF_MAKER_NOTES     IMG_CONFIG_FALSE
    #define IMG_CONFIG_NVM_FROM_FILE        IMG_CONFIG_FALSE
    #define IMG_CONFIG_PREFLASH_USING_TORCHMODE		IMG_CONFIG_FALSE
    #define IMG_CONFIG_GSAMPLE_TUNING_ALGO  IMG_CONFIG_FALSE
    #define IMG_CONFIG_SW_PLATFORM			1
	#define IMG_CONFIG_SENSORNVM_READ		0
	#define IMG_CONFIG_NVM_PATH 	1
#endif

#endif /*_IMGCONFIG_H*/

//eof
