#!/bin/sh
case $1 in
    start)
    echo "Starting ab_listener..."
    ab_listener &
    echo "...done"
    ;;
    stop)
    echo "Stopping ab_listener..."
    killall ab_listener
    echo "...done"
    ;;
    *)
    echo "Usage:" >&2
    echo -e "\t$0 start" >&2
    echo -e "\t$0 stop" >&2
    ;;
esac
exit
