/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <buffer.idt>

interface mpeg2dec.mpc.api.fillthisheader {
void fillThisHeader(Buffer_p buffer);
}
