/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <t1xhv_common.idt>
#include <t1xhv_vdc_mpeg2.idt>

interface mpeg2dec.mpc.api.update_algo { 

/** @addtogroup mpeg2decUpdateAlgoGroup updateAlgo
 *  @ingroup mpeg2decProvidedInterfaceGroup
 *  @{
 */
/*!
 Description : (Not yet implemented) Update the configuration of a specific NMF algo component.
 *   
 * \remarks	For the corresponding ITF server name(s), please refer to \ref mpeg2decConfigurationGroup
 */ 
void updateAlgo(void);

/** @} */ // end of mpeg2decUpdateAlgoGroup
}
