
typedef enum {
  TRANSFERT_MTF_ONLY,
  TRANSFERT_MTF_HW_LOOP
} t_mtf_mode;

void mtfWriteTable(t_mtf_mode mode, t_uint32 addr_out, t_uint16 *pt_src, t_uint16 len, t_uint16 incr, t_uint16 swap_cfg);

void mtfReadTable(t_mtf_mode mode, t_uint32 addr_in, t_uint16 *pt_dest, t_uint16 len, t_uint16 incr,t_uint16 swap_cfg);