/*****************************************************************************/
/**
*  © ST-Ericsson, 2009 - All rights reserved
*  Reproduction and Communication of this document is strictly prohibited
*  unless specifically authorized in writing by ST-Ericsson
*
* \file
* \brief   resource_sharer "ping" interface type definition
* \author  ST-Ericsson
*/
/*****************************************************************************/



interface resource_sharer.api.lock {
    void Lock(t_uint16 requesterId);
}