/*****************************************************************************/
/**
*  © ST-Ericsson, 2009 - All rights reserved
*  Reproduction and Communication of this document is strictly prohibited
*  unless specifically authorized in writing by ST-Ericsson
*
* \file
* \brief   resource_sharer "ping" interface type definition
* \author  ST-Ericsson
*/
/*****************************************************************************/



interface resource_sharer.api.release {
/* parameter is useless, I put it to workaround a problem
   where NMF generates incorrect code for a function with no
   parameters in an interface collection */
/* also, name is capitalized to avoid conflict with interface
   name. Bugger */
    void Release(t_uint16 requesterId);
}