/*
 * LPP_PeriodicalReportingCriteria.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP_PDU-Definitions"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#include <asn_internal.h>

#include "LPP_PeriodicalReportingCriteria.h"

static int
reportingAmount_2_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
reportingAmount_2_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
reportingAmount_2_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
reportingAmount_2_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
reportingAmount_2_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
reportingAmount_2_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
reportingAmount_2_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
reportingAmount_2_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
reportingAmount_2_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
reportingAmount_2_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	reportingAmount_2_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
reportingInterval_11_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
reportingInterval_11_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
reportingInterval_11_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
reportingInterval_11_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
reportingInterval_11_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
reportingInterval_11_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
reportingInterval_11_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
reportingInterval_11_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
reportingInterval_11_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
reportingInterval_11_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	reportingInterval_11_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int asn_DFL_2_set_7(int set_value, void **sptr) {
	ENUMERATED_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 7 */
		return asn_long2INTEGER(st, 7);
	} else {
		/* Test default value 7 */
		long value;
		if(asn_INTEGER2long(st, &value))
			return -1;
		return (value == 7);
	}
}
static asn_INTEGER_enum_map_t asn_MAP_reportingAmount_value2enum_2[] = {
	{ 0,	3,	"ra1" },
	{ 1,	3,	"ra2" },
	{ 2,	3,	"ra4" },
	{ 3,	3,	"ra8" },
	{ 4,	4,	"ra16" },
	{ 5,	4,	"ra32" },
	{ 6,	4,	"ra64" },
	{ 7,	11,	"ra-Infinity" }
};
static unsigned int asn_MAP_reportingAmount_enum2value_2[] = {
	7,	/* ra-Infinity(7) */
	0,	/* ra1(0) */
	4,	/* ra16(4) */
	1,	/* ra2(1) */
	5,	/* ra32(5) */
	2,	/* ra4(2) */
	6,	/* ra64(6) */
	3	/* ra8(3) */
};
static asn_INTEGER_specifics_t asn_SPC_reportingAmount_specs_2 = {
	asn_MAP_reportingAmount_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_reportingAmount_enum2value_2,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1	/* Strict enumeration */
};
static ber_tlv_tag_t asn_DEF_reportingAmount_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static asn_per_constraints_t asn_PER_reportingAmount_constr_2 = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportingAmount_2 = {
	"reportingAmount",
	"reportingAmount",
	reportingAmount_2_free,
	reportingAmount_2_print,
	reportingAmount_2_constraint,
	reportingAmount_2_decode_ber,
	reportingAmount_2_encode_der,
	reportingAmount_2_decode_xer,
	reportingAmount_2_encode_xer,
	reportingAmount_2_decode_uper,
	reportingAmount_2_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_reportingAmount_tags_2,
	sizeof(asn_DEF_reportingAmount_tags_2)
		/sizeof(asn_DEF_reportingAmount_tags_2[0]) - 1, /* 1 */
	asn_DEF_reportingAmount_tags_2,	/* Same as above */
	sizeof(asn_DEF_reportingAmount_tags_2)
		/sizeof(asn_DEF_reportingAmount_tags_2[0]), /* 2 */
	&asn_PER_reportingAmount_constr_2,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportingAmount_specs_2	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_reportingInterval_value2enum_11[] = {
	{ 0,	21,	"noPeriodicalReporting" },
	{ 1,	6,	"ri0-25" },
	{ 2,	5,	"ri0-5" },
	{ 3,	3,	"ri1" },
	{ 4,	3,	"ri2" },
	{ 5,	3,	"ri4" },
	{ 6,	3,	"ri8" },
	{ 7,	4,	"ri16" },
	{ 8,	4,	"ri32" },
	{ 9,	4,	"ri64" }
};
static unsigned int asn_MAP_reportingInterval_enum2value_11[] = {
	0,	/* noPeriodicalReporting(0) */
	1,	/* ri0-25(1) */
	2,	/* ri0-5(2) */
	3,	/* ri1(3) */
	7,	/* ri16(7) */
	4,	/* ri2(4) */
	8,	/* ri32(8) */
	5,	/* ri4(5) */
	9,	/* ri64(9) */
	6	/* ri8(6) */
};
static asn_INTEGER_specifics_t asn_SPC_reportingInterval_specs_11 = {
	asn_MAP_reportingInterval_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_reportingInterval_enum2value_11,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1	/* Strict enumeration */
};
static ber_tlv_tag_t asn_DEF_reportingInterval_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static asn_per_constraints_t asn_PER_reportingInterval_constr_11 = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportingInterval_11 = {
	"reportingInterval",
	"reportingInterval",
	reportingInterval_11_free,
	reportingInterval_11_print,
	reportingInterval_11_constraint,
	reportingInterval_11_decode_ber,
	reportingInterval_11_encode_der,
	reportingInterval_11_decode_xer,
	reportingInterval_11_encode_xer,
	reportingInterval_11_decode_uper,
	reportingInterval_11_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_reportingInterval_tags_11,
	sizeof(asn_DEF_reportingInterval_tags_11)
		/sizeof(asn_DEF_reportingInterval_tags_11[0]) - 1, /* 1 */
	asn_DEF_reportingInterval_tags_11,	/* Same as above */
	sizeof(asn_DEF_reportingInterval_tags_11)
		/sizeof(asn_DEF_reportingInterval_tags_11[0]), /* 2 */
	&asn_PER_reportingInterval_constr_11,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportingInterval_specs_11	/* Additional specs */
};

static asn_per_constraints_t asn_PER_memb_reportingAmount_constr_2 = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_reportingInterval_constr_11 = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_LPP_PeriodicalReportingCriteria_1[] = {
	{ ATF_POINTER, 1, offsetof(struct LPP_PeriodicalReportingCriteria, reportingAmount),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportingAmount_2,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_memb_reportingAmount_constr_2,
		asn_DFL_2_set_7,	/* DEFAULT 7 */
		"reportingAmount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_PeriodicalReportingCriteria, reportingInterval),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportingInterval_11,
		0,	/* Defer constraints checking to the member type */
		&asn_PER_memb_reportingInterval_constr_11,
		0,
		"reportingInterval"
		},
};
static int asn_MAP_LPP_PeriodicalReportingCriteria_oms_1[] = { 0 };
static ber_tlv_tag_t asn_DEF_LPP_PeriodicalReportingCriteria_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LPP_PeriodicalReportingCriteria_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportingAmount at 2754 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reportingInterval at 2758 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LPP_PeriodicalReportingCriteria_specs_1 = {
	sizeof(struct LPP_PeriodicalReportingCriteria),
	offsetof(struct LPP_PeriodicalReportingCriteria, _asn_ctx),
	asn_MAP_LPP_PeriodicalReportingCriteria_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_LPP_PeriodicalReportingCriteria_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LPP_PeriodicalReportingCriteria = {
	"LPP_PeriodicalReportingCriteria",
	"LPP_PeriodicalReportingCriteria",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LPP_PeriodicalReportingCriteria_tags_1,
	sizeof(asn_DEF_LPP_PeriodicalReportingCriteria_tags_1)
		/sizeof(asn_DEF_LPP_PeriodicalReportingCriteria_tags_1[0]), /* 1 */
	asn_DEF_LPP_PeriodicalReportingCriteria_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_PeriodicalReportingCriteria_tags_1)
		/sizeof(asn_DEF_LPP_PeriodicalReportingCriteria_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LPP_PeriodicalReportingCriteria_1,
	2,	/* Elements count */
	&asn_SPC_LPP_PeriodicalReportingCriteria_specs_1	/* Additional specs */
};

