/*
 * LPP_ReqNavListInfo.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: sunilsatish.rao@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP_PDU-Definitions"
 * 	found in "LPP_RRLP_Rel_10.asn"
 * 	`asn1c -gen-PER`
 */

#include <asn_internal.h>

#include "LPP_ReqNavListInfo.h"

static int
memb_NativeInteger_constraint_3(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NativeInteger_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_svReqList_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_clockModelID_PrefList_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_orbitModelID_PrefList_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_Member_constr_4 = {
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (1..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_clockModelID_PrefList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_NativeInteger_constraint_3,
		&asn_PER_memb_Member_constr_4,
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_clockModelID_PrefList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_clockModelID_PrefList_specs_3 = {
	sizeof(struct LPP_ReqNavListInfo__clockModelID_PrefList),
	offsetof(struct LPP_ReqNavListInfo__clockModelID_PrefList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static asn_per_constraints_t asn_PER_clockModelID_PrefList_constr_3 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_clockModelID_PrefList_3 = {
	"clockModelID-PrefList",
	"clockModelID-PrefList",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_clockModelID_PrefList_tags_3,
	sizeof(asn_DEF_clockModelID_PrefList_tags_3)
		/sizeof(asn_DEF_clockModelID_PrefList_tags_3[0]) - 1, /* 1 */
	asn_DEF_clockModelID_PrefList_tags_3,	/* Same as above */
	sizeof(asn_DEF_clockModelID_PrefList_tags_3)
		/sizeof(asn_DEF_clockModelID_PrefList_tags_3[0]), /* 2 */
	&asn_PER_clockModelID_PrefList_constr_3,
	asn_MBR_clockModelID_PrefList_3,
	1,	/* Single element */
	&asn_SPC_clockModelID_PrefList_specs_3	/* Additional specs */
};

static asn_per_constraints_t asn_PER_memb_Member_constr_6 = {
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (1..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_orbitModelID_PrefList_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_NativeInteger_constraint_5,
		&asn_PER_memb_Member_constr_6,
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_orbitModelID_PrefList_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_orbitModelID_PrefList_specs_5 = {
	sizeof(struct LPP_ReqNavListInfo__orbitModelID_PrefList),
	offsetof(struct LPP_ReqNavListInfo__orbitModelID_PrefList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static asn_per_constraints_t asn_PER_orbitModelID_PrefList_constr_5 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_orbitModelID_PrefList_5 = {
	"orbitModelID-PrefList",
	"orbitModelID-PrefList",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_orbitModelID_PrefList_tags_5,
	sizeof(asn_DEF_orbitModelID_PrefList_tags_5)
		/sizeof(asn_DEF_orbitModelID_PrefList_tags_5[0]) - 1, /* 1 */
	asn_DEF_orbitModelID_PrefList_tags_5,	/* Same as above */
	sizeof(asn_DEF_orbitModelID_PrefList_tags_5)
		/sizeof(asn_DEF_orbitModelID_PrefList_tags_5[0]), /* 2 */
	&asn_PER_orbitModelID_PrefList_constr_5,
	asn_MBR_orbitModelID_PrefList_5,
	1,	/* Single element */
	&asn_SPC_orbitModelID_PrefList_specs_5	/* Additional specs */
};

static asn_per_constraints_t asn_PER_memb_svReqList_constr_2 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  64,  64 }	/* (SIZE(64..64)) */
};
static asn_per_constraints_t asn_PER_memb_clockModelID_PrefList_constr_3 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */
};
static asn_per_constraints_t asn_PER_memb_orbitModelID_PrefList_constr_5 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */
};
static asn_TYPE_member_t asn_MBR_LPP_ReqNavListInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_ReqNavListInfo, svReqList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_svReqList_constraint_1,
		&asn_PER_memb_svReqList_constr_2,
		0,
		"svReqList"
		},
	{ ATF_POINTER, 3, offsetof(struct LPP_ReqNavListInfo, clockModelID_PrefList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_clockModelID_PrefList_3,
		memb_clockModelID_PrefList_constraint_1,
		&asn_PER_memb_clockModelID_PrefList_constr_3,
		0,
		"clockModelID-PrefList"
		},
	{ ATF_POINTER, 2, offsetof(struct LPP_ReqNavListInfo, orbitModelID_PrefList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_orbitModelID_PrefList_5,
		memb_orbitModelID_PrefList_constraint_1,
		&asn_PER_memb_orbitModelID_PrefList_constr_5,
		0,
		"orbitModelID-PrefList"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_ReqNavListInfo, addNavparamReq),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"addNavparamReq"
		},
};
static int asn_MAP_LPP_ReqNavListInfo_oms_1[] = { 1, 2, 3 };
static ber_tlv_tag_t asn_DEF_LPP_ReqNavListInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LPP_ReqNavListInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* svReqList at 3754 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* clockModelID-PrefList at 3755 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* orbitModelID-PrefList at 3756 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* addNavparamReq at 3757 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LPP_ReqNavListInfo_specs_1 = {
	sizeof(struct LPP_ReqNavListInfo),
	offsetof(struct LPP_ReqNavListInfo, _asn_ctx),
	asn_MAP_LPP_ReqNavListInfo_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LPP_ReqNavListInfo_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LPP_ReqNavListInfo = {
	"LPP_ReqNavListInfo",
	"LPP_ReqNavListInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LPP_ReqNavListInfo_tags_1,
	sizeof(asn_DEF_LPP_ReqNavListInfo_tags_1)
		/sizeof(asn_DEF_LPP_ReqNavListInfo_tags_1[0]), /* 1 */
	asn_DEF_LPP_ReqNavListInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_ReqNavListInfo_tags_1)
		/sizeof(asn_DEF_LPP_ReqNavListInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LPP_ReqNavListInfo_1,
	4,	/* Elements count */
	&asn_SPC_LPP_ReqNavListInfo_specs_1	/* Additional specs */
};

