/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */


/**
 * Includes							       
 */
#include "mtf_api.h"
#include "hed_api.h"
#include "stdio.h"
/****************************************************************************/
/**
 * \brief   retrieve infos from Slice Error Status Buffer generated by HED.
 * \author  cyril enault
 * \param   addr_isbg
 * \param   ptr on structure t_sesb.
 * \note        read Slice Error Status  
 * 
 **/
/****************************************************************************/

void HED_GET_SLICE_HEADER(t_uint32 addr_isbg, t_hed_slice_header *ptr_hed_sesb)
{
    /* SESB */
    /*     31|   30| 29   21|20      16|15    0
     *  error| last| first_mb_in_slice | MBAddr
     *  -------------------| SlicePointerOffset
     */                    
     t_uint16 i;
    t_uint32 tmp_table[2]; /* 2 t_uint32 table for temporary data from MTF */
    //printf("addr_isbg 0x%.8lX\n",addr_isbg);
    //printf("MTF_SWAP_BYTE_NO_SWAP_WORD64 :\n");
    mtf_read_table(addr_isbg,
                   &tmp_table[0],
                   4, /* len == 2 */
                   1, /* incr == 1 */
                   MTF_SWAP_BYTE_NO_SWAP_WORD64);
    //for (i = 0; i < 4/2; i++)
    //   printf("\t%d : %.8lX\n",i,tmp_table[i]);
    ptr_hed_sesb->MBAddr =              LS_SHORT(tmp_table[0]);
    ptr_hed_sesb->first_mb_in_slice =   wextract(MS_SHORT(tmp_table[0]),0xE00);
    ptr_hed_sesb->lastSlice =           wextractu(MS_SHORT(tmp_table[0]),0x10E);
    ptr_hed_sesb->error_status =        wextractu(MS_SHORT(tmp_table[0]),0x10F);
    ptr_hed_sesb->SlicePointerOffset =  (tmp_table[1])&0x1FFFFFUL;
}
void HED_GET_SLICE_HEADER_LOC(t_uint32 *ptr_loc_isbg, t_hed_slice_header *ptr_hed_sesb)
{
    /* SESB */
    /*     31|   30| 29   21|20      16|15    0
     *  error| last| first_mb_in_slice | MBAddr
     *  -------------------| SlicePointerOffset
     */                    
    ptr_hed_sesb->MBAddr =              LS_SHORT(*ptr_loc_isbg);
    ptr_hed_sesb->first_mb_in_slice =   wextract(MS_SHORT(*ptr_loc_isbg),0xE00);
    ptr_hed_sesb->lastSlice =           wextractu(MS_SHORT(*ptr_loc_isbg),0x10E);
    ptr_hed_sesb->error_status =        wextractu(MS_SHORT(*ptr_loc_isbg++),0x10F);
    ptr_hed_sesb->SlicePointerOffset =  (*ptr_loc_isbg)&0x1FFFFFUL;
}

