BUILD_MMDSP_PROC_audio/virtual_surround=bin
NO_STD_BUILD_audio/virtual_surround=1
BUILD_MMDSP_NMF_audio/virtual_surround=bin
BUILD_ARM_PROC_audio/virtual_surround=bin
BUILD_ARM_CODE_audio/virtual_surround=bin
BUILD_ARM_NMF_audio/virtual_surround=bin
BUILD_XP70_SIA_CODE_audio/virtual_surround=false
