/*****************************************************************************/
/*
 *  © ST-Ericsson, 2009 - All rights reserved
 *  Reproduction and Communication of this document is strictly
 *  prohibited
 *  unless specifically authorized in writing by ST-Ericsson
 *
 * \brief   interface function declaration 
 * \author  ST-Ericsson
 */
/*****************************************************************************/
#include <t1xhv_common.idt>
#include <t1xhv_vdc_mpeg4.idt>
interface mpeg4dec.mpc.api.end_algodeblock {

void endAlgoDeblock(t_t1xhv_status status, t_t1xhv_decoder_info info, t_uint32 durationInTicks, t_uint32 bitstream_size);

}


