BUILD_MMDSP_PROC_imaging/redeye_detector=bin
NO_STD_BUILD_imaging/redeye_detector=1
BUILD_MMDSP_NMF_imaging/redeye_detector=bin
BUILD_ARM_PROC_imaging/redeye_detector=bin
BUILD_ARM_CODE_imaging/redeye_detector=bin
BUILD_ARM_NMF_imaging/redeye_detector=bin
BUILD_XP70_SIA_CODE_imaging/redeye_detector=false
