#
# Copyright (C) ST-Ericsson SA 2011. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

include $(MM_MAKEFILES_DIR)/SharedConfig.mk

INSTALL_HEADER = osi_trace.h debug_trace.h

todo: header

test:

include $(MM_MAKEFILES_DIR)/SharedRules.mk
