/*
 * Copyright (C) ST-Ericsson SA 2011. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

#include <stdio.h>
#include "cn_message_types.h"
#include "message_handler.h"
#include "cn_macros.h"

message_string_entry_t message_string_table[] = {
    { CN_REQUEST_READ_OPL_FROM_SIM, "CN_REQUEST_READ_OPL_FROM_SIM" },
    { CN_REQUEST_SET_DEFAULT_NVMD, "CN_REQUEST_SET_DEFAULT_NVMD" },
    { CN_REQUEST_RF_ON, "CN_REQUEST_RF_ON" },
    { CN_REQUEST_RF_OFF, "CN_REQUEST_RF_OFF" },
    { CN_REQUEST_RF_STATUS, "CN_REQUEST_RF_STATUS" },
    { CN_REQUEST_REGISTRATION_CONTROL, "CN_REQUEST_REGISTRATION_CONTROL" },
    { CN_REQUEST_RESET_MODEM, "CN_REQUEST_RESET_MODEM" },
    { CN_REQUEST_SET_PREFERRED_NETWORK_TYPE, "CN_REQUEST_SET_PREFERRED_NETWORK_TYPE" },
    { CN_REQUEST_GET_PREFERRED_NETWORK_TYPE, "CN_REQUEST_GET_PREFERRED_NETWORK_TYPE" },
    { CN_REQUEST_REGISTRATION_STATE_NORMAL, "CN_REQUEST_REGISTRATION_STATE_NORMAL" },
    { CN_REQUEST_REGISTRATION_STATE_GPRS, "CN_REQUEST_REGISTRATION_STATE_GPRS" },
    { CN_REQUEST_NETWORK_EMERGENCY_NUMBERS_UPDATE, "CN_REQUEST_NETWORK_EMERGENCY_NUMBERS_UPDATE" },
    { CN_REQUEST_CELL_INFO, "CN_REQUEST_CELL_INFO" },
    { CN_REQUEST_AUTOMATIC_NETWORK_REGISTRATION, "CN_REQUEST_AUTOMATIC_NETWORK_REGISTRATION" },
    { CN_REQUEST_MANUAL_NETWORK_REGISTRATION, "CN_REQUEST_MANUAL_NETWORK_REGISTRATION" },
    { CN_REQUEST_MANUAL_NETWORK_REGISTRATION_WITH_AUTOMATIC_FALLBACK, "CN_REQUEST_MANUAL_NETWORK_REGISTRATION_WITH_AUTOMATIC_FALLBACK" },
    { CN_REQUEST_NETWORK_DEREGISTER, "CN_REQUEST_NETWORK_DEREGISTER" },
    { CN_REQUEST_NET_QUERY_MODE, "CN_REQUEST_NET_QUERY_MODE" },
    { CN_REQUEST_MANUAL_NETWORK_SEARCH, "CN_REQUEST_MANUAL_NETWORK_SEARCH" },
    { CN_REQUEST_INTERRUPT_NETWORK_SEARCH, "CN_REQUEST_INTERRUPT_NETWORK_SEARCH" },
    { CN_REQUEST_CURRENT_CALL_LIST, "CN_REQUEST_CURRENT_CALL_LIST" },
    { CN_REQUEST_DIAL, "CN_REQUEST_DIAL" },
    { CN_REQUEST_HANGUP, "CN_REQUEST_HANGUP" },
    { CN_REQUEST_SWAP_CALLS, "CN_REQUEST_SWAP_CALLS" },
    { CN_REQUEST_HOLD_CALL, "CN_REQUEST_HOLD_CALL" },
    { CN_REQUEST_RESUME_CALL, "CN_REQUEST_RESUME_CALL" },
    { CN_REQUEST_CONFERENCE_CALL, "CN_REQUEST_CONFERENCE_CALL" },
    { CN_REQUEST_CONFERENCE_CALL_SPLIT, "CN_REQUEST_CONFERENCE_CALL_SPLIT" },
    { CN_REQUEST_EXPLICIT_CALL_TRANSFER, "CN_REQUEST_EXPLICIT_CALL_TRANSFER" },
    { CN_REQUEST_ANSWER_CALL, "CN_REQUEST_ANSWER_CALL" },
    { CN_REQUEST_USSD, "CN_REQUEST_USSD" },
    { CN_REQUEST_USSD_ABORT, "CN_REQUEST_USSD_ABORT" },
    { CN_REQUEST_SET_SIGNAL_INFO_CONFIG, "CN_REQUEST_SET_SIGNAL_INFO_CONFIG" },
    { CN_REQUEST_GET_SIGNAL_INFO_CONFIG, "CN_REQUEST_GET_SIGNAL_INFO_CONFIG" },
    { CN_REQUEST_SET_SIGNAL_INFO_REPORTING, "CN_REQUEST_SET_SIGNAL_INFO_REPORTING" },
    { CN_REQUEST_GET_SIGNAL_INFO_REPORTING, "CN_REQUEST_GET_SIGNAL_INFO_REPORTING" },
    { CN_REQUEST_RSSI_VALUE, "CN_REQUEST_RSSI_VALUE" },
    { CN_REQUEST_CLIP_STATUS, "CN_REQUEST_CLIP_STATUS" },
    { CN_REQUEST_CLIR_STATUS, "CN_REQUEST_CLIR_STATUS" },
    { CN_REQUEST_CNAP_STATUS, "CN_REQUEST_CNAP_STATUS" },
    { CN_REQUEST_COLR_STATUS, "CN_REQUEST_COLR_STATUS" },
    { CN_REQUEST_SET_CLIR, "CN_REQUEST_SET_CLIR" },
    { CN_REQUEST_QUERY_CALL_FORWARD, "CN_REQUEST_QUERY_CALL_FORWARD" },
    { CN_REQUEST_SET_CALL_FORWARD, "CN_REQUEST_SET_CALL_FORWARD" },
    { CN_REQUEST_SET_MODEM_PROPERTY, "CN_REQUEST_SET_MODEM_PROPERTY" },
    { CN_REQUEST_GET_MODEM_PROPERTY, "CN_REQUEST_GET_MODEM_PROPERTY" },
    { CN_REQUEST_SET_CSSN, "CN_REQUEST_SET_CSSN" },
    { CN_REQUEST_DTMF_SEND, "CN_REQUEST_DTMF_SEND" },
    { CN_REQUEST_DTMF_START, "CN_REQUEST_DTMF_START" },
    { CN_REQUEST_DTMF_STOP, "CN_REQUEST_DTMF_STOP" },
    { CN_REQUEST_SET_CALL_WAITING, "CN_REQUEST_SET_CALL_WAITING" },
    { CN_REQUEST_GET_CALL_WAITING, "CN_REQUEST_GET_CALL_WAITING" },
    { CN_REQUEST_CHANGE_BARRING_PASSWORD, "CN_REQUEST_CHANGE_BARRING_PASSWORD" },
    { CN_REQUEST_QUERY_CALL_BARRING, "CN_REQUEST_QUERY_CALL_BARRING" },
    { CN_REQUEST_SET_CALL_BARRING, "CN_REQUEST_SET_CALL_BARRING" },
    { CN_REQUEST_SET_PRODUCT_PROFILE_FLAG, "CN_REQUEST_SET_PRODUCT_PROFILE_FLAG" },
    { CN_REQUEST_SET_L1_PARAMETER, "CN_REQUEST_SET_L1_PARAMETER" },
    { CN_REQUEST_SET_USER_ACTIVITY_STATUS, "CN_REQUEST_SET_USER_ACTIVITY_STATUS" },
    { CN_REQUEST_SET_NEIGHBOUR_CELLS_REPORTING, "CN_REQUEST_SET_NEIGHBOUR_CELLS_REPORTING" },
    { CN_REQUEST_GET_NEIGHBOUR_CELLS_REPORTING, "CN_REQUEST_GET_NEIGHBOUR_CELLS_REPORTING" },
    { CN_REQUEST_GET_NEIGHBOUR_CELLS_COMPLETE_INFO, "CN_REQUEST_GET_NEIGHBOUR_CELLS_COMPLETE_INFO" },
    { CN_REQUEST_SET_EVENT_REPORTING, "CN_REQUEST_SET_EVENT_REPORTING" },
    { CN_REQUEST_GET_EVENT_REPORTING, "CN_REQUEST_GET_EVENT_REPORTING" },
    { CN_REQUEST_GET_RAB_STATUS, "CN_REQUEST_GET_RAB_STATUS" },
    { CN_REQUEST_BASEBAND_VERSION, "CN_REQUEST_BASEBAND_VERSION" },
    { CN_REQUEST_GET_PP_FLAGS, "CN_REQUEST_GET_PP_FLAGS" },
    { CN_REQUEST_MODIFY_EMERGENCY_NUMBER_LIST, "CN_REQUEST_MODIFY_EMERGENCY_NUMBER_LIST" },
    { CN_REQUEST_GET_EMERGENCY_NUMBER_LIST, "CN_REQUEST_GET_EMERGENCY_NUMBER_LIST" },
    { CN_REQUEST_TIMING_ADVANCE, "CN_REQUEST_TIMING_ADVANCE" },
    { CN_REQUEST_NMR_INFO, "CN_REQUEST_NMR_INFO" },
    { CN_REQUEST_SET_HSXPA_MODE, "CN_REQUEST_SET_HSXPA_MODE" },
    { CN_REQUEST_GET_HSXPA_MODE, "CN_REQUEST_GET_HSXPA_MODE" },
    { CN_REQUEST_SS, "CN_REQUEST_SS" },
    { CN_REQUEST_SET_MANDATED_NETWORK_TYPE_FROM_SIM, "CN_REQUEST_SET_MANDATED_NETWORK_TYPE_FROM_SIM" },
    { CN_REQUEST_SET_EMPAGE, "CN_REQUEST_SET_EMPAGE" },
    { CN_REQUEST_RESET_MODEM_WITH_DUMP, "CN_REQUEST_RESET_MODEM_WITH_DUMP"},
    { CN_REQUEST_SLEEP_TEST_MODE, "CN_REQUEST_SLEEP_TEST_MODE"},
    { CN_REQUEST_GET_NEIGHBOUR_CELLS_EXTD_INFO, "CN_REQUEST_GET_NEIGHBOUR_CELLS_ECID_INFO"},
    { CN_REQUEST_UNKNOWN, NULL } /* termination entry */
};

char *lookup_message_table(cn_message_type_t msg_type)
{
    int i = 0;

    while (CN_REQUEST_UNKNOWN != message_string_table[i].msg_type) {
        if (msg_type == message_string_table[i].msg_type) {
            return (char *)message_string_table[i].msg_string_p;
        }

        i++;
    }

    return NULL;
}

