/*
 * SUPL_ULP_AreaId.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-START"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_AreaId.h"

static asn_per_constraints_t asn_PER_type_AreaId_constr_1 = {
    { APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }    /* (0..7,...) */,
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    0, 0    /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_AreaId_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.gSMAreaId),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_GSMAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "gSMAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.wCDMAAreaId),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_WCDMAAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "wCDMAAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.cDMAAreaId),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_CDMAAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "cDMAAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.hRPDAreaId),
        (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_HRPDAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "hRPDAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.uMBAreaId),
        (ASN_TAG_CLASS_CONTEXT | (4 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_UMBAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "uMBAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.lTEAreaId),
        (ASN_TAG_CLASS_CONTEXT | (5 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_LTEAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "lTEAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.wLANAreaId),
        (ASN_TAG_CLASS_CONTEXT | (6 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_WLANAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "wLANAreaId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct AreaId, choice.wiMAXAreaId),
        (ASN_TAG_CLASS_CONTEXT | (7 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_WimaxAreaId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "wiMAXAreaId"
        },
};
static asn_TYPE_tag2member_t asn_MAP_AreaId_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gSMAreaId at 505 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* wCDMAAreaId at 506 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cDMAAreaId at 507 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* hRPDAreaId at 508 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uMBAreaId at 509 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* lTEAreaId at 510 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* wLANAreaId at 511 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* wiMAXAreaId at 512 */
};
static asn_CHOICE_specifics_t asn_SPC_AreaId_specs_1 = {
    sizeof(struct AreaId),
    offsetof(struct AreaId, _asn_ctx),
    offsetof(struct AreaId, present),
    sizeof(((struct AreaId *)0)->present),
    asn_MAP_AreaId_tag2el_1,
    8,    /* Count of tags in the map */
    0,
    8    /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AreaId = {
    "AreaId",
    "AreaId",
    CHOICE_free,
    CHOICE_print,
    CHOICE_constraint,
    CHOICE_decode_ber,
    CHOICE_encode_der,
    CHOICE_decode_xer,
    CHOICE_encode_xer,
    CHOICE_decode_uper,
    CHOICE_encode_uper,
    CHOICE_outmost_tag,
    0,    /* No effective tags (pointer) */
    0,    /* No effective tags (count) */
    0,    /* No tags (pointer) */
    0,    /* No tags (count) */
    &asn_PER_type_AreaId_constr_1,
    asn_MBR_AreaId_1,
    8,    /* Elements count */
    &asn_SPC_AreaId_specs_1    /* Additional specs */
};

