/*
 * SUPL_ULP_FrequencyInfo.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_FrequencyInfo.h"

static asn_per_constraints_t asn_PER_type_modeSpecificInfo_constr_2 = {
    { APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }    /* (0..1,...) */,
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    0, 0    /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_modeSpecificInfo_2[] = {
    { ATF_NOFLAGS, 0, offsetof(struct FrequencyInfo__modeSpecificInfo, choice.fdd),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_FrequencyInfoFDD,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "fdd"
        },
    { ATF_NOFLAGS, 0, offsetof(struct FrequencyInfo__modeSpecificInfo, choice.tdd),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_FrequencyInfoTDD,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "tdd"
        },
};
static asn_TYPE_tag2member_t asn_MAP_modeSpecificInfo_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd at 1151 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd at 1152 */
};
static asn_CHOICE_specifics_t asn_SPC_modeSpecificInfo_specs_2 = {
    sizeof(struct FrequencyInfo__modeSpecificInfo),
    offsetof(struct FrequencyInfo__modeSpecificInfo, _asn_ctx),
    offsetof(struct FrequencyInfo__modeSpecificInfo, present),
    sizeof(((struct FrequencyInfo__modeSpecificInfo *)0)->present),
    asn_MAP_modeSpecificInfo_tag2el_2,
    2,    /* Count of tags in the map */
    0,
    2    /* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeSpecificInfo_2 = {
    "modeSpecificInfo",
    "modeSpecificInfo",
    CHOICE_free,
    CHOICE_print,
    CHOICE_constraint,
    CHOICE_decode_ber,
    CHOICE_encode_der,
    CHOICE_decode_xer,
    CHOICE_encode_xer,
    CHOICE_decode_uper,
    CHOICE_encode_uper,
    CHOICE_outmost_tag,
    0,    /* No effective tags (pointer) */
    0,    /* No effective tags (count) */
    0,    /* No tags (pointer) */
    0,    /* No tags (count) */
    &asn_PER_type_modeSpecificInfo_constr_2,
    asn_MBR_modeSpecificInfo_2,
    2,    /* Elements count */
    &asn_SPC_modeSpecificInfo_specs_2    /* Additional specs */
};

static asn_TYPE_member_t asn_MBR_FrequencyInfo_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct FrequencyInfo, modeSpecificInfo),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        +1,    /* EXPLICIT tag at current level */
        &asn_DEF_modeSpecificInfo_2,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "modeSpecificInfo"
        },
};
static ber_tlv_tag_t asn_DEF_FrequencyInfo_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_FrequencyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* modeSpecificInfo at 1151 */
};
static asn_SEQUENCE_specifics_t asn_SPC_FrequencyInfo_specs_1 = {
    sizeof(struct FrequencyInfo),
    offsetof(struct FrequencyInfo, _asn_ctx),
    asn_MAP_FrequencyInfo_tag2el_1,
    1,    /* Count of tags in the map */
    0, 0, 0,    /* Optional elements (not needed) */
    0,    /* Start extensions */
    2    /* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FrequencyInfo = {
    "FrequencyInfo",
    "FrequencyInfo",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_FrequencyInfo_tags_1,
    sizeof(asn_DEF_FrequencyInfo_tags_1)
        /sizeof(asn_DEF_FrequencyInfo_tags_1[0]), /* 1 */
    asn_DEF_FrequencyInfo_tags_1,    /* Same as above */
    sizeof(asn_DEF_FrequencyInfo_tags_1)
        /sizeof(asn_DEF_FrequencyInfo_tags_1[0]), /* 1 */
    0,    /* No PER visible constraints */
    asn_MBR_FrequencyInfo_1,
    1,    /* Elements count */
    &asn_SPC_FrequencyInfo_specs_1    /* Additional specs */
};

