/*
 * SUPL_ULP_MeasResultEUTRA.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_MeasResultEUTRA.h"

static asn_TYPE_member_t asn_MBR_cgi_Info_3[] = {
    { ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, cellGlobalId),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_CellGlobalIdEUTRA,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "cellGlobalId"
        },
    { ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, trackingAreaCode),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_TrackingAreaCode,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "trackingAreaCode"
        },
};
static ber_tlv_tag_t asn_DEF_cgi_Info_tags_3[] = {
    (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_cgi_Info_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId at 1463 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* trackingAreaCode at 1465 */
};
static asn_SEQUENCE_specifics_t asn_SPC_cgi_Info_specs_3 = {
    sizeof(struct MeasResultEUTRA__cgi_Info),
    offsetof(struct MeasResultEUTRA__cgi_Info, _asn_ctx),
    asn_MAP_cgi_Info_tag2el_3,
    2,    /* Count of tags in the map */
    0, 0, 0,    /* Optional elements (not needed) */
    -1,    /* Start extensions */
    -1    /* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cgi_Info_3 = {
    "cgi-Info",
    "cgi-Info",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_cgi_Info_tags_3,
    sizeof(asn_DEF_cgi_Info_tags_3)
        /sizeof(asn_DEF_cgi_Info_tags_3[0]) - 1, /* 1 */
    asn_DEF_cgi_Info_tags_3,    /* Same as above */
    sizeof(asn_DEF_cgi_Info_tags_3)
        /sizeof(asn_DEF_cgi_Info_tags_3[0]), /* 2 */
    0,    /* No PER visible constraints */
    asn_MBR_cgi_Info_3,
    2,    /* Elements count */
    &asn_SPC_cgi_Info_specs_3    /* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResult_6[] = {
    { ATF_POINTER, 2, offsetof(struct MeasResultEUTRA__measResult, rsrpResult),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_RSRP_Range,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "rsrpResult"
        },
    { ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__measResult, rsrqResult),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_RSRQ_Range,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "rsrqResult"
        },
};
static int asn_MAP_measResult_oms_6[] = { 0, 1 };
static ber_tlv_tag_t asn_DEF_measResult_tags_6[] = {
    (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_measResult_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult at 1467 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsrqResult at 1468 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResult_specs_6 = {
    sizeof(struct MeasResultEUTRA__measResult),
    offsetof(struct MeasResultEUTRA__measResult, _asn_ctx),
    asn_MAP_measResult_tag2el_6,
    2,    /* Count of tags in the map */
    asn_MAP_measResult_oms_6,    /* Optional members */
    2, 0,    /* Root/Additions */
    1,    /* Start extensions */
    3    /* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResult_6 = {
    "measResult",
    "measResult",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_measResult_tags_6,
    sizeof(asn_DEF_measResult_tags_6)
        /sizeof(asn_DEF_measResult_tags_6[0]) - 1, /* 1 */
    asn_DEF_measResult_tags_6,    /* Same as above */
    sizeof(asn_DEF_measResult_tags_6)
        /sizeof(asn_DEF_measResult_tags_6[0]), /* 2 */
    0,    /* No PER visible constraints */
    asn_MBR_measResult_6,
    2,    /* Elements count */
    &asn_SPC_measResult_specs_6    /* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MeasResultEUTRA_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, physCellId),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_PhysCellId,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "physCellId"
        },
    { ATF_POINTER, 1, offsetof(struct MeasResultEUTRA, cgi_Info),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        0,
        &asn_DEF_cgi_Info_3,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "cgi-Info"
        },
    { ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, measResult),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
        0,
        &asn_DEF_measResult_6,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "measResult"
        },
};
static int asn_MAP_MeasResultEUTRA_oms_1[] = { 1 };
static ber_tlv_tag_t asn_DEF_MeasResultEUTRA_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MeasResultEUTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId at 1461 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cgi-Info at 1463 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* measResult at 1467 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MeasResultEUTRA_specs_1 = {
    sizeof(struct MeasResultEUTRA),
    offsetof(struct MeasResultEUTRA, _asn_ctx),
    asn_MAP_MeasResultEUTRA_tag2el_1,
    3,    /* Count of tags in the map */
    asn_MAP_MeasResultEUTRA_oms_1,    /* Optional members */
    1, 0,    /* Root/Additions */
    -1,    /* Start extensions */
    -1    /* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MeasResultEUTRA = {
    "MeasResultEUTRA",
    "MeasResultEUTRA",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_MeasResultEUTRA_tags_1,
    sizeof(asn_DEF_MeasResultEUTRA_tags_1)
        /sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
    asn_DEF_MeasResultEUTRA_tags_1,    /* Same as above */
    sizeof(asn_DEF_MeasResultEUTRA_tags_1)
        /sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
    0,    /* No PER visible constraints */
    asn_MBR_MeasResultEUTRA_1,
    3,    /* Elements count */
    &asn_SPC_MeasResultEUTRA_specs_1    /* Additional specs */
};

