/*
 * SUPL_ULP_Ver2-CellInfo-extension.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_Ver2-CellInfo-extension.h"

static asn_per_constraints_t asn_PER_type_Ver2_CellInfo_extension_constr_1 = {
    { APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }    /* (0..4,...) */,
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    0, 0    /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Ver2_CellInfo_extension_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct Ver2_CellInfo_extension, choice.hrpdCell),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_HrpdCellInformation,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "hrpdCell"
        },
    { ATF_NOFLAGS, 0, offsetof(struct Ver2_CellInfo_extension, choice.umbCell),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_UmbCellInformation,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "umbCell"
        },
    { ATF_NOFLAGS, 0, offsetof(struct Ver2_CellInfo_extension, choice.lteCell),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_LteCellInformation,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "lteCell"
        },
    { ATF_NOFLAGS, 0, offsetof(struct Ver2_CellInfo_extension, choice.wlanAP),
        (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_WlanAPInformation,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "wlanAP"
        },
    { ATF_NOFLAGS, 0, offsetof(struct Ver2_CellInfo_extension, choice.wimaxBS),
        (ASN_TAG_CLASS_CONTEXT | (4 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_WimaxBSInformation,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "wimaxBS"
        },
};
static asn_TYPE_tag2member_t asn_MAP_Ver2_CellInfo_extension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* hrpdCell at 1418 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* umbCell at 1419 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* lteCell at 1420 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* wlanAP at 1421 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* wimaxBS at 1422 */
};
static asn_CHOICE_specifics_t asn_SPC_Ver2_CellInfo_extension_specs_1 = {
    sizeof(struct Ver2_CellInfo_extension),
    offsetof(struct Ver2_CellInfo_extension, _asn_ctx),
    offsetof(struct Ver2_CellInfo_extension, present),
    sizeof(((struct Ver2_CellInfo_extension *)0)->present),
    asn_MAP_Ver2_CellInfo_extension_tag2el_1,
    5,    /* Count of tags in the map */
    0,
    5    /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ver2_CellInfo_extension = {
    "Ver2-CellInfo-extension",
    "Ver2-CellInfo-extension",
    CHOICE_free,
    CHOICE_print,
    CHOICE_constraint,
    CHOICE_decode_ber,
    CHOICE_encode_der,
    CHOICE_decode_xer,
    CHOICE_encode_xer,
    CHOICE_decode_uper,
    CHOICE_encode_uper,
    CHOICE_outmost_tag,
    0,    /* No effective tags (pointer) */
    0,    /* No effective tags (count) */
    0,    /* No tags (pointer) */
    0,    /* No tags (count) */
    &asn_PER_type_Ver2_CellInfo_extension_constr_1,
    asn_MBR_Ver2_CellInfo_extension_1,
    5,    /* Elements count */
    &asn_SPC_Ver2_CellInfo_extension_specs_1    /* Additional specs */
};

