/*
 * SUPL_ULP_WimaxNMRList.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_WimaxNMRList.h"

static asn_per_constraints_t asn_PER_type_WimaxNMRList_constr_1 = {
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    { APC_CONSTRAINED,     5,  5,  1,  32 }    /* (SIZE(1..32)) */,
    0, 0    /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_WimaxNMRList_1[] = {
    { ATF_POINTER, 0, 0,
        (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
        0,
        &asn_DEF_WimaxNMR,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        ""
        },
};
static ber_tlv_tag_t asn_DEF_WimaxNMRList_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_WimaxNMRList_specs_1 = {
    sizeof(struct WimaxNMRList),
    offsetof(struct WimaxNMRList, _asn_ctx),
    0,    /* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_WimaxNMRList = {
    "WimaxNMRList",
    "WimaxNMRList",
    SEQUENCE_OF_free,
    SEQUENCE_OF_print,
    SEQUENCE_OF_constraint,
    SEQUENCE_OF_decode_ber,
    SEQUENCE_OF_encode_der,
    SEQUENCE_OF_decode_xer,
    SEQUENCE_OF_encode_xer,
    SEQUENCE_OF_decode_uper,
    SEQUENCE_OF_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_WimaxNMRList_tags_1,
    sizeof(asn_DEF_WimaxNMRList_tags_1)
        /sizeof(asn_DEF_WimaxNMRList_tags_1[0]), /* 1 */
    asn_DEF_WimaxNMRList_tags_1,    /* Same as above */
    sizeof(asn_DEF_WimaxNMRList_tags_1)
        /sizeof(asn_DEF_WimaxNMRList_tags_1[0]), /* 1 */
    &asn_PER_type_WimaxNMRList_constr_1,
    asn_MBR_WimaxNMRList_1,
    1,    /* Single element */
    &asn_SPC_WimaxNMRList_specs_1    /* Additional specs */
};

