/*
 * SUPL_ULP_ReportingCap.c
 *
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * Author: david.gowers@stericsson.com for ST-Ericsson.
 * License terms: Redistribution and modifications are permitted subject to BSD license. 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of ST-Ericsson nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ST-ERICSSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 *     found in "ULP_v2.0.0.asn"
 *     `asn1c -gen-PER -fcompound-names`
 */

#include <asn_internal.h>

#include "SUPL_ULP_ReportingCap.h"

static int
memb_minInt_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
            asn_app_constraint_failed_f *ctfailcb, void *app_key) {
    long value;
    
    if(!sptr) {
        _ASN_CTFAIL(app_key, td, sptr,
            "%s: value not given (%s:%d)",
            td->name, __FILE__, __LINE__);
        return -1;
    }
    
    value = *(const long *)sptr;
    
    if((value >= 1 && value <= 3600)) {
        /* Constraint check succeeded */
        return 0;
    } else {
        _ASN_CTFAIL(app_key, td, sptr,
            "%s: constraint failed (%s:%d)",
            td->name, __FILE__, __LINE__);
        return -1;
    }
}

static int
memb_maxInt_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
            asn_app_constraint_failed_f *ctfailcb, void *app_key) {
    long value;
    
    if(!sptr) {
        _ASN_CTFAIL(app_key, td, sptr,
            "%s: value not given (%s:%d)",
            td->name, __FILE__, __LINE__);
        return -1;
    }
    
    value = *(const long *)sptr;
    
    if((value >= 1 && value <= 1440)) {
        /* Constraint check succeeded */
        return 0;
    } else {
        _ASN_CTFAIL(app_key, td, sptr,
            "%s: constraint failed (%s:%d)",
            td->name, __FILE__, __LINE__);
        return -1;
    }
}

static asn_per_constraints_t asn_PER_memb_minInt_constr_2 = {
    { APC_CONSTRAINED,     12,  12,  1,  3600 }    /* (1..3600) */,
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    0, 0    /* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_maxInt_constr_3 = {
    { APC_CONSTRAINED,     11,  11,  1,  1440 }    /* (1..1440) */,
    { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
    0, 0    /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ReportingCap_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct ReportingCap, minInt),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_NativeInteger,
        memb_minInt_constraint_1,
        &asn_PER_memb_minInt_constr_2,
        0,
        "minInt"
        },
    { ATF_POINTER, 1, offsetof(struct ReportingCap, maxInt),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_NativeInteger,
        memb_maxInt_constraint_1,
        &asn_PER_memb_maxInt_constr_3,
        0,
        "maxInt"
        },
    { ATF_NOFLAGS, 0, offsetof(struct ReportingCap, repMode),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_RepModeSupport,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "repMode"
        },
    { ATF_POINTER, 1, offsetof(struct ReportingCap, batchRepCap),
        (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_BatchRepCap,
        0,    /* Defer constraints checking to the member type */
        0,    /* No PER visible constraints */
        0,
        "batchRepCap"
        },
};
static int asn_MAP_ReportingCap_oms_1[] = { 1, 3 };
static ber_tlv_tag_t asn_DEF_ReportingCap_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReportingCap_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* minInt at 1710 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxInt at 1711 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* repMode at 1712 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* batchRepCap at 1713 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReportingCap_specs_1 = {
    sizeof(struct ReportingCap),
    offsetof(struct ReportingCap, _asn_ctx),
    asn_MAP_ReportingCap_tag2el_1,
    4,    /* Count of tags in the map */
    asn_MAP_ReportingCap_oms_1,    /* Optional members */
    2, 0,    /* Root/Additions */
    3,    /* Start extensions */
    5    /* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReportingCap = {
    "ReportingCap",
    "ReportingCap",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0,    /* Use generic outmost tag fetcher */
    asn_DEF_ReportingCap_tags_1,
    sizeof(asn_DEF_ReportingCap_tags_1)
        /sizeof(asn_DEF_ReportingCap_tags_1[0]), /* 1 */
    asn_DEF_ReportingCap_tags_1,    /* Same as above */
    sizeof(asn_DEF_ReportingCap_tags_1)
        /sizeof(asn_DEF_ReportingCap_tags_1[0]), /* 1 */
    0,    /* No PER visible constraints */
    asn_MBR_ReportingCap_1,
    4,    /* Elements count */
    &asn_SPC_ReportingCap_specs_1    /* Additional specs */
};

