BUILD_MMDSP_PROC_video/components/exif_mixer=bin
NO_STD_BUILD_video/components/exif_mixer=1
BUILD_MMDSP_NMF_video/components/exif_mixer=bin
BUILD_ARM_PROC_video/components/exif_mixer=bin
BUILD_ARM_CODE_video/components/exif_mixer=src
BUILD_ARM_NMF_video/components/exif_mixer=src
BUILD_XP70_SIA_CODE_video/components/exif_mixer=false
