BUILD_MMDSP_PROC_video/components/vpp=bin
NO_STD_BUILD_video/components/vpp=1
BUILD_MMDSP_NMF_video/components/vpp=bin
BUILD_ARM_PROC_video/components/vpp=bin
BUILD_ARM_CODE_video/components/vpp=bin
BUILD_ARM_NMF_video/components/vpp=bin
BUILD_XP70_SIA_CODE_video/components/vpp=false
