# -*- Mode: Makefile -*-
# vim:syntax=make:
export PLATFORM
export SVA_SUBSYSTEM

all :
	make -C mpc/algo

install :
	make -C mpc/algo $@

clean realclean:
	make -C mpc/algo $@

#### Checking constraint from Symbian ##############
check_constraint:
