#
# Copyright (C) ST-Ericsson SA 2010. All rights reserved.
# This code is ST-Ericsson proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of ST-Ericsson SA.
#

# vim:syntax=make:
# -*- Mode: Makefile -*-
include $(MM_MAKEFILES_DIR)/AudioConfig.mk

VPATH += common/include

INSTALL_HEADER = amr.h

todo: install

include $(MM_MAKEFILES_DIR)/SharedRules.mk

test cleantest:
