/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */


interface exif_mixer.arm_nmf.api.log_event { 

  void eventProcessOutput();
  void eventProcess();
}
