/*
 * Copyright (C) ST-Ericsson SA 2010. All rights reserved.
 * This code is ST-Ericsson proprietary and confidential.
 * Any use of the code for whatever purpose is subject to
 * specific written permission of ST-Ericsson SA.
 */

interface exif_mixer.arm_nmf.api.setConfig { 

void setConfigure(t_uint32 index, void* opaque_ptr);
void setDimension(t_uint32 width, t_uint32 height);
}


