<HTML>
	<HEAD>
		<TITLE>Trace Viewer help -- <?php echo($title2); ?></TITLE>
		<LINK REL=Stylesheet TYPE="text/css" HREF="../../css/ostviewer_help.css">
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	</HEAD>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">

<BODY class='WhiteBackgnd, main'>

<table width="100%" cellpadding=4 cellspacing=0 border=0>
  <td valign="top">
    <tr>

      <td bgcolor="" align=left>
        <img src="../images/ostviewer_icon_64x64.gif" width=64 height=64
        ALT="Trace Viewer Logo">
      </td>
      
      <td bgcolor="">
      </td>

      <td class= 'HeaderBanner' align=left valign=top width="100%">

        <p class= 'TitleBig'>
         <?php echo($title1); ?>
        </p>

        <p class= 'TitleMedium'>
        <?php echo($title2); ?>
        </p>

      </td>

    </tr>
  </td>
</table>

