BUILD_MMDSP_PROC_audio/mdrc=bin
NO_STD_BUILD_audio/mdrc=1
BUILD_MMDSP_NMF_audio/mdrc=bin
BUILD_ARM_PROC_audio/mdrc=bin
BUILD_ARM_CODE_audio/mdrc=bin
BUILD_ARM_NMF_audio/mdrc=bin
BUILD_XP70_SIA_CODE_audio/mdrc=false
