/*****************************************************************************/
/**
*  © ST-Ericsson, 2009 - All rights reserved
*  Reproduction and Communication of this document is strictly prohibited
*  unless specifically authorized in writing by ST-Ericsson
*
* \file    
* \brief   
* \author  ST-Ericsson
*/
/*****************************************************************************/

#include <t1xhv_common.idt>
#include <t1xhv_post_process.idt>
#include <t1xhv_pp.idt>
#include <t1xhv_retarget.idt>
#include <t1xhv_vdc.idt>
#include <t1xhv_vec.idt>
#include <vfm_common.idt>


interface resource_manager.api.common_interface_exports { 
/* This is used to export singally all common header files 
which are generated multiple times inside each codec component
*/
void common_interface_exports(void);
}

