/*****************************************************************************/
/**
*  © ST-Ericsson, 2009 - All rights reserved
*  Reproduction and Communication of this document is strictly prohibited
*  unless specifically authorized in writing by ST-Ericsson
*
* \file    
* \brief   
* \author  ST-Ericsson
*/
/*****************************************************************************/

#include <t1xhv_common.idt>
#include <t1xhv_resource_manager.idt>

interface resource_manager.api.inform_resource_status {

/** @addtogroup rmInformResourceGroup informResourceStatus
 *  @ingroup rmRequiredInterfaceGroup
 *  @{ 
 */
/*!
 Description : Interface to inform the status of a resource allocation request.
 

 \param[in]  status  Status of the allocation request.
 \param[in]  resource The specified resource
 *
 * \remarks	For the corresponding ITF server name(s), please refer to \ref rmConfigurationGroup 
 */

void informResourceStatus(t_t1xhv_resource_status status, t_t1xhv_resource resource);

/** @} */ // end of rmInformResourceGroup


}
