BUILD_MMDSP_PROC_audio/stereowidener=bin
NO_STD_BUILD_audio/stereowidener=1
BUILD_MMDSP_NMF_audio/stereowidener=bin
BUILD_ARM_PROC_audio/stereowidener=bin
BUILD_ARM_CODE_audio/stereowidener=src
BUILD_ARM_NMF_audio/stereowidener=src
BUILD_XP70_SIA_CODE_audio/stereowidener=false
