# -*- Mode: Makefile -*-
# vim:syntax=make:

#-----------------------
# List of Directory
#-----------------------
include $(MM_MAKEFILES_DIR)/SharedCheck.mk

DIRECTORIES= amrwbdec amrwbenc

include $(MM_MAKEFILES_DIR)/SharedDispatch.mk


